### ISSUE TITLE
[BUG] Endpoints are not working

### ISSUE THREAD

**Issue by marcouberti** [immuni-app/immuni-app-android#1]
**Describe the bug**

The application currently points to endpoints that are not publicly accessible. The application works nonetheless, however it would be better to have working endpoints.

**To Reproduce**

1. Open the application
2. Observe that the configuration is not fetched

**Expected behavior**

The application should be able to reach remote endpoints

**Smartphone (please complete the following information):**

- Device: any
- OS: Android 6+
- Version 1

**Comment by Efesto** [comment]
I think is an expected behavior (or at least is known) 👉  https://github.com/immuni-app/immuni-app-android/blob/master/README.md#backend-services
