### ISSUE TITLE
[GENERAL] Duplicated dependency line

### ISSUE THREAD

**Issue by ndorigatti** [immuni-app/immuni-app-android#10]
https://github.com/immuni-app/immuni-app-android/blob/8c4739b471754977ea42b5cc2090cd28804a141f/app/build.gradle#L132

glide annotation processor is duplicated

**Comment by immuniopensource** [comment]
Hi @ndorigatti and thanks for your contribution!
This issue has been fixed by #11 and it's currently merged in master. 
Closing, thanks again :+1:
