### ISSUE TITLE
[BUG] No push notification is received to alert that the service is inactive if Exposure Notifications are turned off

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#106]
**Describe the bug**

If the user gives consent to receive _Immuni notifications_ but _Exposure Notifications_ are turned off, no push notification is received to alert that the service is inactive. The user can see that the service is inactive only by opening the app.

**To Reproduce**

1. Give consent to receive Immuni notifications
2. Go to Settings > Google > COVID-19 exposure notifications
3. Tap to `Turn off exposure notifications` and Confirm
4. Open the app and observe that the Service is inactive
--> No push notification is sent to alert the user.

**Expected behaviour**

A push notification should be sent to alert that the service is inactive.

**Comment by sroddy** [comment]
After #115 is merged, the notification should arrive within 15 minutes since you toggle off the service after having toggled it on and waited for at least 15 minutes.

**Comment by LauraB-QA** [comment]
Fix verified in v1.0.1
