### ISSUE TITLE
[FEAT] English language

### ISSUE THREAD

**Issue by Efesto** [immuni-app/immuni-app-android#12]
The app interface doesn't support English language.

I think this feature is important considering the presence of non-italian speakers in the country like seasonal workers and immigrants.

**Comment by enricocid** [comment]
It makes no sense.
values -> strings -> English
values-it -> strings -> Italian

Also, You should use a localisation service too.

**Comment by powext** [comment]
> Also, You should use a localization service too.
Not necessary, also because it doesn't make sense, the English translations would be useful only to people in Italy, so why localization services?

However, using localization services to properly set the user language is a bad practice, you should always follow the operating system language.

**Comment by spectrumIG** [comment]
> It makes no sense.
> values -> strings -> English
> values-it -> strings -> Italian
> 
> Also, You should use a localisation service too.

What's the problems with that structure of translations? It's simply the default for an Android Project. Also why a localization service? Is not a standard practice.

**Comment by marcouberti** [comment]
Hi @Efesto, sure we are working on localisation in another branch. The app will be localised in many languages including of course english.

**Comment by 4face-studi0** [comment]
Why you guys hate to follow the Issue's template?

**Comment by gvdr** [comment]
@marcouberti can you please let us know which languages are you working on?

**Comment by ilovelinux** [comment]
Implemented in commit https://github.com/immuni-app/immuni-app-android/commit/ce40a25d85510c1bd73183f362fc43c21216b41d

**Comment by Efesto** [comment]
Closing this because it's solved
