### ISSUE TITLE
generazione del codice OTP

### ISSUE THREAD

**Issue by ghost** [immuni-app/immuni-app-android#121]
perché la generazione del codice OTP avviene ogni volta che si apre la schermata di "caricamento dati" e non avviene mediante temporizzazione? 
si potrebbe forzare un device ad avere lo stesso OTP di un altro mediante una riapertura automatica della scheda.

**Comment by Cipulot** [comment]
EN: why the generation of the OTP code occurs every time the "data loading" screen is opened and does not occur by timing? You could force a device to have the same OTP as another by automatically reopening the card.

**Comment by immuniopensource** [comment]
Buongiorno @oppo99, in linea di massima che due dispositivi mostrino lo stesso OTP nella schermata di "Caricamento dati" non è un problema, ma potrebbe diventarlo nel caso la collisione avvenga in una fase di upload. In linea teorica due dispositivi potrebbero utilizzare lo stesso OTP per concludere upload diversi, in momenti diversi. Dai nostri calcoli, dato l'alfabeto e la lunghezza dell'OTP, le probabilità di una collisione comincerebbero ad essere problematiche a partire da centinaia di migliaia di utenti positivi che effettuano l'upload delle chiavi contemporaneamente.
