### ISSUE TITLE
[BUG] it translations: some strings contain apostrophes not preceded by "\"

### ISSUE THREAD

**Issue by enricocid** [immuni-app/immuni-app-android#129]
**Describe the bug**

There are strings containing apostrophes not preceded by \ that could lead to build issues.

Example:

`<string name="notifications_update_os_description">Apri l’app per completare l’attivazione.</string>`

I'd propose a PR but I'm unable to test the changes. Double check strings :-)

**To Reproduce**

na

**Expected behaviour**

na

**Screenshots**

na

**Smartphone (please complete the following information):**

na

**Additional context**

na

**Comment by marcouberti** [comment]
@enricocid this character doesn't need to be escaped. ’ is different from '.
