### ISSUE TITLE
[BUG][Home] Superfluous line appears in the corner of Indicazioni per te tile

### ISSUE THREAD

**Issue by serenadg** [immuni-app/immuni-app-android#133]
Superfluous line appears in the corner of Indicazioni per te tile. There is a small artifact appearing in the corner.

**Screenshots**
![IMG_2829](https://user-images.githubusercontent.com/23152109/83395322-5fa4aa80-a3fa-11ea-835e-ca3f2b71d2e1.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy J5

**Additional context**
This issue may affect other suggestions screens

**Comment by marcouberti** [comment]
@serenadg which is the Android version?

**Comment by bfabio** [comment]
I can reproduce it on a Nexus 5 with Marshmallow (6.0.1) and Immuni v1.1.0.

**Comment by titaniabanfi** [comment]
closing because won't fix
