### ISSUE TITLE
[GENERAL] App exit confirmation

### ISSUE THREAD

**Issue by mlocati** [immuni-app/immuni-app-android#137]
# Issue content

When hitting the "back" hardware button, the app asks if we really want to quit the application.

AFAIK the app keeps running in background even if it's closed. So this message is a bit misleading: users may think that the app won't do its job if closed...

**Comment by mlocati** [comment]
If it's not clear, I'm referring to this confirmation:

![immagine](https://user-images.githubusercontent.com/928116/84018031-dbb16c00-a97f-11ea-9c73-2a29e0748492.png)

Is it necessary?

**Comment by robertodauria** [comment]
I had the exact same doubt the first time I saw that message, even if I knew tracing is supposed to stay active in the background.

I think something like "Sei sicuro di voler uscire? Il tracciamento contatti rimarrà attivo" would be much clearer.

**Comment by mlocati** [comment]
What about simply removing it?

**Comment by mlocati** [comment]
18 days without any feedback from BS? 🤔

**Comment by marcouberti** [comment]
@mlocati fixed

**Comment by mlocati** [comment]
Great, thanks!
