### ISSUE TITLE
[GENERAL] Potential security issues in the libraries this project is using

### ISSUE THREAD

**Issue by matteobaccan** [immuni-app/immuni-app-android#14]
# Issue content
I have forked the project and used a dependency security scanner to check if there are some security problems related to the library used by the project.

This is the result:

[Security scan](https://www.meterian.io/projects/?pid=22883259-3565-478e-b700-647442150129)

I suggest you to check all the dependencies of the project, because many of potential security problems may be solved with a minor update

all the best
matteo baccan

**Comment by Dbof** [comment]
I agree on the "update your dependecies" part in general. No offense, but have you read your own scan report? There is literally one issue with the Guava library that might lead to DOS attacks if "used on a server". This is hardly a "security problem" for a mobile app, is it?
