### ISSUE TITLE
[FEAT] official .APK relase

### ISSUE THREAD

**Issue by M9k** [immuni-app/immuni-app-android#140]
Some people use ROM without GApps (like LineageOS or MIUI china).
Please build an official .apk in the relase with the aab.

Thanks.

EDIT: Some people with custom roms have the framework but not the store, aab is hardy usable as a "relase", apk will still be a lot more usefull.

**Comment by edocod1** [comment]
I believe Immuni needs the new APIs that Google included in the latest GApps update. It probably wouldn't work.

**Comment by Talebian12** [comment]
> Some people use ROM without GApps (like LineageOS or MIUI china).
> Please build an official .apk in the relase with the aab.
> 
> Thanks.

Immuni needs the last update of Gooogle Play Services.

**Comment by dace74** [comment]
> Some people use ROM without GApps (like LineageOS or MIUI china).
> Please build an official .apk in the relase with the aab.
> 
> Thanks.
> 
> EDIT: Some people with custom roms have the framework but not the store, aab is hardy usable as a "relase", apk will still be a lot more usefull.

If you haven't installed Play Services app not work.Huawei or MIUI without google services not working

**Comment by nicosemp** [comment]
> Huawei or MIUI without google services not working

That's true for now, but as you can see from the [download page](https://www.immuni.italia.it/download.html) they are going to support the Huawei AppGallery too.

**Comment by dace74** [comment]
> > Huawei or MIUI without google services not working
> 
> That's true for now, but as you can see from the [download page](https://www.immuni.italia.it/download.html) they are going to support the Huawei AppGallery too.

Questo consentirà agli utenti di **alcuni** modelli di smartphone Huawei di usare Immuni.

New models with resctriction and not play services not working, of possibile for not new smartphone and tablet (2 years old)

**Comment by immuniteam** [comment]
Thanks @M9k for your issue. You can download Immuni from Google Play and use it correctly if your Android smartphone fulfils all three of the following requirements:

- Bluetooth Low Energy
- Android version 6 (Marshmallow, API 23) or above
- Google Play Services version 20.18.13 or above

Unfortunately, you won’t be able to use Immuni if your model of Android smartphone doesn’t feature Bluetooth Low Energy or doesn’t support the minimum Android and Google Play Services versions indicated above. Also with the latest version of google play services there should be no problems on most huwei branded devices. We are closing this issue for now, let us know if you need futher details.
