### ISSUE TITLE
[GENERAL] Date of the last exposure

### ISSUE THREAD

**Issue by mirkocazzolla** [immuni-app/immuni-app-android#142]
In the StateCloseDialogFragment it’s clear that the user will be informed about the date of the last possible contact with a positive covid patient.
The user could easily make a list of the people he met and, in this way, if he didn't take a public transport, they can be certainly identified. Then this information could unwittingly reveal the identity of the infectived patient.
Don't you think it is better to omit this data? In any case, the aim is to push the exposed citizen to get tested, regardless of the date of the infection.

**Comment by dace74** [comment]
controversy doesn't make sense.
if a person has few social contacts, he will still know who can be the positive who infected him, otherwise he has no way of tracing the contact.
without an exposure date it is impossible to calculate the incubation timing and the related quarantine days.
