### ISSUE TITLE
[GENERAL] "Caricamento dati" is poorly described

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-app-android#144]
The function intended for test result loading is called "Caricamento dati" in the Italian localisation, is nested in the settings menu (despite it's not a setting at all) and and is poorly described.

"Caricamento dati" is a very odd choice of words, as it is very generic (what data are we talking about?). Even the underlying page does not explain clearly what is the purpose, and its placement into the settings menu may lead the user to the false understanding that the function is somehow necessary to keep the app up-to-date or to make it work.

The intended use of this function should be well described in order to avoid confusion.

After a few hours since availability, we already have one user complaining about this within one of the reviews onGoogle Play Store.

It should not be assumed that the average user knows how the app works, nor that he/she will read the FAQs.

**Comment by immuniteam** [comment]
Thanks for the issue @lmasellis, actually we are working to improve this feature.
we will keep you updated.
