### ISSUE TITLE
[BUG] Exposure notifications not enabled if bluetooth is ON

### ISSUE THREAD

**Issue by matteosecli** [immuni-app/immuni-app-android#146]
**Describe the bug**

Cannot enable exposure notifications if bluetooth is on.

**To Reproduce**

1. Install Immuni from the [Play Store](https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni)
2. Ensure bluetooth is ON
3. Open the app and complete the initial steps
4. Press on "Allow"
5. You see the error message "Exposure notifications are not enabled"
6. Close the app
7. Turn bluetooth OFF
8. Open the app again and start over by completing the initial steps
9. Press on "Allow"
10. Exposure notifications are enabled

**Expected behaviour**

Exposure notifications are enabled when the bluetooth is on, or at least the user gets notified to turn it off.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Honor V10
- OS: Android 10
- Version: 10.0.0.146

**Additional context**

Possibly related: #145

-----

**Update:** it seems that steps 6. and 8. are not necessary; after you're stuck on the "Allow" screen, you can just turn off your bluetooth via the drop-down system menu and then press "Allow" again, it should work.

**Comment by grausof** [comment]
Seems like a common problem in the Huawei world!

**Comment by matguidi** [comment]
I confirm this bug on my Honor 10 View.

**Comment by DrSchottky** [comment]
Same on an LG G3 (Android 6, PS version 20.18.17)
I have no COVID-19 notifications settings in the device settings menu. 

- If I start the app with BT turned on it says I don't have exposure notifications enabled
- If I start the app with BT turned off it starts (at least on the UI) but, if I close and reopen it, it says that the service is off and I can't turn in beczause I don't have exposure notifications enabled

Same behavior on a Galaxy S3 (Lineage OS 14.1/Android7.1.2, PS 20.18.17)

**Comment by RoBYCoNTe** [comment]
I can confirm the same behavior on Huawei P smart. After seeing this post I’ve disabled Bluetooth and restarted the app. The configuration process was completed successfully, but after closing the app and reopening it I’ve received another warning about the stopped service.

**Comment by heyteacher** [comment]
> Same on an LG G3 (Android 6, PS version 20.18.17)
> I have no COVID-19 notifications settings in the device settings menu.
> 
> * If I start the app with BT turned on it says I don't have exposure notifications enabled
> * If I start the app with BT turned off it starts (at least on the UI) but, if I close and reopen it, it says that the service is off and I can't turn in because I don't have exposure notifications enabled
> 
> Same behavior on a Galaxy S3 (Lineage OS 14.1/Android7.1.2, PS 20.18.17)

Same behavior HUAWEI P10 Light (Android  8.0.0)

**Comment by lo97** [comment]
> > Same on an LG G3 (Android 6, PS version 20.18.17)
> > I have no COVID-19 notifications settings in the device settings menu.
> > 
> > * If I start the app with BT turned on it says I don't have exposure notifications enabled
> > * If I start the app with BT turned off it starts (at least on the UI) but, if I close and reopen it, it says that the service is off and I can't turn in because I don't have exposure notifications enabled
> > 
> > Same behavior on a Galaxy S3 (Lineage OS 14.1/Android7.1.2, PS 20.18.17)
> 
> Same behavior HUAWEI P10 Light (Android 8.0.0)

Same on my P10 light

**Comment by DrSchottky** [comment]
I can confirm that, at least for me, the service ins't really working even if the UI says so (after starting app with BT disabled).
I dumped the BLE traffic with external hardware and I don't see any adv packet coming from those devices, while all's good with my Pixel 3A.

**Comment by fabioalbani** [comment]
Same for me on my Huawei p8 lite 2017. It seems that the play services version updated a few days ago doesn't contain the notification exposure api. Will the app gallery version work? When will be released?

**Comment by AlainCh2** [comment]
Same issue

V10 - Pie updated

**Comment by DrSchottky** [comment]
Ai possessori di Huawei che hanno provato l'app:
potreste provare a scaricare l'app [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=it) aprire la il menu "Device information" e postare uno screenshot, indicando anche se con l'app funzionava tutto o c'erano dei problemi (errori, mancanza NE nelle impostazioni Google, etc) ?

Una cosa del genere:

![83694434-52550f00-a5f8-11ea-8dee-0e4a5f7fb041](https://user-images.githubusercontent.com/6048264/83754159-cc72ab80-a66b-11ea-84d1-85741e3d34f0.jpg)

Grazie

**Comment by AlainCh2** [comment]
Here you go.  No problem whatsoever with  nRF Connect.

![2020-06-04 14 20 48](https://user-images.githubusercontent.com/41082160/83756093-d1852a00-a66e-11ea-92bb-ff7e50900bc7.jpg)

**Comment by DrSchottky** [comment]
@AlainCh2 Multiple adv not supported, yet another confirmation that's the issue (see #154 )

**Comment by fabioalbani** [comment]
Hello, I have a Huawei p8 lite 2017,  I don't see covid exposure settings
in Google setup, the play version is 20.15.13.

My screenshot is

Il gio 4 giu 2020, 14:33 DrSchottky <notifications@github.com> ha scritto:

**Comment by matteosecli** [comment]
Immuni keeps deactivating after a while (automatic power management turned off, etc.) and I have to turn bt off & activate again. Play Services 20.18.17 (120408-311416286).

Here's the BLE info:

![Screenshot_20200604_144405_no nordicsemi android mcp](https://user-images.githubusercontent.com/4618521/83758652-af8da680-a672-11ea-9c5d-91d016de1c89.jpg)

Exposure Notifications:

![Screenshot_20200604_144552_com google android gms](https://user-images.githubusercontent.com/4618521/83758655-b0263d00-a672-11ea-834d-6ca05aaff140.jpg)

**Comment by heyteacher** [comment]
starting from v1.0.2, app is available again in Google Play for my Huawei P10 Light and seems to work fine 👌

**Comment by heyteacher** [comment]
> starting from v1.0.2, app is available again in Google Play for my Huawei P10 Light and seems to work fine

and "COVID-19 explosure notifications" appears magically in Google application
![IMG_20200608_113723](https://user-images.githubusercontent.com/51722388/84016022-fcc48d80-a97c-11ea-9b66-2fc89b66d42a.jpg)
