### ISSUE TITLE
L'app sembra non avviarsi in background

### ISSUE THREAD

**Issue by totarello91** [immuni-app/immuni-app-android#147]
Ho disattivato l'ottimizzazione della batteria per l'app e ho consentito l'avvio in background all'accensione del telefono (consiglio di mettere una guida a riguardo nell'app). Nonostante ciò sembrerebbe che l'app non si avvii in background all'accensione del telefono finché non la apro manualmente. Non compare infatti né tra le app in background né nei servizi in esecuzione

**Comment by mlocati** [comment]
*Credo* che siano i servizi della libreria di Google che tengono traccia dei contatti e che quindi devono essere sempre attivi

**Comment by marcouberti** [comment]
L'app utilizza WorkManager (che al suo interno utilizza il la permission RECEIVE_BOOT_COMPLETED) e quindi da linee guida Google dovrebbe riprendere l'esecuzione dei Work pianificati anche dopo un riavvio del sistema. 
Tuttavia e' un problema noto quello di alcuni produttori che non rispettano le specifiche di Android.
Nel frattempo Google, che e' a conoscenza di questo problema, sta lavorando per risolvere questo problema tramite Play Services.

**Comment by alex-train** [comment]
Preferirei avere una notifica fissa nella barra delle notifiche che mi dica se l'app è attiva o no. Questo faciliterebbe l'utente.

**Comment by andrea-nisti** [comment]
Non andrebbe implementata la gestione del ble tramite un foreground service? In questo modo si è sicuri che android non decide di chiuderne l'esecuzione in background. Inoltre sarebbe presente una notifica sulla barra ad indicare l'attività del servizio.

**Comment by marcouberti** [comment]
@andrea-nisti no non serve. La parte relativa al BLE non è in alcun modo gestita dall'app, ma dalla Exposure Notification API (Google Play Services). Questi ultimi non vengono mai killati dal sistema e sono sempre funzionanti.

Riguardo alla notifica in foreground è un punto valido, ma non necessario, quindi al momento non è in programma questa feature.
