### ISSUE TITLE
[GENERAL] Clarify to the average user why Location services must be active

### ISSUE THREAD

**Issue by bfabio** [immuni-app/immuni-app-android#149]
The app should clarify why the Location services are required using the simplest language possible.

[onboarding_exposure_message_extended says](https://github.com/immuni-app/immuni-app-android/blob/master/app/src/main/res/values/strings.xml#L239):

> For exposure notifications to work, your phone's location services must be active at the system level. Immuni does not have access to location services and therefore cannot track your position or movements

Non technical users read this as "We need X. We don't use X" which is confusing (and admittedly it's counterintuitive, but unfortunately it's how Android works).

I think we should add a FAQ item about it and try to reword that message.

**Comment by lorcalhost** [comment]
Looking at some 1 star reviews on the Google Play store we can see how there is a lot of confusion about the need of having location services active, sometimes even giving space to some conspiracy theories from some users.

**Comment by Talebian12** [comment]
> The app should clarify why the Location services are required using the simplest language possible.
> 
> [onboarding_exposure_message_extended says](https://github.com/immuni-app/immuni-app-android/blob/master/app/src/main/res/values/strings.xml#L239):
> 
> > For exposure notifications to work, your phone's location services must be active at the system level. Immuni does not have access to location services and therefore cannot track your position or movements
> 
> Non technical users read this as "We need X. We don't use X" which is confusing (and admittedly it's counterintuitive, but unfortunately it's how Android works).
> 
> I think we should add a FAQ item about it and try to reword that message.

https://source.android.com/devices/bluetooth/ble#ble-scanning
`Caution: BLE scanning needs location permissions as BLE scanning identifies objects that could be used for geolocation. Turning off Location services will turn off Bluetooth scanning.`

**Comment by nicosemp** [comment]
> https://source.android.com/devices/bluetooth/ble#ble-scanning
> `Caution: BLE scanning needs location permissions as BLE scanning identifies objects that could be used for geolocation. Turning off Location services will turn off Bluetooth scanning.`

"could be used"

However this app clearly doesn't use them for geolocation. So it can, and should, make it clear to the user that it's not doing it.

> Non technical users read this as "We need X. We don't use X" which is confusing (and admittedly it's counterintuitive, but unfortunately it's how Android works).

I completely agree with this.
This is what 90% of my friends said to me:
"Hey you said it doesn't use GPS! Why is it asking for location services then??"
The average user doesn't know that GPS is a technology which falls under the same Location Services, but requires a separate permission to be used by an app.
