### ISSUE TITLE
[BUG] \ rendered in messages

### ISSUE THREAD

**Issue by lorcalhost** [immuni-app/immuni-app-android#150]
**`\` is rendered in messages**

`\` are generally rendered where they should't
e.g. 

> The use of Immuni is strictly personal. If you **haven`\`'t** done so already, set up a PIN on your device to protect it and prevent others from accessing your data and apps, including Immuni.

incorrectly renders with `\` which is not needed.

**To Reproduce**

1. Download the app on a device with English set as main language
2. Setup

**Expected behaviour**

No `\` should be rendered

e.g.  

> The use of Immuni is strictly personal. If you **haven't** done so already, set up a PIN on your device to protect it and prevent others from accessing your data and apps, including Immuni.

**Smartphone (please complete the following information):**

- Device: OnePlus 7
- OS: Android 10

**Additional context**

Bug can be easily fixed by modifying the values in `app/src/main/res/values/strings.xml`

**Comment by marcouberti** [comment]
Thank you. This has been already fixed [here](https://github.com/immuni-app/immuni-app-android/commit/583d2f890bbd2e077008d4078fc4ffe91a7f800d).
