### ISSUE TITLE
[GENERAL] change the 'servizio attivo' status to 'servizio bluetooth attivo'

### ISSUE THREAD

**Issue by NikPiermafrost** [immuni-app/immuni-app-android#151]
Many people are nit getting what 'servizio attivo' means even in regions where the app has yet to be tested, using it to prove the app is useless

**Comment by marcouberti** [comment]
Hi @NikPiermafrost, the service to be active needs several things, not only bluetooth:
- bluetooth
- device localisation on (required by the Android Bluetooth API, we don't collect location)
- exposure SDK ON

**Comment by NikPiermafrost** [comment]
Thanks for the clarification and fast response, then can i suggest to change it to something like "servizi controllo esposizione attivi"? I know it's a minor change but it will help people understand what it does more and create less debate

**Comment by marcouberti** [comment]
Thanks for the suggestion.
