### ISSUE TITLE
[BUG] non si può consentire l'uso del bluetooth se questo è già attivo

### ISSUE THREAD

**Issue by paolobenve** [immuni-app/immuni-app-android#152]
Ho appena installato l'app sul mio cell android Honor 9 Lite (LLD-L31, Android 9.1.0.158), sul quale **tengo sempre il bluetooth attivo**.

Quando l'app mi ha chiesto il consenso all'uso del bluetooth ho avuto un problema: il pulsante _consenti_ non so se non era attivo o non portava avanti. In pratica non c'era maniera di cominciare a usare l'app.

Visto che mi diceva che aveva bisogno di una modalità bluetooth "leggera", ho provato a **disattivare il bluetooth** a livello di sistema, e dopo averlo fatto il bottone _consenti_ ha fatto quello che doveva fare e sono potuto andare avanti.

**Comment by nicolasap-dm** [comment]
Vedi anche #146

**Comment by immuniopensource** [comment]
Duplicate of #146
