### ISSUE TITLE
consumo gps

### ISSUE THREAD

**Issue by proidit** [immuni-app/immuni-app-android#153]
e' possibile evitare l'uso del gps per non causare consumo eccessivo della batteria? 
appena ho disattivato il gps l'applicazione ha avvisato che senza di esso non puo' funzionare.... disinstallata immediagamente per non rimanere senza batteria a meta' giornata.

**Comment by marcouberti** [comment]
Purtroppo no. Le Notifiche di Esposizione di Google richiedono la localizzazione abilitata per permettere il funzionamento del Bluetooth Low Energy.

**Comment by proidit** [comment]
utilizzare il bluetooth classico (che non  richiede gps) invece del BLE?

**Comment by Gianpaolo91** [comment]
GPS attivo non significa che questo venga utilizzato, infatti non compare l'icona della localizzazione nella barra delle notifiche proprio perchè non è utilizzata. Inoltre il BLE consuma meno del Bluetooth classico.

**Comment by proidit** [comment]
ok

**Comment by Agomik** [comment]
Ho notato oggi la stessa cosa. Capisco perfettamente il problema tecnico, ma il fatto che Immuni mi obblighi a tenere la geolocalizzazione attiva anche se non è necessaria (ovvero a dare un permesso del che non voglio dare) penso vanifichi molti sforzi di design e comunicazione. Nel mio caso è un motivo sufficiente per non utilizzare l'app.

**Comment by Talebian12** [comment]
> Ho notato oggi la stessa cosa. Capisco perfettamente il problema tecnico, ma il fatto che Immuni mi obblighi a tenere la geolocalizzazione attiva anche se non è necessaria (ovvero a dare un permesso del che non voglio dare) penso vanifichi molti sforzi di design e comunicazione. Nel mio caso è un motivo sufficiente per non utilizzare l'app.

https://source.android.com/devices/bluetooth/ble#ble-scanning

**Comment by Agomik** [comment]
> > Ho notato oggi la stessa cosa. Capisco perfettamente il problema tecnico, ma il fatto che Immuni mi obblighi a tenere la geolocalizzazione attiva anche se non è necessaria (ovvero a dare un permesso del che non voglio dare) penso vanifichi molti sforzi di design e comunicazione. Nel mio caso è un motivo sufficiente per non utilizzare l'app.
> 
> https://source.android.com/devices/bluetooth/ble#ble-scanning

Se ti riferisci a:

> Caution: BLE scanning needs location permissions as BLE scanning identifies objects that could be used for geolocation. Turning off Location services will turn off Bluetooth scanning.

Purtroppo motiva ma non risolve il problema.

**Comment by bfabio** [comment]
@proidit You can set the location service to battery saving mode (also called low accuracy mode) on certain Android versions and ROMs. That'll turn off the GPS and keep BT active.

**Comment by Tomb01** [comment]
Tralasciando i problemi di carattere diciamo "tecnico" e per addetti ai lavori, ricordando comunque che avere la localizzazione attiva (se pur non utilizzata a Immuni) la rende disponibile ad altre app presenti sullo smartphone e alla stessa Google (si sono consapevole che questo è l'ultimo dei problemi, perchè Google come Facebook e altri hanno già una valanga di nostri dati in loro possesso)
Il problema maggiore ritengo sia la credibilità dell'app in se. Dato che il sistema funziona bene se siamo in tanti ad utilizzarlo è importante che l'app abbia una certa "credibilità" appunto.
Immaginate di spiegare ad una persona che non è molto dentro la tecnologia che deve mantenere il GPS accesso solo per autorizzare un altro sistema (ossia il BLE) a lavorare, probabilmente vi risponde che l'app ci sta tracciando e che i poteri forti ci controllano. In tutto questo l'app viene scaricata da meno persone e il sistema funziona male.
Spero di non essere andato off-topic e di aver fatto passare il concetto.

**Comment by proidit** [comment]
Sarebbe opportuno almeno spiegare all'utente alla richiesta di autorizzazione della geolocalizzazione in termini comprensibili ai non addetti ai lavori quello che avete spiegato perchè diversamente l'utente collega automaticamente la geolocalizzazione con il consumo eccessivo di batteria e disinstalla immediatamente l'applicazione come avevo fatto anche io inizialmente.

**Comment by bfabio** [comment]
@proidit I opened an issue tracking that (#149)

**Comment by adrfantini** [comment]
Heya all,
just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.

Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.

**Comment by proidit** [comment]
> Heya all,
> just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> 
> Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.

provando ad installare lanversione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)

**Comment by Talebian12** [comment]
> Heya all,
> just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> 
> Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.

Da quello che ho letto nella documentazione usa il sistema di Exposure Notification europea DESIRE, le cui specifiche descritte [qui](https://github.com/3rd-ways-for-EU-exposure-notification/project-DESIRE/blob/master/DESIRE-specification-EN-v1_0.pdf). Questo sistema utilizza anche lui Bluetooth Low Energy (BLE), il quale secondo la documentazione di Android (Documentazione Bluetooth LE Scanning [qui](https://source.android.com/devices/bluetooth/ble#location-scanning)) richiede obbligatoriamente l'attivazione della localizzazione per l'utilizzo dello scanning BLE. Comunque Immuni anche se richiede l'attivazione della localizzazione non implica l'uso del modulo GPS, essendo che per l'utilizzo è richiesto il permesso [ACCESS_FINE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION), ma nel Manifest è richiesto solo il permesso [BLUETOOTH](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH).

**Comment by adrfantini** [comment]
> > Heya all,
> > just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> > Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.
> 
> provando ad installare la versione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
> ![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)

Viene richiesto il permesso, ma non che la geolocalizzazione sia di fatto attiva. Da quello che mi pare di capire l'app continua a funzionare se il GPS viene disattivato, contrariamente ad Immuni.

**Comment by Talebian12** [comment]
> > > Heya all,
> > > just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> > > Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.
> > 
> > provando ad installare la versione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
> > ![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)
> 
> Viene richiesto il permesso, ma non che la geolocalizzazione sia di fatto attiva. Da quello che mi pare di capire l'app continua a funzionare se il GPS viene disattivato, contrariamente ad Immuni.

L'app non continua a funzionare, vedi la mia risposta sopra.

**Comment by jumpjack** [comment]
> Purtroppo no. Le Notifiche di Esposizione di Google richiedono la localizzazione abilitata per permettere il funzionamento del Bluetooth Low Energy.

e allora google cos'ha aggiornato a fare le sue librerie, se poi bluetooth e GPS sono ancora insensatamente vincolati tra loro?!?

**Comment by adrfantini** [comment]
> > > > Heya all,
> > > > just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> > > > Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.
> > > 
> > > 
> > > provando ad installare la versione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
> > > ![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)
> > 
> > 
> > Viene richiesto il permesso, ma non che la geolocalizzazione sia di fatto attiva. Da quello che mi pare di capire l'app continua a funzionare se il GPS viene disattivato, contrariamente ad Immuni.
> 
> L'app non continua a funzionare, vedi la mia risposta sopra.

Se disattivo la geolocalizzazione in Immuni, l'app mi comunica che non sta funzionando. La stessa cosa non avviene con l'app Francese, che anzi rende molto chiaro che, per farla continuare a funzionare, non devo disattivare il Bluetooth. Una volta data l'autorizzazione iniziale, non menzione né pare necessitare più della localizzazione.

![photo_2020-06-03_20-33-44](https://user-images.githubusercontent.com/12826141/83675603-9ab10480-a5d9-11ea-8a83-76d5c604a02b.jpg)

**Comment by proidit** [comment]
> > > > > Heya all,
> > > > > just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> > > > > Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.
> > > > 
> > > > 
> > > > provando ad installare la versione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
> > > > ![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)
> > > 
> > > 
> > > Viene richiesto il permesso, ma non che la geolocalizzazione sia di fatto attiva. Da quello che mi pare di capire l'app continua a funzionare se il GPS viene disattivato, contrariamente ad Immuni.
> > 
> > 
> > L'app non continua a funzionare, vedi la mia risposta sopra.
> 
> Se disattivo la geolocalizzazione in Immuni, l'app mi comunica che non sta funzionando. La stessa cosa non avviene con l'app francese, che anzi rende molto chiaro che, per farla continuare a funzionare, non devo disattivare il Bluetooth. Una volta data l'autorizzazione iniziale, non menziona né pare necessitare più della localizzazione.
> 
> ![photo_2020-06-03_20-33-44](https://user-images.githubusercontent.com/12826141/83675603-9ab10480-a5d9-11ea-8a83-76d5c604a02b.jpg)

che sia un bug dell'applicazione francese che non fa il check?

**Comment by sroddy** [comment]
Sì, è probabile

> > > > > > Heya all,
> > > > > > just to add some info to this issue, I know that a similar [official French app](https://gitlab.inria.fr/stopcovid19/accueil/) does not require the localisation services to be active in order to work. I do not know if this is because they fall back to normal BT for when the localisation is inactive, or due to some other technical differences with Immuni.
> > > > > > Whatever it is, taking a look at its code might be a good starting point for finding a possible workaround for this issue.
> > > > > 
> > > > > 
> > > > > provando ad installare la versione francese sembrerebbe che anche quest'ultima utilizzi la stessa metodologia di quella italiana infatti richiede ugualmente autorizzazione alla geolocalizzazione quindi l'uso del BLE e non bluetooth classico
> > > > > ![IMG_20200603_113003](https://user-images.githubusercontent.com/4655081/83620616-d7efa500-a58d-11ea-8b83-82e3d153e819.jpg)
> > > > 
> > > > 
> > > > Viene richiesto il permesso, ma non che la geolocalizzazione sia di fatto attiva. Da quello che mi pare di capire l'app continua a funzionare se il GPS viene disattivato, contrariamente ad Immuni.
> > > 
> > > 
> > > L'app non continua a funzionare, vedi la mia risposta sopra.
> > 
> > 
> > Se disattivo la geolocalizzazione in Immuni, l'app mi comunica che non sta funzionando. La stessa cosa non avviene con l'app francese, che anzi rende molto chiaro che, per farla continuare a funzionare, non devo disattivare il Bluetooth. Una volta data l'autorizzazione iniziale, non menziona né pare necessitare più della localizzazione.
> > ![photo_2020-06-03_20-33-44](https://user-images.githubusercontent.com/12826141/83675603-9ab10480-a5d9-11ea-8a83-76d5c604a02b.jpg)
> 
> che sia un bug dell'applicazione francese che non fa il check?

Sì è probabile, perché lo scanning in quel caso continua a funzionare senza dare eccezioni, ma semplicemente ritorna sempre un array vuoto di risultati. Quindi senza un check esplicito è molto facile non rendersene conto in fase di sviluppo

**Comment by sroddy** [comment]
@proidit posso sapere se nelle impostazioni del tuo device è possibile, a livello di gestione dei servizi di localizzazione, attivarli/disattivarli la modalità FINE (GPS) / COARSE (WIFI/CELLULAR).

Se questo fosse possibile, dovresti poter ridurre in modo significativo il consumo di batteria impostando questa seconda modalità.

**Comment by proidit** [comment]
> @proidit posso sapere se nelle impostazioni del tuo device è possibile, a livello di gestione dei servizi di localizzazione, attivarli/disattivarli la modalità FINE (GPS) / COARSE (WIFI/CELLULAR).
> 
> Se questo fosse possibile, dovresti poter ridurre in modo significativo il consumo di batteria impostando questa seconda modalità.
> 
> La mia schermata ad esempio è fatta così:
> ![screenshot-1591215817262](https://user-images.githubusercontent.com/729934/83685424-f1720a80-a5e8-11ea-8423-a26f5d8d9c2c.jpg)

il problema non e' ridurre i consumi a livello di configurazione del cell che sarebbe un attivita a carico dell'utente piu o meno esperto e che investirebbe tutte le applicazioni installate ma ottenere le stesse funzionalita senza l'attivazione della localizzazione che anche se non completa a livello psicologico dissuade l'utente ad installare l'app.
peraltro la si promuove garantendo la privacy ma la richiesta di dare tali permessi farebbe pensare che avviene un tracciamento degli spostamenti anche se poi nella realta non avverrebbe.
purtroppo sembra non ci sia altra soluzione con il BLE perche tutto si appoggia alle API google che sembrerebbero imporre tali autorizzazioni

**Comment by Agomik** [comment]
È tecnicamente possibile far interagire BLE e Bluetooth normale? In tal caso si potrebbe switchare tra l'una e l'altra tecnologia dipendentemente dalla geolocalizzazione senza che l'utente se ne accorga.

**Comment by Talebian12** [comment]
> > @proidit posso sapere se nelle impostazioni del tuo device è possibile, a livello di gestione dei servizi di localizzazione, attivarli/disattivarli la modalità FINE (GPS) / COARSE (WIFI/CELLULAR).
> 
> > 
> 
> > Se questo fosse possibile, dovresti poter ridurre in modo significativo il consumo di batteria impostando questa seconda modalità.
> 
> > 
> 
> > La mia schermata ad esempio è fatta così:
> 
> > ![screenshot-1591215817262](https://user-images.githubusercontent.com/729934/83685424-f1720a80-a5e8-11ea-8423-a26f5d8d9c2c.jpg)
> 
> 
> 
> il problema non e' ridurre i consumi a livello di configurazione del cell che sarebbe un attivita a carico dell'utente piu o meno esperto e che investirebbe tutte le applicazioni installate ma ottenere le stesse funzionalita senza l'attivazione della localizzazione che anche se non completa a livello psicologico dissuade l'utente ad installare l'app.
> 
> peraltro la si promuove garantendo la privacy ma la richiesta di dare tali permessi farebbe pensare che avviene un tracciamento degli spostamenti anche se poi nella realta non avverrebbe.
> 
> purtroppo sembra non ci sia altra soluzione con il BLE perche tutto si appoggia alle API google che sembrerebbero imporre tali autorizzazioni

Non sono le api di Google, è una imposizione dell’os. Per separare il funzionamento servirebbe una nuova release di android che non può raggiungere tutti i device, soprattutto i telefoni economici e mid-level.

**Comment by adrfantini** [comment]
Purtroppo penso che l'unico approccio possibile sia quello di informare il più possibile l'utente a riguardo, vedi #149.

**Comment by immuniteam** [comment]
Thanks @proidit for the issue, due to a limitation of the operating system, on Android smartphones the geolocalisation service needs to be enabled to allow the system to detect Bluetooth signals and record the random codes of nearby users.
Immuni uses Bluetooth Low Energy, a technology designed to be particularly energy-efficient.
For more information please take a look at the official Immuni website, here's the link:
https://www.immuni.italia.it/faq.html
We hope everything is clear, for the moment we close the issue.
