### ISSUE TITLE
[BUG] Notifiche di esposizione non attivate

### ISSUE THREAD

**Issue by Polm1** [immuni-app/immuni-app-android#154]
**Describe the bug**
Alla schermata di abilitazione delle notifiche viene restituito un feedback di "notifica di esposizione non attivate" nonostante siano attive nelle impostazioni. Per risolvere temporaneamente è necessario un riavvio del dispositivo ma si ripresenta quando si esce e rientra nell'applicazione.

**To Reproduce**
1. Installare l'applicazione
2. Proseguire nel wizard fino alla schermata di abilitazione notifiche di esposizione
3. Click su "consentì"

**Expected behaviour**
Feedback di successo

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Honor view 10 lite
- OS: Android 10
- Version 1.0.0

**Additional context**
Regione di provenienza: Sardegna

**Comment by riffraff** [comment]
vedo lo stesso problema su un Huawei P10-Lite , EMUI 8.0 / Android 8.0. 
Forse la versione android è obsoleta, ma se così fosse mi aspetterei l'app non fosse installabile

**Comment by lo97** [comment]
> vedo lo stesso problema su un Huawei P10-Lite , EMUI 8.0 / Android 8.0.
> Forse la versione android è obsoleta, ma se così fosse mi aspetterei l'app non fosse installabile

Non è obsoleta, è un bug di molti huawei

**Comment by ArteInfoRM** [comment]
Stesso problema con Honor 7X pure riavviando. 
EMUI 9.1.0 - Android 9

**Comment by ArteInfoRM** [comment]
> vedo lo stesso problema su un Huawei P10-Lite , EMUI 8.0 / Android 8.0.
> Forse la versione android è obsoleta, ma se così fosse mi aspetterei l'app non fosse installabile

Se l'APP deve coprire il 60% dei dispositivi sarebbe assurdo

**Comment by Talebian12** [comment]
Sembra generalmente un problema diffuso su Huawei, ho provato diversi device tra cui Galaxy Note 8, Galaxy S5, Nexus 5, Galaxy S7, LG G6, LG Q6. Tutti andavano, poi ho provato Huawei P10 e non va, credo sia un problema strettamente legato alla EMUI e non all'app e Google.

**Comment by ArteInfoRM** [comment]
> credo sia un problema strettamente legato alla EMUI e non all'app e Google.
Probabile si veridica su Honor e Huawei, ho provato su Xiaomi MI 9 e il problema non si verifica.
Se fosse così devono risolvere e sarebbe scandaloso in quanto Huawei è al secondo posto dietro a Samsung (31%) come mercato e detiene il 26% dello stesso.

**Comment by ArteInfoRM** [comment]
Stesso problema su Oukitel U7 Max con Android 7.0

**Comment by ArteInfoRM** [comment]
Il problema sembra legato alla messa al bando di Trump e quindi sembra che Honor e Huawei non possano accedere a Google Mobile Services e devono attendere una versione che usi Huawei Mobile Services.

**Comment by voldenuit** [comment]
Stesso problema su P10 Lite e P Smart 2017. Riguarda comunque specifici modelli Huawei e Honor, visto che ad esempio sui vecchi Honor 8 e Huawei P9 con Android 7.0 ed EMUI 5.0 il problema _non_ si presenta e l'app funziona regolarmente.

**Comment by Humanitech** [comment]
Confermo: Honor View 10 stesso problema.

**Comment by andreascian** [comment]
Sto facendo anch'io dei test con P20 Lite. Play Services mi sembra aggiornato, e infatti vedo la voce delle notifiche di esposizione tra i settings.

```
adb shell dumpsys package com.google.android.gms | grep versionName | head -n 1
    versionName=20.18.17 (100408-311416286)
```

Ma ho l'app da lo stesso il messaggio di errore.

Via adb, la parte significativa direi che e' questa:

```
06-02 22:26:26.818 21180 21731 I ExposureNotification: Utils#isSupported enabled=true, isDeviceSupported=true, isBluetoothSupported=false [CONTEXT service_id=236 ]
06-02 22:26:26.831  1993  1993 W System.err: com.google.android.gms.common.api.ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39501), resolution=null, message=null}
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.2.1:4)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@17.2.1:2)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.2.1:18)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:204)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.2.1:210)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:108)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:75)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.zaf.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:2)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(com.google.android.gms:play-services-basement@@17.2.1:6)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.2.1:25)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(com.google.android.gms:play-services-basement@@17.2.1:11)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.2.1:49)
06-02 22:26:26.831  1993  1993 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:112)
06-02 22:26:26.831  1993  1993 W System.err: 	at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.2.1:8)
06-02 22:26:26.831  1993  1993 W System.err: 	at android.os.Looper.loop(Looper.java:216)
06-02 22:26:26.831  1993  1993 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by andreascian** [comment]
FYI: io ho risolto con quanto descritto in #146 ovver:

* disattivo BT
* apro Immuni e procedo col Wizard
* confermo l'abilitazione delle notifiche di esposizione

questa volta funziona correttamente

Peccato che sia un'operazione da fare di continuo, visto che l'app mi continua a dire, dopo poco, che il servizio e' disattivato e, per riattivarlo, e' necessaria la trafila di cui sopra (ottimizzazioni batteria gia' disabilitate)

**Comment by DrSchottky** [comment]
@andreascian Attenzione che potrebbe essere un falso positivo.
Se fosse così su tutti i huawei credo sia una issue di estrema importanza e da risolvere al più presto.

**Comment by dg14** [comment]
Stesso problema su Huawei P smart 2019 (Android 10).

**Comment by Gioxxy** [comment]
Same issue on Oneplus 7T Pro OxygenOS

**Comment by marcouberti** [comment]
Ciao a tutti e grazie per le preziose informazioni. Stiamo cercando di risolvere il problema con questi device.
Posso chiedere a chi di voi ha un device Huawei/Honor di allegare un bugreport dopo aver provato ad attivare le exposure API? (adb bugreport)
Grazie!

**Comment by dg14** [comment]
Ciao Marco,
seguendo le indicazioni che ho visto ieri ed oggi, non esiste una voce in
Impostazioni / Google che parla di exposure / notifiche di esposizione /
covid.

puoi fare uno screen di dove dovrebbe essere questa attivazione? grazie


Il giorno mer 3 giu 2020 alle ore 11:24 Marco Uberti <
notifications@github.com> ha scritto:

**Comment by DrSchottky** [comment]
@dg14 
![1](https://user-images.githubusercontent.com/6048264/83622187-ed65ce80-a58f-11ea-9921-fb326b956ed0.jpg)
![2](https://user-images.githubusercontent.com/6048264/83622205-f191ec00-a58f-11ea-8b75-f8141468af1a.jpg)

**Comment by dg14** [comment]
Ciao, non compare quella voce.

ora aggiornando immuni e rieseguendo la procedura di configurazione, esce:
Google Play Service non è ancora pronto. 
Error code: 39501.

E' un problema di vendor o di google play?

**Comment by DrSchottky** [comment]
Penso di PS, su tutti e tre i telefoni problematici in test (S3, G3, Moto G) ho lo stesso errore dopo l'aggiornamento.
Il check però viene bypassato se si richiede l'abilitazione a BT spento

**Comment by dg14** [comment]
> Il check però viene bypassato se si richiede l'abilitazione a BT spento (stesso problema di prima).
una volta fatto quel giro (disabilitazione BT, che poi è fuorviante se pensi al BLE), stranamente immuni lo riabilita. il problema probabilmente è quando il phone va in standby.

provato ora. disattivato BT, immuni, attiva ok. 
controllo BT ed è tornato su da solo.
esco immuni, lo riapro servizio OK.
spengo schermo. riapro immuni e servizio non attivo.

**Comment by DrSchottky** [comment]
@dg14 in realtà non abilita nulla, c'è una incongruenza tra lo stato riportato dall'UI e quello effettivo.

**Comment by Gioxxy** [comment]
![image](https://user-images.githubusercontent.com/27723588/83624804-63b80000-a593-11ea-80c2-cf87e226d440.png)

Nelle impostazioni vedo la pagina delle notifiche di esposizione.

Bug report:
[bugreport-OnePlus7TPro-QKQ1.190716.003-2020-06-03-12-26-18.zip](https://github.com/immuni-app/immuni-app-android/files/4722674/bugreport-OnePlus7TPro-QKQ1.190716.003-2020-06-03-12-26-18.zip)

**Comment by marcouberti** [comment]
Grazie @Gioxxy.

Stiamo cercando di capire dove sta il problema. Probabilmente non si attiva mai e come avete gia' detto potrebbe essere un falso positivo l'attivazione iniziale.

**Comment by ArteInfoRM** [comment]
> potrebbe essere un falso positivo l'attivazione iniziale.

Sui miei telefoni Oukitel e Honor aziendali non si attiva nemmeno la prima volta, il problema si verifica subito alla prima attivazione.

**Comment by White-Rabbit89** [comment]
Ciao,
allego qui i log del mio dispositivo. In sostanza noto più comportamenti strani:

- Andando in Impostazioni -> Google vedo la voce "Notifiche di esposizione al COVID-19" solo al riavvio del dispositivo, mentre dopo un pò di utilizzo tale voce scompare (ma è possibile ricercarla tramite la funzione ricerca)
- Non riesco più a installare l'app, in quanto vedo il messaggio qui sotto:
![Screenshot_20200603_144447_com android vending](https://user-images.githubusercontent.com/19634544/83638059-dda6b400-a5a8-11ea-9aa3-b57510b152b0.jpg)

Il mio dispositivo è un **Huawei Honor 10**, con **Android 9.1.0**, e versione dei **Play Services 20.18.17 (100408-311416286)**.

Trovate il bugreport qui:
[bugreport-COL-L29-HUAWEICOL-L29-2020-06-03-14-34-34.zip](https://github.com/immuni-app/immuni-app-android/files/4723353/bugreport-COL-L29-HUAWEICOL-L29-2020-06-03-14-34-34.zip)

**Comment by marcouberti** [comment]
Grazie @White-Rabbit89, si al momento abbiamo escluso i dispositivi Huawei/Honor in attesa di risolvere il problema. Inutile lasciarla scaricare se poi non funziona.

**Comment by DrSchottky** [comment]
@marcouberti possono esservi utili altri log?

**Comment by marcouberti** [comment]
@DrSchottky si certo, se ne avete ci farebbero molto comodo grazie.

**Comment by andreascian** [comment]
> @DrSchottky si certo, se ne avete ci farebbero molto comodo grazie.

visto che adesso da Play Store non e' piu' accessibile per Huaway/Honor, ci puoi dare un link da dove scaricare l'APK o possiamo anche usare un nostro build per replicare il problema e inviarti log?

**Comment by dg14** [comment]
Marco,

ti allego una parte di logcat da quando ho aperto la app, fino a quando ho
provato a riattivare il servizio immuni.
ti è utile?


Il giorno mer 3 giu 2020 alle ore 18:51 Marco Uberti <
notifications@github.com> ha scritto:

**Comment by marcouberti** [comment]
Grazie @dg14, che device e'?

**Comment by DrSchottky** [comment]
@marcouberti 
[bugreport-NJH47F-2020-06-03-19-20-35.zip](https://github.com/immuni-app/immuni-app-android/files/4725035/bugreport-NJH47F-2020-06-03-19-20-35.zip)

TL;DR: Galaxy S3 Neo Lineage 14.1 (Android 7.1.2). Aspettato parecchie ore per avere la voce Notifiche esposizione nei settaggi Google. Installato App, partita (solo lato UI, non emetteva in realtà), killata e riavviata: errore 39501. Sparite le Notifiche esposizione nei settaggi Google.
Riavviato nullo è cambiato, generato bugreport.

Volendo escludere il fatto che fosse legato al fatto che usassi una custom ROM ho provato a replicare l'esperimento su un LG G3 stock: stesso identico comportamento.

**Comment by dg14** [comment]
Huawei p smart 2019

Il mer 3 giu 2020, 19:05 Marco Uberti <notifications@github.com> ha scritto:

**Comment by andreascian** [comment]
> @andreascian bella domanda =) ci pensiamo su e vi faccio sapere.

ho provato il build col master attuale e ho un error code `39507`.
Il tag `Immuni-1.0.0build1000563` invece da l'errore di attivazione, ma non e' presente il, probabile, falso positivo che fa' sembrare l'app funzionare se viene disabilitato il BT.
Ma forse e' un problema del mio build, ammetto di sapere cosa aspettarmi di diverso tra l'app ufficiale e quella buildata dai sorgenti

**Comment by andreascian** [comment]
da googlata ignorante in giro, ho trovato questo: https://github.com/google/exposure-notifications-android/issues/3

quindi dai sorgenti direi nisba :cry: ma attendo conferma (anche se preferirei una smentita :wink: ) da @marcouberti 
(a parte gli scherzi, e' comprensibile che sia necessario che l'app sia firmata per accedere alle API, altrimenti si avrebbe il casino piu' totale di implementazioni fasulle. Pero' sarebbe altresi' un peccato che non si possa fare del testing con un proprio build)

**Comment by marcouberti** [comment]
@andreascian confermo che non tutti possono usare le Exposure Notification API, ma solo le app governative autorizzate. Queste app vengono riconosciute dai Play Services tramite la loro signature/package name. 

Se voi provate ad attivarle dalle vostre build locali riceverete un errore ApiException con codice di errore: 39507 che significa UNHAUTORIZED.

Se ricevete invece un errore 39501 significa che c'e' qualche problema di compatibilita' hardware.

**Comment by dg14** [comment]
> Se ricevete invece un errore 39501 significa che c'e' qualche problema di compatibilita' hardware.

significa che il vendor (non credo, dato che i BLE sono già supportati nativamente) deve rilasciare una patch? o solo che i servizi google non contemplano quel tipo di configurazione hardware, per cui verrà rilasciata una versione di google play che risolve il problema?

**Comment by marcouberti** [comment]
Probabilmente una nuova versione di Google Play Services risolvera' il problema.

**Comment by pierangelodalben** [comment]
Perché avete rimosso l'app per tutti i dispositivi huawei? Mentre sul device huawei p20 lite ho riscontrato i comportamenti già segnalati da altri, su huawei mate 20 con android 10 sembra funzionare l'attivazione sia partendo ha bt spento che acceso.

**Comment by voldenuit** [comment]
> Grazie @White-Rabbit89, si al momento abbiamo escluso i dispositivi Huawei/Honor in attesa di risolvere il problema. Inutile lasciarla scaricare se poi non funziona.

Ma a me, come ho scritto sopra, sembra funzionare, sia su Huawei P9 che su Honor 8: il servizio si attiva e rimane tale anche uscendo e rientrando nell’app. Può essere ugualmente una falsa attivazione? Per cui, mi chiedevo: sarebbe possibile in qualche modo verificare l’effettivo scambio degli id casuali con altri dispositivi? Non dico visualizzarli (anche se, visto che sono anonimi e cambiano dopo un po’, forse non sarebbe un problema), sarebbe sufficiente anche un semplice contatore per verificarne l’incremento.

**Comment by pierangelodalben** [comment]
> Probabilmente una nuova versione di Google Play Services risolvera' il problema.

Speriamo perché altrimenti se funzionasse solo con alcuni device android escludendone molti altri anche abbastanza recenti (io uso huawei mate 20 aggiornato ad android 10 e un huawei p20 lite con android 9) ne ridurrebbe l'efficacia

**Comment by dg14** [comment]
Io avrei escluso Apple piuttosto che Huawei

Il mer 3 giu 2020, 23:50 Pierangelo Dal Ben <notifications@github.com> ha
scritto:

**Comment by pierangelodalben** [comment]
> > Grazie @White-Rabbit89, si al momento abbiamo escluso i dispositivi Huawei/Honor in attesa di risolvere il problema. Inutile lasciarla scaricare se poi non funziona.
> 
> Ma a me, come ho scritto sopra, sembra funzionare, sia su Huawei P9 che su Honor 8: il servizio si attiva e rimane tale anche uscendo e rientrando nell’app. Può essere ugualmente una falsa attivazione? Per cui, mi chiedevo: sarebbe possibile in qualche modo verificare l’effettivo scambio degli id casuali con altri dispositivi? Non dico visualizzarli (anche se, visto che sono anonimi e cambiano dopo un po’, forse non sarebbe un problema), sarebbe sufficiente anche un semplice contatore per verificarne l’incremento.

Anche secondo me sarebbe più utile fornire un'opzione di diagnostica piuttosto che rimuovere completamente l'app per tutti i huawei. Capisco che i mondo android sia più eterogeneo di quello apple ma se viene pubblicata una app senza un test su una vasta gamma di devices android non può che risultare in una sfiducia di una applicazione che è stata rilasciata troppo in fretta.

**Comment by andreascian** [comment]
a quanto sembra il problema non e' tanto relativo a Immuni ma bensi' a Google Play Services, che nella versione finora rilasciata non funziona correttamente su (alcuni?) Huawei.
Credo che sarebbe utile per tutti se quando riportate il funzionamento o meno dell'app sul vostro dispositivo, oltre a modello e versione Android, riportaste anche la versione di Google Play Services installata.
Io mi sono registrato per la sua versione beta, magari questa si comporta diversamente (attendo fiducioso che @marcouberti , o chi per lui, ci dia un apk da installare, anche via adb, per proseguire coi test)

**Comment by pierangelodalben** [comment]
> a quanto sembra il problema non e' tanto relativo a Immuni ma bensi' a Google Play Services, che nella versione finora rilasciata non funziona correttamente su (alcuni?) Huawei.
> Credo che sarebbe utile per tutti se quando riportate il funzionamento o meno dell'app sul vostro dispositivo, oltre a modello e versione Android, riportaste anche la versione di Google Play Services installata.
> Io mi sono registrato per la sua versione beta, magari questa si comporta diversamente (attendo fiducioso che @marcouberti , o chi per lui, ci dia un apk da installare, anche via adb, per proseguire coi test)

Goople play services versione 20.18.17 sia su huawei mate 20 che su huawei p20 lite

**Comment by Lorenzo-R** [comment]
> si al momento abbiamo escluso i dispositivi Huawei/Honor in attesa di risolvere il problema. Inutile lasciarla scaricare se poi non funziona.

Non so se può aiutare ma sul mio Huawei P20 l'app **sembra** funzionare correttamente.
Ho scaricato l'app dal Play Store e ho attivato il servizio la sera del 1 giugno. Da quel momento non ho mai riscontrato nessun problema evidente, ogni volta che apro l'app **il servizio risulta attivo**.
Non so poi se veramente il servizio sta funzionando: ho scaricato un debugger BLE (BlueSee BLE Debugger: https://apps.apple.com/it/app/bluesee-ble-debugger/id1336679524?mt=12) per verificare che gli advertisements del Exposure Notification Service fossero effettivamente trasmessi, ma onestamente, non avendo nessuna esperienza riguardo a BLE (o Bluetooth in generale), non so esattamente cosa dovrei cercare o aspettarmi.

Il mio dispositivo è uno Huawei P20 (modello EML-L09) con EMUI 9.1.0 e Google Play Services versione 20.18.17

Se avete bisogno di qualsiasi altra informazione non esitate a chiedere.

**Comment by DrSchottky** [comment]
Ai possessori di Huawei che hanno provato l'app:
potreste provare a scaricare l'app [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=it) aprire la il menu "Device information" e postare uno screenshot, indicando anche se con l'app funzionava tutto o c'erano dei problemi (errori, mancanza NE nelle impostazioni Google, etc) ?

Una cosa del genere:

![83694434-52550f00-a5f8-11ea-8dee-0e4a5f7fb041](https://user-images.githubusercontent.com/6048264/83754159-cc72ab80-a66b-11ea-84d1-85741e3d34f0.jpg)

Grazie

**Comment by dg14** [comment]
![Screenshot_20200604_141139_no nordicsemi android mcp](https://user-images.githubusercontent.com/3777310/83755208-7bfc4d80-a66d-11ea-8e60-4dc257d2752e.jpg)

**Comment by pierangelodalben** [comment]
hauwei mate 20 con android 10 e google play services 20.18.17, google notifiche covid attive, immuni viene attivato sia partendo con BT spento che BT acceso

![mate20](https://user-images.githubusercontent.com/1194805/83755393-ced60500-a66d-11ea-9fc5-44946459244f.jpg)

**Comment by pierangelodalben** [comment]
hauwei p20 lite con android 9 e google play services 20.18.17, google notifiche covid attive, immuni viene attivato SOLO partendo con BT spento (con BT acceso rimmane bloccato sulla schermata di attivazione)

![p20lite](https://user-images.githubusercontent.com/1194805/83755499-f4fba500-a66d-11ea-9328-301f9069d8fc.jpg)

**Comment by DrSchottky** [comment]
Grazie, questo pare confermare anche i test fatti coi miei device (se avete ulteriori sample mandate pure): le NE non funzionano correttamente se manca il supporto al multiple advertisement (che non significa che il sistema non sia in grado di emettere pacchetti adv) a livello di ROM.
@marcouberti ha senso? Avete avuto esiti simili dai vostri test interni?

**Comment by mirkoscotti** [comment]
Identico problema con Honor 9 Lite, EMUI 9.1.0.158

**Comment by voldenuit** [comment]
@DrSchottky Ecco i miei risultati. Su P9 e Honor 8 Immuni si attiva senza problemi e rimane attiva anche rientrando successivamente nell'app. Goole Play Services aggiornati all'ultima versione: 20.18.17

Huawei P9 (EVA-L19, versione dual SIM):

![p9](https://user-images.githubusercontent.com/2168343/83760225-ef558d80-a674-11ea-8d17-f98ed98765ad.png)

Honor 8:

![honor8](https://user-images.githubusercontent.com/2168343/83760303-0bf1c580-a675-11ea-8880-c9638f3d2a8b.png)

Effettivamente, in entrambi i casi è presente il supporto al multiple advertisement.

**Comment by Charles-II** [comment]
Se vi può servire io potrei fare dei test su un Huawei Mate 10 Pro con Android 9 e Google Paly Services versione 20.18.17 (100408-311416286)

**Comment by Gioxxy** [comment]
Nel mio caso, su Oneplus 7T Pro pur avendo Multiple advertisement supported da errore sempre.
Google Play Services v20.18.17 (120400-311416286)

![image](https://user-images.githubusercontent.com/27723588/83762026-5aa05f00-a677-11ea-9119-6dcc8f3b37a1.png)

**Comment by DrSchottky** [comment]
@Gioxxy errore 39507 o 39501?

**Comment by Gioxxy** [comment]
> @Gioxxy errore 39507 o 39501?

39507

**Comment by DrSchottky** [comment]
> 
> 
> > @Gioxxy errore 39507 o 39501?
> 
> 39507

Io per ora quelli che non supportavano il multiple adv li ho visti in 39501. L'app l'hai installata da playstore, giusto?
Quello probabilmente è un altro bug

**Comment by andreascian** [comment]
questo il mio P20 Lite, errore 39501

![Screenshot_20200604_154034_no nordicsemi android mcp](https://user-images.githubusercontent.com/5579628/83764315-1498ca80-a67a-11ea-819d-312d9c536515.jpg)

**Comment by Gioxxy** [comment]
> > > @Gioxxy errore 39507 o 39501?
> > 
> > 
> > 39507
> 
> Io per ora quelli che non supportavano il multiple adv li ho visti in 39501. L'app l'hai installata da playstore, giusto?
> Quello probabilmente è un altro bug

Sì dal Play Store

**Comment by stefanosalvador** [comment]
Moto G 2014 Android 10 Lineage OS + OpenGApps
Errore 39501
Configurazione EN prima presente poi sparita

![Screenshot_20200604-150637_nRF_Connect](https://user-images.githubusercontent.com/41092/83765137-1adb7680-a67b-11ea-9469-e77973ca9d64.png)

Samsung Tab S4 Android 9 del produttore
Errore 39501
Configurazione EN prima presente poi sparita

![Screenshot_20200604-153020_nRF Connect](https://user-images.githubusercontent.com/41092/83765580-a5bc7100-a67b-11ea-812a-c083c1746dec.jpg)

**Comment by stefanosalvador** [comment]
> Samsung Tab S4 Android 9 del produttore
> Errore 39501
> Configurazione EN prima presente poi sparita

Aggiornamento: il problema sembra sia causato dal fatto che usavo un account secondario sul dispositivo, usando quello principale funziona tutto senza problemi, pare proprio un problema del multiple adv. Speriamo in un aggiornamento da parte di Google.

**Comment by diegomaninetti** [comment]
Huawei P10 Lite, Google play services 20.18.17.
App non funzionante, voce "Notifiche di esposizione covid-19" non presente nel play services.

**Comment by diegomaninetti** [comment]
Aggiungo screenshot app diagnostica
![image](https://user-images.githubusercontent.com/2275525/83790218-1ffaee80-a698-11ea-8f72-d78345860115.png)

**Comment by DrSchottky** [comment]
Qualcosa non torna:
ho preso due Huawei, un P9 Lite ed un Y7 2018, stessa versione dei Play Services (20.18.17).
Il secondo supporta il multi adv e l'app funziona correttamente.
Il primo non lo supporta, e nelle impostazioni Google non compariva nulla riguardo alle EN. O meglio, si alternava tra non mostrare nulla e mostrare questo:
![Screenshot_20200604-182822](https://user-images.githubusercontent.com/6048264/83785520-baa3ff00-a691-11ea-93d3-60414f9bcd96.png)

Che se cliccato apre una schermata bianca. Naturalmente l'app non andava.

Dal Play Store sono entrato nel programma beta dei PS e ho aggiornato a 20.21.15, dopodiché le opzioni Google sono diventate così:
![Screenshot_20200604-182216](https://user-images.githubusercontent.com/6048264/83785680-f8a12300-a691-11ea-869f-ce97e7715199.png)

E l'app ha cominciato a funzionare!
Esco dal programma beta, faccio il downgrade a 20.18.17 e si ripresenta la situazione iniziale.
Rientro in beta e riaggiorno, ma non c'è verso di far ricomparire le impostazioni EN

**Comment by dg14** [comment]
Aderito in beta, installato Google Play Services (beta),
Controllo Exposure settings su Impostazioni / Google: non presente.
avviato immuni, richiesta di attivazione servizio, servizio attivo ok, bluetooth su.
Vado a controllare su  Impostazioni / Google: presente.

metto in sospensione, falcio via eventuali app che girano in foreground. 
riapro immuni.
servizio attivo.

problema risolto?

**Comment by deboooo** [comment]
Huawei P10 Lite con Google Play Services in beta ho risolto il problema e ora l'app resta attiva anche se viene chiusa.
Continuo però a NON vedere EN in Impostazioni/Google (la trovo però se effettuo una ricerca nelle impostazioni)

**Comment by diegomaninetti** [comment]
P10 Lite, play services versione beta.
Non posso testare il funzionamento dell'app in quanto non più accessibile dal play store.
Esiste un apk signed da usare come test?

**Comment by DrSchottky** [comment]
> 
> 
> P10 Lite, play services versione beta.
> Non posso testare il funzionamento dell'app in quanto non più accessibile dal play store.
> Esiste un apk signed da usare come test?

Per testare si trova su APKPure, io ho fatto così sui Huawei

**Comment by diegomaninetti** [comment]
> > P10 Lite, play services versione beta.
> > Non posso testare il funzionamento dell'app in quanto non più accessibile dal play store.
> > Esiste un apk signed da usare come test?
> 
> Per testare si trova su APKPure, io ho fatto così sui Huawei

Grazie.
P10 Lite, con play services beta. Sembra funzionare (alla riapertura risulta attiva).

**Comment by stefanosalvador** [comment]
> Moto G 2014 Android 10 Lineage OS + OpenGApps
> Errore 39501
> Configurazione EN prima presente poi sparita

Con Google Play Services beta funziona anche con questo device.

**Comment by matguidi** [comment]
![Screenshot_20200604_214339](https://user-images.githubusercontent.com/59918868/83803237-7ffb9000-a6ac-11ea-9b20-cb178465efc8.jpg)

Finché l'app è stata disponibile, avevo il problema descritto da altri: si attivava con BT spento, una volta attivato il BT l'app cessava di funzionare.

**Comment by Jany-M** [comment]
Come detto anche qui, nessun problema (apparente) con **Huawei P20 Pro**, l'app funziona ed è sempre rimasta attiva. 
Adesso il PlayStore dice che non è più compatible... come altri, non voglio usare l'app Gallery. 

![Screenshot_20200605_021400](https://user-images.githubusercontent.com/4365842/83822822-72590100-a6d2-11ea-94fc-b6da1e82ffb2.jpg)

![Screenshot_20200605_020627](https://user-images.githubusercontent.com/4365842/83822902-b0562500-a6d2-11ea-86eb-199d8c0d27c8.jpg)

**Comment by Polm1** [comment]
@marcouberti non so se possa essere utile però mi sono dimenticato di specificare che ho sperimentato il bug dalla Sardegna.

**Comment by marcouberti** [comment]
@Polm1 grazie, non credo faccia differenza, comunque indagheremo anche su questo.
@Jany-M grazie per l'utile informazione.

**Comment by rickeight** [comment]
Trovo davvero assurdo che l'app funzioni dal giorno 1 sul mio Huawei P30 Pro e sia stata rimossa dal Play Store.
Ma avete letto che non funziona anche su altri brand? Perchè gli altri brand la vedono?

**Comment by quaqo** [comment]
Come segnalato in #179, sul mio Honor 8, Immuni ha sempre funzionato e l'Exposure Notification Framework è sempre stato disponibile (ma non posso aggiornare l'app). Da poche ore è comparso l'Exposure Notification anche su un P10 Lite, che precedentemente non lo supportava (i GPS non sono stati aggiornati, sembra un'attivazione "lato server"?).

Non posso però installare Immuni, perché non disponibile sul Play Store (#179).

**Comment by Gioxxy** [comment]
Dopo l'aggiornamento 1.0.2 riesco ad attivare l'app e non ho più l'errore 39507 su Oneplus 7T Pro

**Comment by dg14** [comment]
Per ottenere l'aggiornamento 1.0.2, dovrei buildarmelo a manella? Huawei p
smart 2019?

Il dom 7 giu 2020, 00:01 Gionatan Cernusco <notifications@github.com> ha
scritto:

**Comment by marcouberti** [comment]
@dg14 non ce ne è bisogno, anche perchè non funzionerebbe, l'app per funzionare deve essere quella ufficiale firmata da noi. Ancora un pò di pazienza e l'app ritornerà disponibile a tutti.

**Comment by lrob** [comment]
Ho un Huawei p20 lite, ho  installato l'app il primo giorno che era disponibile e non funzionava, proprio come descritto in questi thread.  L'ho tenuta installata ed oggi funziona correttamente e nella lista dei servizi è presente "notifiche di esposizione al covid-19".

**Comment by matguidi** [comment]
Confermo che anche sul mio Honor 10 View (Numero di build 9.1.0.364, Versione EMUI 9.1.0) Immuni ora funziona correttamente.

**Comment by immuniteam** [comment]
Thanks @Polm1 for your issue. Our team worked together with Google to resolve this issue related to some Huawei devices. With the latest version of google play services there should be no problems on most Huawei branded devices. We are continuing to work on making Immuni available for most devices. We are closing this issue for now, let us know if you need futher details.
