### ISSUE TITLE
[BUG] notifiche di esposizione non attivate

### ISSUE THREAD

**Issue by Polm1** [immuni-app/immuni-app-android#156]
**Describe the bug**
Alla schermata di abilitazione delle notifiche viene restituito un feedback di "notifica di esposizione non attivate" nonostante siano attive nelle impostazioni. Per risolvere temporaneamente è necessario un riavvio del dispositivo ma si ripresenta quando si esce e rientra nell'applicazione.

**To Reproduce**
1. Installare l'applicazione
2. Proseguire nel wizard fino alla schermata di abilitazione notifiche di esposizione
3. Click su "consentì"

**Expected behaviour**
Feedback di successo

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Honor view 10 lite
- OS: Android 10
- Version 1.0.0

**Additional context**
In alternativa, con l'app già installata, uscire e rientrare, cliccare su "riattiva immuni" nell'avviso "Servizio non attivo"

**Comment by immuniopensource** [comment]
Hi @Polm1, is this a duplicate of #154?

**Comment by Polm1** [comment]
> Hi @Polm1, is this a duplicate of #154?

Yep, sorry for duplicate: I was writing on mobile device and didn't really know what have been happened...anyway didn't intend to create a duplicate.

Thanks
