### ISSUE TITLE
Allow selecting foreign country as residence

### ISSUE THREAD

**Issue by riffraff** [immuni-app/immuni-app-android#158]
**Is your feature request related to a problem? Please describe it.**

As an Italian who resides abroad and plans on traveling to Italy, I would like to be able to choose a foreign country as residence rather than an italian province (or the generic "EE" for "estero").
This might also be useful for foreigners traveling to Italy, if they decided to install the app.

**Describe the solution you'd like**
Add an "I live abroad" option to the region selection page

**Describe alternatives you've considered**
Being registered with AIRE I can always select the province of my original town, but that would be misleading for statistical purposes.

**Comment by lo97** [comment]
I think it's more about where you are (for choosing the rigt ASL) than what your residence is
