### ISSUE TITLE
[FEAT] Modalità EDIFICIO con sensore GIROSCOPICO

### ISSUE THREAD

**Issue by mrprunen** [immuni-app/immuni-app-android#164]
Uno dei luoghi più a rischio per i contagi sono gli edifici dove la gente lavora, studia o fruisce di servizi. 

Si potrebbe pensare ad implementare l'uso dei sensori giroscopici presenti in qualsiasi smartphone in commercio per tracciare un percorso grossolano degli spostamenti eseguiti all'interno di un edificio.

Il contagio avviene anche per contatto di superfici e il tracciamento bluetooth non compre questa evenienza. 

Non è un calcolo sicuramente semplice poiché in ballo ci sono gli stili di camminata e la posizione del telefono al momento della rilevazione del dato.

Se c'è qualche esperto di giroscopi possiamo confrontarci per l'analisi e poi definire i building blocks

**Comment by ballad2** [comment]
Se ho capito il senso questo  presuppone l' uso di dati dal GPS.

**Comment by mrprunen** [comment]
Il GPS serve solo per sapere in quale punto dell'edificio è entrata la persona.
Entrata nell'edificio il GPS non rileva più la posizione.
A quel punto interviene il tracciamento dei dati del sensore giroscopico che permette di ricostruire il percorso fatto all'interno.
Sarà così possibile ricostruire in quale sezione e con quali persone è potenzialmente andata in contatto la persona.
I luoghi chiusi sono quelli a più alto rischio contagio.
Il bluetooth permette una rilevazione di prossimità ma non di percorso.
Se la persona contagiata ha toccato maniglie ed oggetti tra una fase di sanificazione e l'altra altre persone potrebbero contagiarsi.

**Comment by ballad2** [comment]
Quindi  avevo capito bene, questo presuppone che immuni sappia che a una certa data e ora il soggetto e' entrato in un certo edificio, smentendo quindi l' affermazione che immuni _non_ utilizza dati di geo localizzazione. Se si aggiunge questo al fatto che la versione compilata non funziona e comunque non e' quella di cui si fa il download dal sito si apre a ogni sorta di dubbio sulle garanzie di privacy.

**Comment by mrprunen** [comment]
Qui si sta parlando di possibili funzionalità.
I dati potrebbero essere residenti solo sul telefono della persona ed essere usati solo nel momento in cui ci sia un reale bisogno.
Se chi è infetto da il consenso alla ricostruzione l'app potrebbe generare un report da usare nel modo opportuno.
Le altre persone che hanno usato l'app immuni e sono passate in quei luoghi nel momento del passaggio ricevono l'alert e confrontano i propri spostamenti con gli spostamenti dell'altro utente.
I dati inoltre potrebbero essere anonimizzati per garantire la privacy.

A mio avviso il tracciamento gps gestito in rispetto della privacy è fondamentale.
L'aggiunta del tracciamento con giroscopio può aggiungere dettaglio nei luoghi più a rischio.

**Comment by enricocid** [comment]
> Il GPS serve solo per sapere in quale punto dell'edificio è entrata la persona.
> Entrata nell'edificio il GPS non rileva più la posizione.
> A quel punto interviene il tracciamento dei dati del sensore giroscopico che permette di ricostruire il percorso fatto all'interno.
> Sarà così possibile ricostruire in quale sezione e con quali persone è potenzialmente andata in contatto la persona.
> I luoghi chiusi sono quelli a più alto rischio contagio.
> Il bluetooth permette una rilevazione di prossimità ma non di percorso.
> Se la persona contagiata ha toccato maniglie ed oggetti tra una fase di sanificazione e l'altra altre persone potrebbero contagiarsi.

Se una persona è contagiata e ha una importante carica virale se ne deve stare a casa sotto controllo medico e non andare in giro a spargere il virus.
E per fare questi calcoli poi non ci vorrebbero dei punti di riferimento? Ad es. le specifiche seppur grossolane degli interni? Chiedo. Sono le aziende e chi gestisce a dover gestire gli spazi comuni negli edifici e nelle aziende e garantire condizioni di sicurezza.

**Comment by mrprunen** [comment]
E' ovvio che chi è positivo sta in quarantena.
Il sistema di tracciamento serve per ricostruire a ritroso i contatti che un positivo ha avuto per dare la possibilità a chi è stato in contatto di verificare le sue condizioni ed eventualmente isolarsi a sua volta.
Se io oggi scopro di essere positivo ma ieri sono stato a lavoro devo essere in grado di capire con chi sono stato in contatto.
 
Per quanto riguarda i dubbi sul GPS, io sto parlando di usare il giroscopio e non il gps.
Il gps serve per l'esterno. Negli interni non c'è modo di capire il percorso di una persona con il GPS. Il giroscopio rileva i "G" a cui è sottoposto il telefono. E' un sistema inerziale.

**Comment by powext** [comment]
Google non permette l'utilizzo del GPS assieme alle Exposure Notifications, quindi inutile discuterne.

**Comment by immuniteam** [comment]
Immuni was born to alert the users who have had a risky exposure with potential people who tested positive for covid-19 ensuring maximum privacy and anonymity of the data. Tracing people, routes etc. it is not the purpose of this app and it would also go against any principle of privacy.
