### ISSUE TITLE
[CONTENT DESIGN] Rivedere label e copy in generale sul caricamento dati

### ISSUE THREAD

**Issue by silviaminenti** [immuni-app/immuni-app-android#167]
#108 - copy e content design main features
CARICAMENTO DATI - Non è immediato capire dove si inseriesce il proprio stato: negativo/positivo, navigando si arriva attraverso impostazioni> caricamento dati in cui troviamo il funnel per la verifica, è poco chiaro sia nell'architettura di navigazione e labeling che nella scrittura delle FAQ, meriterebbe portare in home il processo e descriverlo in maniera più semplice, ad esempio aggiungere una card in home con: "carimento propri dati" ( oppure "stato di salute", rivedere copy più esplicito) in cui accedere alla schermata di verifica con operatore sanitario, inoltre mettere infotips che rimanda alle faq per descrivere le modalità. 
![IMG_0734](https://user-images.githubusercontent.com/3907939/83628454-c65fca80-a598-11ea-8059-2ab823d7a735.JPG)

**Comment by bfabio** [comment]
@silviaminenti 

Correlato a #144.
Chiarimento: la schermata è per comunicare _solamente_ la positività.

**Comment by immuniopensource** [comment]
Duplicate of #144
