### ISSUE TITLE
[GENERAL] Missing localizations: SL (Slovenian), LLD (Ladin)

### ISSUE THREAD

**Issue by abaumg** [immuni-app/immuni-app-android#169]
# Issue content
Apart from French (in the Aosta Valley) and German (in South Tyrol), also Slovene (in Trieste, Gorizia and Udine) and Ladin (in South Tyrol and Trentino) are co-official languages in Italy.

Currently, only the French and German localizations are included. The Slovene and Ladin localizations are missing.

**Comment by immuniopensource** [comment]
Hi @abaumg and thanks for this issue. As this topic is already present in the general `documentation` repo I am closing this one to continue the discussion over there. Thanks for your understanding!
