### ISSUE TITLE
[GENERAL] Make Region and Province names localizable

### ISSUE THREAD

**Issue by abaumg** [immuni-app/immuni-app-android#170]
Apart from Italian, there exists various minority languages with co-official status: French, German, Slovene, Ladin. Some regions and provinces have official names in one or more of these co-official languages, e.g. Trentino-Alto Adige (IT) = Trentino-Südtirol (DE) = Trentin-Südtirol (LLD). Currently, the names of regions and provinces are hardcoded. Please enable them for localization.

**Comment by immuniopensource** [comment]
Hi @abaumg and thanks for this issue. As this topic is already present in the general `documentation` repo I am closing this one to continue the discussion over there. Thanks for your understanding!
