### ISSUE TITLE
[FEAT] Permanent notification and "enable/disable" button

### ISSUE THREAD

**Issue by jumpjack** [immuni-app/immuni-app-android#172]
Android apps can show a permanent notification of being running, so there is no need to open the app to check if it is running or if it has messages.
Clicking the notification should also enable/disable the app, and GPS/bluetooth as required.

GPS+bluetooth drain a lot of battery, so we need to quickly disable everything once we are at home.

**Comment by lo97** [comment]
Bluetooth LE uses very little energy. GPS is not used, so this comment is all wrong

**Comment by VaiTon** [comment]
> 
> 
> Bluetooth LE uses very little energy. GPS is not used, so this comment is all wrong

Despite not requiring GPS and BLE consuming "very little energy", there are still reasons for this to be implemented:
1. Someone may want to quickly disable the app when at home (BLE still consumes battery).
2. Someone may want to check the app status (active or not) without opening the app itself.

If the feature is implemented as proposed, and a setting is added to disable it, I see it as a good feature someone may like.

**Comment by carlidel** [comment]
An On/Off switch would be a terrible design decision for how this whole contact tracing thing is conceived. Same thing for a permanent notification banner.

What we are aiming to is a "set it and forget it" system that only notifies you when something goes wrong (application wise #175 or covid-19 wise).

If we have an immediate button, and we start to toggle the on/off switch arbitrarily, it's inevitable to mess up at some point and just forget to turn it back on when needed.

**Comment by DrSchottky** [comment]
> It's declared to be an "open " and "privacy-safe" app... but I can't know anything about what it installs and what it saves.

You literally have the source code in front of your eyes

**Comment by carlidel** [comment]
> It says it does not use GPS but it requires GPS but it does not use it but it stops if I stop GPS.

Most Android variants groups the whole geolocalization sensors and frameworks (including BLV) under the vague and wrong term "GPS".

The BLV system is included in the Low Battery and Low quality geolocalzation tools group, and therefore, when the new API requests the usage of BLV, the whole oldish android system displays the whole "GPS" category as "ON", even though only the BLV circuit is on.

**Comment by immuniteam** [comment]
Thanks, @jumpjack for the issue, Immuni is based on Bluetooth Low Energy technology and does not use any type of geolocation, including GPS data. 
You shouldn't notice a difference in battery life. Immuni uses Bluetooth Low Energy, a technology designed to be particularly energy-efficient.
Furthermore, having a button to activate and deactivate this service could be a wrong choice that goes against the main purpose of the app.
Let us know if you need further details!
