### ISSUE TITLE
Huawei indiscriminately pulled out from Google Play Store

### ISSUE THREAD

**Issue by quaqo** [immuni-app/immuni-app-android#179]
I am aware of the bug that prevents some Huawei devices to correctly have the Exposure Framework activated by Google Play Services.

I have a few in my family, and it's my understanding that -as per updated FAQ- a special version will be released through Huawei AppGallery.

My device, however, a **Honor 8 / Android 8.0.0 (EMUI 8)**, works very well and always had the Exposure Framework activated, even before Immuni was released.

Now I can't update the app anymore as it's not distributed on the Play Store: I have Immuni, but I'm stuck on version 1.0.

Also I wouldn't want to activate AppGallery on my phone just for Immuni. I'm fully committed to Google Play Store already, I don't want two stores and I think for a lot of non-tech-savvy people it would be a barrier to overcome if they don't find Immuni on the usual store.

You should consider having a list of working Huawei devices (Honor 8 seems to be referenced in othere issues, so it's not just mine), whilst the P10 Lite seems to be a common non-working one.

**Comment by Lorenzo-R** [comment]
I'm in the exact same situation @quaqo finds himself in: I downloaded the app from the Play Store on my Huawei P20 (and it seems to work properly, as I also stated in https://github.com/immuni-app/immuni-app-android/issues/154#issuecomment-638803348) but now I won't be able to update it.
Just like @quaqo I never used the AppGallery, and I'd rather keep using the Play Store exclusively.

**Comment by Jany-M** [comment]
Same here. Huawei P20 Pro, worked fine, no errors or issues.

Now the store says my phone is not compatible anymore. Why?

![Screenshot_20200605_020307_com android vending](https://user-images.githubusercontent.com/4365842/83822432-4be69600-a6d1-11ea-99df-0af100171447.jpg)

![Screenshot_20200605_020627](https://user-images.githubusercontent.com/4365842/83822443-52750d80-a6d1-11ea-8966-c35798a82dba.jpg)

**Comment by andreascian** [comment]
it seems that Huawei device compatibility is a bit a PITA
I reported some problems too into #154 (P20 Lite) and I would like to partecipate to investigate further on this

I'm wondering if @marcouberti can help us in providing a safe way to access release (here on GitHub?) and allows at least power users to install those apk via ADB (or similar method).
This will help us in participating to the project

**Comment by ballad2** [comment]
APK can be easily generated and installed from github sources, the fact is that such APK does not communicate with google play services, so it is useless for testing purposes.

**Comment by marcouberti** [comment]
@ballad2 exactly, we cannot share a working signed APK, sorry.

**Comment by marcouberti** [comment]
@andreascian  could you share your devices info? In particular:

- device model
- android version
- google play services version
- nearby module version (adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep 'nearby_en')
- rooted

**Comment by andreascian** [comment]
```
bash# adb  shell getprop | grep ro.product
[ro.product.CustCVersion]: [C461]
[ro.product.board]: [ANE]
[ro.product.brand]: [HUAWEI]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [HWANE]
[ro.product.fingerprintName]: [HUAWEI-02ANE]
[ro.product.first_api_level]: [26]
[ro.product.force.opengl]: [true]
[ro.product.hardwareversion]: [HL2ANNEM]
[ro.product.imeisv]: [47]
[ro.product.locale]: [en-GB]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [US]
[ro.product.manufacturer]: [HUAWEI]
[ro.product.model]: [ANE-LX1]
[ro.product.name]: [ANE-LX1]
[ro.product.odm.brand]: [Huawei]
[ro.product.odm.device]: [Dallas]
[ro.product.odm.name]: [Dallas]
[ro.product.vendor.brand]: [hi6250]
[ro.product.vendor.device]: [hi6250]
[ro.product.vendor.manufacturer]: [HUAWEI]
[ro.product.vendor.model]: [hi6250]
[ro.product.vendor.name]: [hi6250]
```

```
bash# adb  shell getprop | grep ro.build
[ro.build.backtargetmode]: [V1.0]
[ro.build.characteristics]: [default]
[ro.build.date]: [Tue Mar  3 12:52:43 CST 2020]
[ro.build.date.utc]: [1583211163]
[ro.build.description]: [ANE-L21-user 9.1.0 HUAWEIANE-L21 311-LGRP2-OVS release-keys]
[ro.build.display.id]: [ANE-LX1 9.1.0.311(C461E6R1P6)]
[ro.build.fingerprint]: [HUAWEI/ANE-LX1/HWANE:9/HUAWEIANE-L21/9.1.0.311C461:user/release-keys]
[ro.build.hide]: [false]
[ro.build.hide.matchers]: [ANE;ane;kirin659;xxxxxxxxxx;MaliT830-MP2;9.1.0]
[ro.build.hide.replacements]: [ANE;ANE;unknown;unknown;unknown;8.0.0]
[ro.build.hide.settings]: [8;1.8 GHz;2.0GB;20.00 GB;32.00 GB;1280 x 720;6.0;3.0.8;4.1]
[ro.build.host]: [cn-central-1b-f4f23c1b41583201548538-3129709449-55sjj]
[ro.build.hw.version.security_patch]: [2020-03-01]
[ro.build.hw_emui_api_level]: [19]
[ro.build.id]: [HUAWEIANE-L21]
[ro.build.preload_use_oemkey]: [true]
[ro.build.product]: [ANE]
[ro.build.soundrecorder.imgtag]: [true]
[ro.build.system_root_image]: [true]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.update_version]: [V1_2]
[ro.build.user]: [test]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: [HUAWEI/ANE-LX1/HWANE:9/HUAWEIANE-L21/9.1.0.200C461:user/release-keys]
[ro.build.version.codename]: [REL]
[ro.build.version.emui]: [EmotionUI_9.1.0]
[ro.build.version.incremental]: [9.1.0.311C461]
[ro.build.version.min_supported_target_sdk]: [17]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [9]
[ro.build.version.sdk]: [28]
[ro.build.version.security_patch]: [2020-03-01]
```

```
bash# adb shell dumpsys package com.google.android.gms | grep versionName | head -n 1
    versionName=20.21.15 (100408-313409149)
```

```
bash# adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep 'nearby_en'
            com.google.android.gms.nearby_en [v202115000]
```

as stated in #154 I've entered Google Play Services beta on AFTER testing (with problems) Immuni. Unfortunately I've deleted Immuni (I was testing my own build prior discover that it was useless for this :cry: ).
For this reason I'm asking if there's a way to re-install official signed version now and test this latest beta of Play Services

@marcouberti please let me know if you need additional info

**Comment by rickeight** [comment]
My feedback here as well, no issues on my P30 Pro from day 1. The App is working.
HUAWEI P30 Pro: EMUI 10 / Android 10
Google Play Services: 20.18.17
Immuni App: 1.0.1

Why only Huawei devices were excluded from the Google Play Store?

**Comment by immuniteam** [comment]
thanks, @quaqo for reporting the issue, at the moment we have unlocked p30, p30 pro, p20 and p20 pro which have always worked.
we are working to solve the problem, looking forward to giving you more information in the next few days.

**Comment by fabioalbani** [comment]
Also p8 lite if updates the play store in dev mode should work.

**Comment by quaqo** [comment]
> thanks, @quaqo for reporting the issue, at the moment we have unlocked p30, p30 pro, p20 and p20 pro which have always worked.
> we are working to solve the problem, looking forward to giving you more information in the next few days.

Thanks for the feedback. Aynways, as reported both by me and by @voldenuit in issue #154, [here](https://github.com/immuni-app/immuni-app-android/issues/154#issuecomment-637707640_) and  [here](https://github.com/immuni-app/immuni-app-android/issues/154#issuecomment-638836699_) Honor 8 also always worked.

**Comment by voldenuit** [comment]
@quaqo Yes and Huawei P9 (very similar to Honor 8) works well too.

**Comment by quaqo** [comment]
> @quaqo Yes and Huawei P9 (very similar to Honor 8) works well too.

Correct, they're almost the same device.

**Comment by marcouberti** [comment]
@Jany-M @rickeight could you confirm the app is now accessible to your P20 PRO and P30 PRO device and fully working? Thanks

**Comment by Jany-M** [comment]
@marcouberti yep, app is back on the PlayStore (P20 Pro), app still works fine. Thank you!

**Comment by rickeight** [comment]
> @Jany-M @rickeight could you confirm the app is now accessible to your P20 PRO and P30 PRO device and fully working? Thanks

@marcouberti I confirm, for P30 Pro the App was available on the Play Store on Friday afternoon. Re-installed and fully working.

**Comment by marcouberti** [comment]
The app is now available again for all devices.
