### ISSUE TITLE
[FEAT] Builds should be reproducible

### ISSUE THREAD

**Issue by bfabio** [immuni-app/immuni-app-android#18]
Users should be able to build the app and reproduce the exact build published to the Play Store, in order to make sure the binary was generated by this repo's source code.

For inspiration, here's how Signal does it: https://github.com/signalapp/Signal-Android/blob/master/ReproducibleBuilds.md

**Comment by matteocontrini** [comment]
From the readme:

>Currently, we have a working open continuous integration for building the client. Here is the full specification. When it comes to reproducible builds, we will instead open an issue explaining what we have done so far and any missing steps.

**Comment by fph** [comment]
So where is the "issue explaining what we have done so far and any missing steps"? Could someone please share a link to it, if it exists?
