### ISSUE TITLE
[GENERAL] Tempo e codice generato

### ISSUE THREAD

**Issue by tailot** [immuni-app/immuni-app-android#184]
# Issue content
Buongiorno, per motivi di lavoro cambio spesso l'ora del telefono (anche via script): ho notato che questo fa variare il codice generato. È un comportamento voluto ?

Saluti
V

**Comment by marcouberti** [comment]
@tailot si e' normale questo comportamento, il codice viene rigenerato ogni volta che rientri in quella pagina.

**Comment by tailot** [comment]
Grazie!
