### ISSUE TITLE
[BUG] `Onboarding/Sperimentazione` copy is not the latest available and needs to be updated

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#189]
**Describe the bug**

`Onboarding/Sperimentazione` copy is not the latest available and needs to be updated.

> Sperimentazione in corso
> 
> Durante la fase di sperimentazione verrai avvisato di un contatto a rischio con una persona positiva al virus solo se quest’ultima è assistita da un’ASL delle seguenti regioni: Abruzzo, Liguria, Marche e Puglia.
> 

![Screenshot_20200605-160905_Immuni](https://user-images.githubusercontent.com/57350395/83885851-3318c780-a747-11ea-8de0-d2359f30bc9e.jpg)

**Comment by serenadg** [comment]
FV
