### ISSUE TITLE
[GENERAL] Which backend services are you calling / will you call?

### ISSUE THREAD

**Issue by satboy78** [immuni-app/immuni-app-android#19]
Could you please elaborate on the following sentence?

> At the current stage, the application points to backend services which are not publicly accessible and whose source code has not been released. Note that the application is designed to work without a backend, especially in the context of not having the Exposure Notification entitlements (see [Installation](#installation).

I think it would be really appreciated by everyone knowing what's the purpose of every call, in particular POST ones! what are you sending? to whom? ecc.

All the best.
Matteo

**Comment by matteocontrini** [comment]
There's [a whole repo](https://github.com/immuni-app/immuni-documentation) for that.

**Comment by satboy78** [comment]
ok, cool, so why not putting a link there to that repo (possibly with a anchor to the right section), instead of that issue link?

> Please see this issue for more information about this topic.

I think it would be better :)

**Comment by immuniopensource** [comment]
Thanks @satboy78 for your question. As @matteocontrini said there are information regarding this topic in the dedicated [documentation](https://github.com/immuni-app/immuni-documentation) repository. However, thanks for your suggestion, we will try to make it clearer. I am closing this issue for the moment, let me know if you need further help.
