### ISSUE TITLE
[BUG] "How it works" copy should be updated

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#190]
**Describe the bug**
Two strings need to be updated by removing the question mark.
Come funziona l'app? >> Come funziona l'app

![Screenshot_20200605-161900_Immuni](https://user-images.githubusercontent.com/57350395/83887333-96efc000-a748-11ea-919a-5bb7f2ed737e.jpg)
![Screenshot_20200605-161846_Immuni](https://user-images.githubusercontent.com/57350395/83887353-9a834700-a748-11ea-91a3-3c627d5b72fb.jpg)

**Comment by serenadg** [comment]
FV
