### ISSUE TITLE
[BUG] The text in the button "Disattiva il servizio" appears to be slightly off and not centered

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#191]
**Describe the bug**

The text in the button "Disattiva il servizio" seems to be slightly off and not centered, due to the extra padding between the icon and the string.
To adjust it, we could reduce the padding on the left of the icon to compensate for the padding between the icon and the string to improve the overall balance (similar to iOS).

![Screenshot_20200605-162714_Immuni](https://user-images.githubusercontent.com/57350395/83888112-b0ddd280-a749-11ea-880d-07b1e9bb3018.jpg)

**Comment by titaniabanfi** [comment]
closing because won't fix.
