### ISSUE TITLE
[BUG] Uppercase inconsistency in Suggestion screen

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#192]
**Describe the bug**

Ministero della salute > Ministero della Salute

![Screenshot_20200605-164521_Immuni](https://user-images.githubusercontent.com/57350395/83890526-2fd40a80-a74c-11ea-83a8-4aa898feff16.jpg)

**Comment by jean-louis** [comment]
This issue should be fixed by this PR https://github.com/immuni-app/immuni-app-android/pull/195

**Comment by titaniabanfi** [comment]
fix verified
