### ISSUE TITLE
[BUG] For a split second the button `Disattiva il servizio` disappears from the Home screen

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#194]
**To Reproduce**

1. On the Home screen tap on `Disattiva il servizio`
2. A screen opens up, tap `Disattiva il servizio` again
--> For a split second the button `Disattiva il servizio` disappears from the Home screen.

**Comment by marcouberti** [comment]
Fixed in #193

**Comment by serenadg** [comment]
FV
