### ISSUE TITLE
[FEAT] Advanced (or debugging) mode

### ISSUE THREAD

**Issue by voldenuit** [immuni-app/immuni-app-android#197]
I think it would be useful to add an advanced mode (or debugging mode) to be able to verify that the app works as intended.

I don't know, based on COVID-19 Exposure Notifications System and privacy guidelines, what you can expose and what you can't. However, for example it would be interesting just being able to check the total number of random ids exchanged with other phones.

**Comment by filippogasbarro** [comment]
Yes, it would be very useful, above all to see if the app it works correctly.
On iOS this thing already exists and can be viewed in the settings.
Thank you if you add it.

**Comment by Lorenzo-R** [comment]
While the implementation of this feature is certainly noncritical and low-priority at the moment, I also think it could be interesting  to consider its implementation in the future (if privacy and security requirements allow it). It could serve as an element of engagement with the app and a sort of assurance that the app is indeed active and functioning correctly.
The info displayed doesn't need to be extremely detailed: even a rough (and aggregated over several days if necessary) estimate of the number of RPIs exchanged would be interesting to have.

**Comment by robertodauria** [comment]
It would be nice to have some kind of confirmation that the app is working as expected, but I share @Lorenzo-R's concerns about privacy. If such a counter increased immediately, then it would be theoretically possible to know if people around you have installed Immuni on their phones (now I wonder if this is possible already by reading the app's logs?)

If the counter is only updated at the end of the day, that mitigates the problem but it doesn't really solve it - e.g. let's say I've been close to five people today for a substantial amount of time, then I check the counter after midnight and I notice it has not increased. I would be pretty confident those five people weren't using Immuni.

**Comment by Lorenzo-R** [comment]
As stated in [this issue](https://github.com/immuni-app/immuni-documentation/issues/63#issuecomment-632354570), the Exposure Notification Framework unfortunately does not provide any info about the number of RPIs exchanged, so implementing such a feature doesn't seem to be possible at the moment.
