### ISSUE TITLE
[GENERAL] "informativa privacy" and "termini di utilizzo"  do not work!

### ISSUE THREAD

**Issue by EddyDevProject** [immuni-app/immuni-app-android#20]
# Issue content
If I click on the two "links" a white page appears.

**Comment by powext** [comment]
The privacy policy and the terms of use are [fetched from the backend](https://github.com/immuni-app/immuni-app-android/blob/8a8199622c06228a326911b55041acdb25f002c8/app/src/main/java/it/ministerodellasalute/immuni/api/services/ConfigurationSettingsService.kt):
```
@JsonClass(generateAdapter = true)
data class ConfigurationSettings(
    @field:Json(name = "minimum_build_version") val minimumBuildVersion: Int,
    @field:Json(name = "faq_url") val faqUrl: Map<Language, String>,
    @field:Json(name = "tos_url") val termsOfServiceUrl: String,
    @field:Json(name = "pp_url") val privacyPolicyUrl: String,
    @field:Json(name = "exposure_configuration") val exposureConfiguration: ExposureConfiguration,
    @field:Json(name = "service_not_active_notification_period") val serviceNotActiveNotificationPeriod: Int, // FIXME use me!
    @field:Json(name = "onboarding_not_completed_notification_period") val onboardingNotCompletedNotificationPeriod: Int,
    @field:Json(name = "required_update_notification_period") val requiredUpdateNotificationPeriod: Int,
    @field:Json(name = "risk_reminder_notification_period") val riskReminderNotificationPeriod: Int, // FIXME use me!
    @field:Json(name = "exposure_info_minimum_risk_score") val exposureInfoMinimumRiskScore: Int,
    @field:Json(name = "exposure_detection_period") val exposureDetectionPeriod: Int,
    @field:Json(name = "support_email") val supportEmail: String = defaultSettings.supportEmail
)
```
Since the backend is not publically available it's normal that this is not working.
> At the current stage, the application points to backend services which are not publicly accessible and whose source code has not been released. Note that the application is designed to work without a backend, especially in the context of not having the Exposure Notification entitlements (see Installation.

**Comment by Datalux** [comment]
In particular `termsOfServiceUrl` and `privacyPolicyUrl` variables are empty:
```
termsOfServiceUrl = "",
privacyPolicyUrl = "",
```
lines 91 and 92 of ConfigurationSettingsService.kt
