### ISSUE TITLE
[GENERAL] Notifica di servizio non attivo non rimovibile

### ISSUE THREAD

**Issue by adrfantini** [immuni-app/immuni-app-android#200]
La notifica "il servizio non è attivo" non è rimovibile in nessun modo e rimane in vista.
Se ho intenzione di rimanere in casa per svariate ore, ad esempio, disattiverò bluetooth e GPS, dato che non necessito di Immuni e dei suoi servizi. Dopo qualche ora, apparirà la notifica di cui sopra, di cui non posso disfarmi in nessun modo se non impedendo ad Immuni di produrre notifiche (il che ovviamente è contrario allo scopo dell'app) o riattivando l'app.

Google Pixel 3a, Android 10.

**Comment by marcouberti** [comment]
@adrfantini In realtà se clicchi sopra la notifica, ti riapre semplicemente l'app, ma senza riattivare il servizio. Devi riattivarlo a mano cliccando su RIATTIVA IL SERVIZIO.

La notifica e' stata implementata appositamente in questo modo per evitare che ci si dimentichi di aver disattivato il servizio. Dopo 4 ore la notifica riappare se il servizio non è stato ancora riattivato.

**Comment by adrfantini** [comment]
Capisco. Questi significa che in pratica, quando desidero l'app sia disattiva, mi arriva una notifica ogni 4 ore? Mi pare un po' invasivo (anche se capisco le ragioni), specie se devo toccare la notifica (invece che swiparla via) e aprire l'app solo per farla sparire. forse una buona via di mezzo è una notifica frequente, ma che si possa nascondere più facilmente.

**Comment by marcouberti** [comment]
Abbiamo modificato la logica delle notifiche per renderla meno invasiva, stessa frequenza, ma cancellabili. Inoltre non appena viene disattivato il servizio da dentro l'app (disponibile da versione 1.1.0 in su) appare una notifica di avvertimento immediatamente per ricordarti di riattivarlo il prima possibile. Questa fix sara' disponibile da una versione dell'app maggiore di v1.1.0.

**Comment by adrfantini** [comment]
Mi sembra molto ragionevole. Grazie e buon lavoro.
