### ISSUE TITLE
[BUG] Notification not cleared after re-enabling Exposure Notification service

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-app-android#204]
**Describe the bug**

The notification telling the user that the app is not working correctly is not automatically cleared after the app is re-enabled, unless the user taps on the notification.

**To Reproduce**

1. Disable Bluetooth
2. Wait (some hours) until a notification is shown, reminding the user that the app is not working correctly
3. Open the app through its icon in the launcher (do not tap on the notification)
4. Tap the red button to re-enable
5. Confirm Exposure Notification service activation in the Google Play Services popup
6. Observe that the app is confirming correct operation
7. Observe that the notification was not automatically cleared
8. Tap on the notification
9. Observe that now the notification has been cleared

**Expected behaviour**

The notification should be cleared automatically as soon as normal operation of the app has been restored.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

- Device: Nokia 2.2
- OS: Android 9
- Version: N/A

**Additional context**

N/A

**Comment by marcouberti** [comment]
@lmasellis this fix will be available in app version grater than v1.1.0.
