### ISSUE TITLE
[BUG] Exposure notification not active in background on Xiaomi and issue with battery saving

### ISSUE THREAD

**Issue by epidemotraining** [immuni-app/immuni-app-android#209]
Sul mio Pocophone F1 e sui due xiaomi dei miei genitori, un remdi A7 e uno che non ricordo, tutti con l'ultima MIUI, l'app non dà problemi apparenti tuttavia ho notato che i permessi erano settati come "Non permettere mostrare le notifiche in background". Non dovrebbe essere in automatico in on? 

E' inoltre sicuro che la modalità di risparmio energetico intelligente della MIUI lasci attiva Immuni in background? Perché sul cellulare dei miei genitori risulta come ultimo utilizzo 6 giorni fa, ovvero quando la ho installata.

**Comment by marcouberti** [comment]
@epidemotraining potresti fornirci uno screenshot di dove vedi quel permesso "Non permettere mostrare le notifiche in background"? E' una cosa specifica del Pocophone? Grazie

Le Exposure Notifications sono sempre attive, anche se l'app non lo e'. Infatti non fanno parte dell'app, ma dei Google Play Services.

**Comment by epidemotraining** [comment]
Certo, ecco lo screen, è così anche sugli altri cellulari xiaomi che ho visto. 
Così è come appare di default:
![immuni](https://user-images.githubusercontent.com/60882634/84172783-b22a3a80-aa7c-11ea-92f4-292724b6c4a9.jpg)

Quindi il fatto che Immuni sia nella modalità intelligente della MIUI non rischia che non sia attivo? Risulta che non è stata usata da 6 giorni semplicemente perché non essendo io nelle 4 regioni di test non si connette ai server per le chiavi ancora?

**Comment by marcouberti** [comment]
Le "Finestre pop-up" non sono le notifiche dell'app che vedi in alto nella barra. Immuni usa le notifiche normali per avvisare l'utente.

Immuni utilizza dei worker che girano in background per fare i check necessari periodicamente. Questi worker sono schedulati in un database di sistema (WorkManager). Anche se l'app non e' utilizzata, questi worker vengono eseguiti quando necessario.

Ci sono dei casi particolari, di dispositivi che non rispettano le linee guida di Google/Android, dove l'applicazione viene uccisa in malo modo, cancellando anche questi worker. Stiamo lavorando per risolvere anche questa problematica.

**Comment by epidemotraining** [comment]
Ah, perfetto, grazie mille per la risposta, ho imparato una cosa nuova su Android e grazie per il vostro prezioso lavoro!
