### ISSUE TITLE
Gestione delle notifiche di esposizione non attivate

### ISSUE THREAD

**Issue by PeraDev7** [immuni-app/immuni-app-android#21]
**Describe the bug**

Toast with "Notifiche di esposizione non attivate" next to App Wizard

**To Reproduce**

1. Open App
2. Select Region
3. Select City
4. Click Consenti
5. Toast with "Notifiche di esposizione non attivate" next to App Wizard
6. Wizard restart if i close and reopen app.

**Expected behaviour**

App starting(?)

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Huawei Mate 20 Lite
- OS: Android 10
- Version [e.g. 1.0.0] 1.0

**Comment by Talebian12** [comment]
Prima di fare qualsiasi cosa, leggete in README che fornisce le risposte alla maggior parte dei problemi:
`Please note that Google restricts the usage of the Exposure Notification API to government entities or developers approved by a government entity to develop an application on behalf of a government for COVID-19 response efforts. Full details are in the Additional Terms document. Otherwise, you may build and use the application, but you will not be able to use the underlying Exposure Notification system.`

**Comment by spectrumIG** [comment]
@PeraDev7 ho segnalato questo bug stamani. Ha ragione @Talebian12 , mi sono già scusato per aver fatto perdere un sacco di tempo agli sviluppatori e altra gente non avendo letto il Readme. Non ci si può fare nulla. Pare una policy delle API di Google.

**Comment by PeraDev7** [comment]
Si si, in effetti è vero.
Quindi il sorgente dell'app c'è, ma l'app non si può usare 🗡️  :D

**Comment by Talebian12** [comment]
> Si si, in effetti è vero.
> Quindi il sorgente dell'app c'è, ma l'app non si può usare 🗡️  :D 

Per ora, da quel che ho capito io stanno lavorando in modo da rendere questa roba non indispensabile e permettere le Reproducible Builds. Da quel che ho capito io almeno.

**Comment by PeraDev7** [comment]
Fonte?
In ogni caso modificando il sorgente si può accedere all'applicazione (?).

**Comment by spectrumIG** [comment]
@PeraDev7 lo puoi fare tranquillamente basta guardarlo e analizzarlo due minuti come ho fatto io stamani. Da quello che ho visto quell'errore è un check su un falg ritrornato dalla libreria...secondo me a prima vista mockarlo anche in maniera grezza solo per vedere come va avanti l'app dovrebbe essere abbastanza semplice. Prova e vedi. :)

**Comment by PeraDev7** [comment]
Fatto fatto. L'app funziona anche senza il servizio ;).

**Comment by RoseMouth** [comment]
@PeraDev7 Potresti descrivere cosa hai modificato per farlo funzionare perfavore? Io non riesco a trovarlo. Grazie mille in anticipo!

**Comment by PeraDev7** [comment]
Al momento non mi ricordo, è un semplice flag all'interno di un activity.

**Comment by andreaprati** [comment]
Basta cambiare le righe 56-58 di ExposureNotificationFragment.kt da:
    private fun canProceed(): Boolean {
        return viewModel.isBroadcastingActive.value ?: false
    }
a
    private fun canProceed(): Boolean {
        return true; 
    }
Grezzo, ma a me funziona. Ovviamente in ogni caso dice che il servizio non è attivo (come è giusto che sia).

**Comment by RoseMouth** [comment]
@andreaprati funziona, grazie mille!

**Comment by Talebian12** [comment]
> Basta cambiare le righe 56-58 di ExposureNotificationFragment.kt da:
> private fun canProceed(): Boolean {
> return viewModel.isBroadcastingActive.value ?: false
> }
> a
> private fun canProceed(): Boolean {
> return true;
> }
> Grezzo, ma a me funziona. Ovviamente in ogni caso dice che il servizio non è attivo (come è giusto che sia).

Va anche a me, perfetto.

**Comment by immuniopensource** [comment]
Buongiorno @PeraDev7 e grazie per la segnalazione. Siccome questo non rappresenta un bug ed è un duplicato di #8 sarebbe da chiudere però, dato che ci sono delle informazioni rilevanti per altri utenti, la possiamo temporaneamente lasciare aperta a beneficio di tutti. Rimuovo [BUG] dal titolo.

**Comment by ToldoDM** [comment]
Ho installato l'applicazione oggi e il problema e' ancora presente.
Siccome avevo gia' il bluetooth che il gps acceso, ho provato a spegnerli entrambi, e al momento di premere "consenti" mi e' venuta fuori la finestra che mi chiedeva il consenso/attivazione.
L'app ha attivato il bt e gps e sono riuscito a completare la sua configurazione.

Non so se possa esservi utile, ma volevo segnalare la cosa.

**Comment by sasadangelo** [comment]
Confermo quanto scritto da @ToldoDM. Sembra un problema comune a tutti i Huawei o almeno così sembra leggendo alcuni forum. La soluzione che mi ha permesso di far funzionale l'app è:
1. disinstallare l'app Immuni
2. disabilitare bluetooth e GPS
3. installare app Immuni
4. Seguire le varie schermate, quando arriva a quella delle notifiche appare un box che ti chiede di accendere Bluetooth e GPS, cliccando OK si risolve il problema e ti consente di andare avanti e attivare l'app.

**Comment by polettix** [comment]
Huawei P9 Lite:
- uscito dall'App Immuni
- disabilitato Bluetooth e GPS
- avviato App Immuni
- autorizzato l'attivazione del Bluetooth quando richiesto
- completata attivazione

Grazie @ToldoDM. Da notare che l'App non ha attivato il GPS.

**Comment by Gioxxy** [comment]
Stesso problema su Oneplus 7T Pro con OxygenOS, ma anche disabilitando BT e GPS non mi fa procedere
