### ISSUE TITLE
"Ultimo controllo della potenziale esposizione" / "Last checked for potential exposure"

### ISSUE THREAD

**Issue by quaqo** [immuni-app/immuni-app-android#217]
Su Android 8.0.0, Huawei Honor 8 e su un Huawei P10 Lite, andando a vedere l'ultimo controllo nella scheda dell'Exposure Notification Framework, l'ultimo controllo risale -per entrambi i device- a oltre una settimana fa.

Il comportamento è considerato normale? Ogni quanto viene effettuato il controllo?

**Comment by quaqo** [comment]
> Ogni quanto viene effettuato il controllo?

Dal codice capisco bene che dovrebbe essere effettuato ogni 4 ore?

**Comment by marcouberti** [comment]
@quaqo Si viene effettuato ogni 4 ore, tuttavia se non ci sono nuove chiavi di positività rispetto all'ultimo controllo, non viene passato nulla alla Exposure Notification API ed è quindi normale che la data di controllo ultima esposizione non risulti aggiornata.

**Comment by quaqo** [comment]
Quindi la data che vedo è l'ultima volta che Immuni ha visto una chiave positiva o l'ultima volta che ha trovato un match?

**Comment by marcouberti** [comment]
E' l'ultima volta che Immuni ha fatto un controllo di matching con le chiavi dei positivi che arrivano dal server. Se queste chiavi non sono aumentate, Immuni non riverifica il matching in quanto già fatto in passato.

**Comment by filippogasbarro** [comment]
Confrontandomi con un'altra persona ho notato che su Huawei effettua meno controlli riguardo il controllo l'ultima esposizione. Ad esempio su Huawei P20lite l'ultimo controllo dell'esposizione è del 13 giugno. Mentre nel Samsung A5 2017 ha effettuato ben 4 controlli in più in questo lasso di tempo.
C'è qualche problema con i Huawei? L'app immuni almeno una volta ogni due giorni l'ho aperta
