### ISSUE TITLE
[BUG] [Settings] Text in 3 different languages

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#219]
**Describe the bug**
In the Settings page, text is in 3 different languages, despite the system language being English.

**Screenshots**

![IMG_3502](https://user-images.githubusercontent.com/53472061/84637763-5fc2a100-aef6-11ea-9341-4837443fb13b.jpg)

**Comment by LauraB-QA** [comment]
Fix verified.
