### ISSUE TITLE
[FEAT] Status notification

### ISSUE THREAD

**Issue by Occhioverde** [immuni-app/immuni-app-android#229]
**Is your feature request related to a problem? Please describe it.**
Given that in many devices (including my Asus Zenfone 4 Max) there are particular systems for blocking the execution of apps in background it would be particularly convenient to have a status notification in the tray bar of Android so you can see at a glance if the service is running or not.

**Describe the solution you'd like**
In my opinion, a persistent notification with Immuni's logo and name and a message that says "Service running" would be sufficient.
Obviously this notification could be disabled by default and activated through the app settings only if necessary so as not to disturb users who may not like it.

**Additional context**
As you can see in [this image](https://imgur.com/9wsf0zB), it seems that the app is not activated when the device starts, which cannot be verified without a status notification.

**Comment by filioro** [comment]
Ciao @Occhioverde, sarebbe molto utile avere la notifica sempre presente, ma ti faccio anche notare che non è Immuni ad occuparsi di raccogliere i codici, ma il sistema operativo, quindi non credo ci siano problemi se Immuni non si attiva all'avvio, l'importante è che Immuni si attivi ogni tanto per controllare i codici sul server. :)

**Comment by Occhioverde** [comment]
@filioro Sì, sono d'accordo con te, però se dimentico di aprirla per qualche giorno rischio di ricevere le notifiche con notevole ritardo, sopratutto tenendo conto del fatto che la persona infetta potrebbe aver inviato la segnalazione dopo diverso tempo dal nostro incontro.

**Comment by multyissad** [comment]
this could also be fixed by the manifactures themselves updating their
bloody hell phones.
Also, Samsung has a tray notification saying that the app Immuni IS up and
running in the background.
Honestly, i am ready to spend 10% of my battery using this app, and knowing
if i got covid contact, rather than taking it without knowing it at all.

Il Gio 18 Giu 2020, 17:33 Riccardo Sacchetto <notifications@github.com> ha
scritto:
