### ISSUE TITLE
[BUG] Error Code 39501

### ISSUE THREAD

**Issue by nicolalandro** [immuni-app/immuni-app-android#232]
**Describe the bug**
Messaggio Error Code 39501 all'abilitazione dell'app.

**To Reproduce**

1. aggiornati i playservices
2. apri l'app
3. segui la procedura
4. clicca abilità
5. Messaggio Error Code 39501
-->

**Expected behaviour**
L'app manda un messaggio di ok e le notifiche funzionano correttamente

**Screenshots**
Non è possibile fare uno screenshot

**Smartphone (please complete the following information):**

- Device: Honor 9 Lite (LLD-L31)
- OS: Android
- Version  8.0.0 (EMUI)

**Additional context**

**Comment by giacmir** [comment]
I've got the same error on my Huawei P8 lite.

**Comment by nicolalandro** [comment]
Yesterday afternoon the app send me a push notification and it stats to work.

**Comment by shoyip** [comment]
I've got the same error today on Huawei P9.

**Comment by Shufang-Zhu** [comment]
I got the same error code on OPPO Reno4 Pro...
