### ISSUE TITLE
[GENERAL] notification noisy/unuseful "notifiche di esposizione disattivate"

### ISSUE THREAD

**Issue by filippogasbarro** [immuni-app/immuni-app-android#234]
# Issue content
Hello,
With the last two update of Immuni app, I notice that every time I put the phone in offline mode, appear the notification with title "Notifiche di esposizione disattivate", "per usare questa funzionalità, attiva il Bluetooth". Only on Android 11 putting Phone in offline mode doesn't switch off the Bluetooth (that practically nobody have it).
It's very noise this notification that, basically appear to a lot of us, every time we go to bed, by putting the devices in offline mode.

As you can understand this notification, In addition to be noise, it's unuseful (for most of us)

**Comment by Occhioverde** [comment]
If the problem is given by the sound that makes the notification you can always disable it by holding it down, pressing the settings button and setting the category priority to "High" instead of "Urgent" (Obviously every other level is fine, it's up to you to decide how you prefer to view it).

**Comment by filippogasbarro** [comment]
The problem is not the sound, but The fact that the notification appears every day before going to bed. Sometimes it seems that I had contact with a positive by appearing that notification in the status bar. But apart from that in notification settings of Google play services is not explicit to which notification is reffered to; like you see in the screenshot 
![Screenshot_20200622_211343_com huawei systemmanager](https://user-images.githubusercontent.com/15571375/85327008-83758080-b4ce-11ea-90a2-d32445653187.jpg)

**Comment by Occhioverde** [comment]
Well, in this case I think there is nothing to do.
Unfortunately as you have noticed this type of warning is managed directly by the operating system (in particular by Play Services) so I believe that the Immuni developers cannot remove the notification.
At most you can set an app like Tasker to automatically ignore it.

**Comment by filippogasbarro** [comment]
Ok, I'll try to contact Google directly for this aspect. Thank you
