### ISSUE TITLE
[GENERAL] Exposure notifications with bluetooth off

### ISSUE THREAD

**Issue by marco-venuti** [immuni-app/immuni-app-android#235]
It is unclear if it's possible (and if so how to) to keep exposure notifications active (and thus to periodically download exposure data) while keeping localization and bluetooth off.
This would be useful in situations where (like at home) no exposure with strangers can occur (and thus one may want to turn off GPS and BT), but one wants to be notified about potential previous exposures.

**Comment by Occhioverde** [comment]
As far as i know, if bluetooth is disabled without explicitly turning off the Immuni verification service, the operating system will (obviously) not be able to collect new codes but Immuni will continue to verify those already present.
The important thing is to check that you are not receiving Immuni's notification that the service is not running. Only in that case the contact list is not compared with the one on the server.

**Comment by marco-venuti** [comment]
Actually, on my device, the notification that Immuni is not running triggers as soon as I turn off either GPS or BT.
