### ISSUE TITLE
[FEAT] Put as alwasy on the visual flag on the selected province

### ISSUE THREAD

**Issue by epidemotraining** [immuni-app/immuni-app-android#236]
**Is your feature request related to a problem? Please describe it.**
I've received request of help by many old or inexperienced people that lamented Immuni "being bugged" because the dot on the "provincia" section doesn't stay on. The dot on the "regione" field stay on. All the mobile are xiamomi with MIUI.

**Describe the solution you'd like**
The dot flagging the "pronvincia" selected should always stay on.

**Additional context**
I'm a little concerned about this because a lot of those people said to me that they are considering removing Immuni because "it doesn't work at all if this don't work".

**Comment by marcouberti** [comment]
@epidemotraining are you referring to the "Edit your province" page not showing your latest province selection? Or to the onboarding page?
