### ISSUE TITLE
[GENERAL] Testo sbagliato nella Home

### ISSUE THREAD

**Issue by ItsFiloHere** [immuni-app/immuni-app-android#249]
Nella Home il tasto "Cosa puoi fare per proteggerti" riporta anche la scritta "Scopri come funziona l'app"
![Screenshot_20200707-134203_Immuni](https://user-images.githubusercontent.com/55856803/86776362-6efdc000-c058-11ea-85be-c455118cf9a6.jpg)

**Comment by sebaker88** [comment]
The app has been updated with the message "Find out more"
