### ISSUE TITLE
[BUG] [FR] [Settings] Ugly linebreak with French symbols.

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#250]
**Describe the bug**
There is an ugly linebreak because there must be a space before and after the symbol in French.
Is there a way to solve this problem without creating more issues with different screen sizes?

![IMG_3760](https://user-images.githubusercontent.com/53472061/86780237-d453b000-c05c-11ea-92bd-439ad781c5fc.jpg)

**Comment by Lazza** [comment]
Unicode `U+00A0` (non-breaking space), probably.

**Comment by titaniabanfi** [comment]
fix verified, thanks for the suggestion for the space!

**Comment by Lazza** [comment]
Unless GitHub is showing an incorrect preview, the proposed fix does not seem to include non-breaking spaces, it seems to remove the spaces.

The spaces are correct in French, they just need to be non-breaking:

https://fr.wikipedia.org/wiki/Guillemet#Usage_en_fran%C3%A7ais
