### ISSUE TITLE
[BUG] [DE] [Onboarding] Truncated text on "I've read the privacy notice" button

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#252]
**Describe the bug**
Truncated text on "I've read the privacy notice" button.
The word "gelesen" is missing in Android.

![IMG_3756](https://user-images.githubusercontent.com/53472061/86790658-f5220280-c068-11ea-9780-d32b87efc50f.jpg)

**Comment by marcouberti** [comment]
Since this happens only on one specific model and it is not easy to solve, I think we can close it until new cases arise.

**Comment by titaniabanfi** [comment]
closing because won't fix
