### ISSUE TITLE
[BUG] [Settings - Change Province] There's no way to dismiss the "change province" modal

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#258]
**Describe the bug**
 There's no way to dismiss the "change province" modal in Settings

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Change Province'
---> See there's no way to go back or dismiss the modal

![IMG_3938](https://user-images.githubusercontent.com/53472061/88772014-647aa600-d180-11ea-9f7a-23cc440c4a0d.jpg)

**Comment by marcouberti** [comment]
On Android you can always use the "back" physical button to navigate back.

**Comment by titaniabanfi** [comment]
closing - discussed offline
