### ISSUE TITLE
[BUG] If the Google Play Services are not updated, when migrating there are several problems with the new version of the app

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#259]
**Describe the bug**
If the Google Play Services are not updated, the app usability is compromised. 
- The "Service Status" tile is missing 
- There's only a push notification to warn about it (not very visible)
- After tapping on the push notification, the "Service Not Active" reactivate button is unresponsive.

**To Reproduce**

1. Update the app to version 1.3.1 (12050571)
2. Notice in the Home page, that the Service Status tile is missing
3. Tap on the push notification "Update Play Services"
4. Then go back to the app (without updating because it's an automatic update)
5. Now the red tile "Service Not Active" is visible
6. Tap on it
7. Tap on reactivate service
---> The button is unresponsive

**Expected behaviour**
It should be more intuitive for a user, for example, a blocking screen clearly saying you must update the Google Play Services or to wait some hours for the automatic updates.

**Screenshots**
![IMG_3932](https://user-images.githubusercontent.com/53472061/88773292-39915180-d182-11ea-81d5-9a11d38d4d8d.jpg)

[IMG_3933.mov.zip](https://github.com/immuni-app/immuni-app-android/files/4993491/IMG_3933.mov.zip)

**Comment by marcouberti** [comment]
Unfortunately this seems something related to the SDK update migration and it is not under our direct control.

**Comment by titaniabanfi** [comment]
closing because won't fix
