### ISSUE TITLE
Huawei P40 without Google play services 

### ISSUE THREAD

**Issue by matteopiccioni** [immuni-app/immuni-app-android#260]
On Huawei P40 without Google play services, app is not working
I think the app should be available in Huawei App Gallery and use Huawei push services too

**Comment by filioro** [comment]
Hi!
Immuni is based on Google's Exposure Notifications and, at the moment, you can use Immuni if your smartphone supports Google Play Services.

:)

**Comment by tiziodcaio** [comment]
Try using microg??? Maybe it works
