### ISSUE TITLE
[Question] Extending support for older version then Andorid 6.0?

### ISSUE THREAD

**Issue by TheDavLab** [immuni-app/immuni-app-android#261]
Dear all,

if I read and understood the documentation properly, looks like only limitation for the App to work is Bluetooth LE.
As BLE is supported since Android 4.3 and is into Bluetooth protocol since version 4.0 there are other reason to limit it to 6.0?

I know that OS fragmentation is one of the major issues about Android but as it's the most popular mobile OS and the very purpose of this project is to reach as many as possible devices in order to have a wide network to allow a better contact tracing in this way there are about 1174 mobile phones release between 2014 and 2016 model potentially left out, as not all phones received the upgrade to 6.0.

I wish to understand if there is the possibility to compile Immuni also for "older" devices. For example, my phone (Xiaomi Redmi 3 Pro, Android 5.1) was released in 2016 but never get the 6.0 upgrade but it should be able to run the App, but I do not know if there are essential features released in 6.0 and actually used by the app that are not present in precedent OS versions.

Thanks a lot for your effort.

**Comment by immuniopensource** [comment]
Hi @TheDavLab, the Exposure Notification API requires Android 6.0 or a higher version of the operating system.

Although it is technically possible to run Immuni on a device with an Android version below 6.0—as you correctly pointed out, there are older devices that support BLE—it won't leverage the Exposure Notification API, which defeats the purpose of having the app in the first place.
You can [read more about it here](https://developers.google.com/android/exposure-notifications/exposure-notifications-api).

Let us know if you have any further question, thank you!
