### ISSUE TITLE
[GENERAL] smartphone reset: how to re-import old data

### ISSUE THREAD

**Issue by tmontanaro** [immuni-app/immuni-app-android#262]
I need to reset my smartphone due to some troubles.
I would like to save the history of all the IDs so that after the reset the immuni app will continue to know all my old IDs and the history of "met" people. What can I do?

**Comment by tiziodcaio** [comment]
For the contact tracking you cannot re-add, for the green passes we should have an it!

**Comment by sebaker88** [comment]
Unfortunately it is not possible to save the ids, for privacy reasons the data is not saved.
