### ISSUE TITLE
[BUG] is not possible change language

### ISSUE THREAD

**Issue by alanStocco** [immuni-app/immuni-app-android#263]
**Describe the bug**

Is not possible to change the language of the App.

**To Reproduce**

In the system configuration of my Huawei P8 Lite 2017 I choose English language.
I can't change to Italian because the option is missing

**Expected behaviour**

Should be possible to choose between Italian and English.

**Mobile info**
Huawei P8 Lite 2017 Android  8

**Comment by tiziodcaio** [comment]
I think this is due to the must-use android app bundle 🙁

**Comment by sebaker88** [comment]
To change the language of the application it is necessary to change the language of the device used. For this reason you cannot change the language to Italian only for the Immuni app
