### ISSUE TITLE
[BUG] Notification vibration issues

### ISSUE THREAD

**Issue by pinux89** [immuni-app/immuni-app-android#268]
**Describe the bug**

vibrazione in "attività in background"  e "servizio attivo" nonostante sia disattiva nelle impostazioni di notifica

**To Reproduce**

-in background non è riproducibile ma accade spesso a distanza di pochi minuti (circa ogni 10 minuti vedendo il notification log)
-aprendo app notifica "sistema attivo" e vibra per qualche secondo

**Expected behaviour**
-compare " attività in background" ma senza vibrazione
-che venga rispettata dall'app il tipo di priorità della notifica e il flag vibrazione

**Smartphone (please complete the following information):**

- Device: Samsung A5 2017
- OS: 8.0
- Version 1.4.0

**Additional context**
la versione precedente non aveva questi problemi

**Comment by pinux89** [comment]
**Aggiornamenti e test**
-ho ridotto le vibrazioni cambiando la priorità notifiche su livello basso (su a5 2017)
- su motog g4 stock 8.1 e j3 custom lineageos 14.1 ( android 7.1.2) con le notifiche priorità alta non ci son problemi

**Comment by totarello91** [comment]
Anche io ricevo notifiche in continuazione dopo l'ultimo aggiornamento

**Comment by pinux89** [comment]
> 
> 
> Anche io ricevo notifiche in continuazione dopo l'ultimo aggiornamento

che telefono usi ? con quale versione di android?

**Aggiornamenti**
Nel "notification log" (Oreo 8.0 e 8.1) son presenti in contemporanea due notifiche una in background con channelId: foreground_service e una non in background con channelId:expsure_notification entrambe con priority: default.

nella notification log di android  7.1.2 è presente solo la notifica non in background e con channelId: exposure_notification

Deduco che forse, secondo me, il problema è nell'if  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)  di AppNotificationManager.kt

**Comment by pinux89** [comment]
problema presente anche su motog g4 stock 8.1 doppia notifica con vibrazione/suoni

**Comment by totarello91** [comment]
> > Anche io ricevo notifiche in continuazione dopo l'ultimo aggiornamento
> 
> che telefono usi ? con quale versione di android?
> 
> **Aggiornamenti**
> Nel "notification log" (Oreo 8.0 e 8.1) son presenti in contemporanea due notifiche una in background con channelId: foreground_service e una non in background con channelId:expsure_notification entrambe con priority: default.
> 
> nella notification log di android 7.1.2 è presente solo la notifica non in background e con channelId: exposure_notification
> 
> Deduco che forse, secondo me, il problema è nell'if if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) di AppNotificationManager.kt e che esegue entrambe le notifiche su Oreo+

Ho un Asus Zenfone 3 ZE520KL con versione Android 8.0.0

**Comment by enricocid** [comment]
Ricevo una notifica con scritto "Servizio attivo" molto frequentemente.
Quando sblocco il telefono dopo un lungo tempo di inattività ma anche durante l'utilizzo e se provo ad aprire immuni (non accadeva prima nemmeno aprendo l'app).
Sono su Xiaomi Mi A2 lite, Android 10.

**Comment by thesofakillers** [comment]
Stessa cosa quì, notifiche "servizio attivo" molto frequenti.
Samsung Galaxy S7
Android 8.0.0

**Comment by vipex** [comment]
Notifiche di "servizio attivo" random anche con telefono in stand-by

Oneplus 7T
OxygenOS 10 (Android 10)
Immuni 1.4.0

**Comment by pinux89** [comment]
Ah, a quanto pare è stata risolta anche con il suggerimento momentaneo che ho scritto su fb e non qui...abbassare la priorità delle notifiche. :+1:   chiudo dopo release

**Comment by filippogasbarro** [comment]
@pinux89 a mio parere il bug andrebbe tenuto aperto, in quanto non tutti gli utilizzatori di Android sanno "metter mano" alle impostazioni delle notifiche delle app. Andrebbe risolto con un aggiornamento software

**Comment by filippogasbarro** [comment]
Allego screenshot del notification log di Android (Samsung Galaxy A5 2017)
Come si può vedere si ricevono notifiche continue da Immuni, ad intervalli di circa mezz'ora/un'ora:

![continuous notification](https://user-images.githubusercontent.com/15571375/93301743-30734700-f7f9-11ea-9019-6cc77b440625.jpg)

![Notification detail](https://user-images.githubusercontent.com/15571375/93301777-3cf79f80-f7f9-11ea-84dc-dc5874e388b8.jpg)

Segnalo inoltre che le notifiche arrivano anche durante la notte, nonostante il cellulare fosse in offline mode (quindi con bluetooth spento). Play services comunica che le notifiche di esposizione sono disattivate, mentre Immuni comunica che il servizio è attivo 🤔.
![notification during night](https://user-images.githubusercontent.com/15571375/93302107-ba231480-f7f9-11ea-98ba-8703a9023045.jpg)

![play services off immuni on](https://user-images.githubusercontent.com/15571375/93302121-c14a2280-f7f9-11ea-84f4-f87b67377938.jpg)

**Comment by pinux89** [comment]
@filippogasbarro il codice risolutivo è stato scritto in https://github.com/immuni-app/immuni-app-android/pull/269 e sarà presente nella versione 1.4.1. Una volta che ha raggiunto il play store ti invito, come anche le altre persone qui presenti, a ritestarla e poi la chiudiamo

**Comment by marcouberti** [comment]
@pinux89 @totarello91 @enricocid @thesofakillers @vipex @filippogasbarro la versione 1.4.1 ha risolto il problema anche sui vostri device?

**Comment by thesofakillers** [comment]
Sí, problema risolto sembrerebbe

**Comment by enricocid** [comment]
> @pinux89 @totarello91 @enricocid @thesofakillers @vipex @filippogasbarro la versione 1.4.1 ha risolto il problema anche sui vostri device?

Risolto 👍😁
