### ISSUE TITLE
[BUG] [ONBOARDING] [DE] Odd linebreaks in Covid-19 Notification popup

### ISSUE THREAD

**Issue by titaniabanfi** [immuni-app/immuni-app-android#275]
In German, there are a couple of odd linebreaks in Covid-19 Notification popup in the Onboarding.

`Covid-19-Benachrichtungen`
`sicher`

- Device: Pixel 4
- OS: Android 11
- Version: 1.5.0 (12050577)

(Not happening in previous versions or smaller devices)

![IMG_4535](https://user-images.githubusercontent.com/53472061/93753945-3c984380-fc01-11ea-94d6-00fa3ffee9ec.jpg)

**Comment by marcouberti** [comment]
@titaniabanfi this is Google's SDK popup we cannot fix. Marked as "Won't fix".

**Comment by titaniabanfi** [comment]
Closing
