### ISSUE TITLE
[BUG] Play Store warns about unavailable space and installation fails

### ISSUE THREAD

**Issue by EverEve** [immuni-app/immuni-app-android#276]
Tried to install Immuni on my mother's Android phone 

Brand/model: Huawei Nova Smart DIG-L01
Play Store version: 21.8.19-21
Android version: 6.0

Phone has 600+ MB free. On my phone the Immuni app weights approx. 31 MB. 
As far as I understand, all system requirements are met. 

When I try to install it with from the Play Store, installation fails with "Unavailable space" message and the system ask me to uninstall apps and delete files in order to free additional space.

I've also asked for support by email 2 days ago (I've been given ticket number 00101729) but since then no-one answered.

**Comment by EverEve** [comment]
Hello, is there anybody in there?
Just nod if you can hear me
Is there anyone home?

**Comment by mirh** [comment]
Unavailable space is an error in the play store, it has nothing to do with individual apps. 
And it's kinda normal that it happens, they always try to guarantee at least some safety buffer (even though 600MB is the upper bound of what I'd feel comfortable)

**Comment by EverEve** [comment]
> 
> 
> Unavailable space is an error in the play store, it has nothing to do with individual apps.
> And it's kinda normal that it happens, they always try to guarantee at least some safety buffer (even though 600MB is the upper bound of what I'd feel comfortable)

Sorry, I think that you haven't understood the problem.

**Comment by mirh** [comment]
I did, and I'm telling you it's completely normal. 
On a phone with just 2GB of ram, half of your "officially free" space could be taken by [zswap](https://stackoverflow.com/a/17149141/5994170).

**Comment by EverEve** [comment]
Okay, if you believe so, who am I to change your mind?
