### ISSUE TITLE
[BUG] microG is updated but no exposure notification.

### ISSUE THREAD

**Issue by ghost** [immuni-app/immuni-app-android#277]
**Device info**
Device: Zuk Z2 Pro (z2_row)
Android version: AOSP Extended 6.5 (Android 9.0), no GAPPS
Play Services: microG 0.2.12.203315 (exposure notification is present)
microG device registration and safetynet enabled and Phonesky installed, but no Google account.
Immuni version: 1.5.0

**Bug description**
When I have to toggle exposure notification from Immuni at the first start, this message appears:
> IT: Google Play Services è aggiornato ma non può ancora abilitare le notifiche di esposizione.
EN: Google Play Services is updated but cannot enable exposure notification yet.

Couldn't attach a screenshot because Immuni doesn't allow it.

**To Reproduce**
1. Start the app on a device with microG (version above)
2. Accept all terms and fill with your location data.
3. Once you are at the exposure notification page, click on "Enable" ("Abilita").
4. See error; exposure notification is not enabled.

**Expected behaviour:**
Exposure notification should be enabled.

**Additional info**
As you can see in the following screenshot, the app does __not__ ask for location services permissions. It doesn't even appear on the list of all the apps requiring those permissions.
Location services and permissions work fine on other apps.
![Screenshot_20200923-191614_Impostazioni](https://user-images.githubusercontent.com/63900993/94046738-5f795200-fdd1-11ea-99e5-114a36e7b0a5.png)
![Screenshot_20200923-191646_Installazione_pacchetti](https://user-images.githubusercontent.com/63900993/94046757-686a2380-fdd1-11ea-86a3-6c4fdb506ca0.png)

**Comment by Tachi107** [comment]
I had the same issue, had to enable phone's bluetooth and location to fix it

**Comment by tiziodcaio** [comment]
Solved in latest versions of microg

**Comment by Tachi107** [comment]
Alright, feel free to close this then :)
