### ISSUE TITLE
Replay attack "in the past"

### ISSUE THREAD

**Issue by vincenzoiovino** [immuni-app/immuni-app-android#278]
Dear all,

As I will explain in this post I tried successfully to achieve a replay attack against myself, that is to make my phone receive a fake risk notification and in doing that I also identified what can be seen as an additional attack.

First of all, I remark that I did everything for research and study purposes. I discourage everyone to redo and replicate the  attacks described in this post. 
However, I think I may help the community and authorities to improve contact tracing apps disclosing the details. In fact, disclosing and making evident these vulnerabilities should motivate political authorities to take decisions like stopping contact tracing  apps at all during key events like voting as suggested by Gennaro et al. ( https://static1.squarespace.com/static/5e937afbfd7a75746167b39c/t/5f47a87e58d3de0db3da91b2/1598531714869/Exposure_Notification.pdf ) or taking serious countermeasures or taking in consideration the adoption of alternative protocols proposed by several researchers worldwide.

What I did is the following.

1.  I wrote this software: https://drive.google.com/file/d/1GJhsCyYheVM5LfZljsmMJLZNN1XhitAj/view?usp=sharing that can be used to generate from real TEK files published on the Immuni's server some RPIs+corresponding date/time. I use the software to generate such a pair of RPI+corresponding time/data (actually I also generate an encrypted metadata).

2. I wrote this software for Arduino to being used with an ESP32 device endowed with an SD card: https://drive.google.com/file/d/1KswnCByRhQlqlCN_ay68mn2FdE6b8kNc/view?usp=sharing
I compile this software in the firmware of the ESP32's device. I save the pair RPI+encrypted metadata generated by the software at step 1 in a file in the SD and I start broadcast as described in the comments of the code (more details can be found reading the code and in the comments therein).

3. I deleted every data and the cache from the Immuni app on the phone's victim (my own phone)  and I also deleted all checks and data from settings->google->exposure notification. I uninstalled Immuni and I reinstalled it and soon after I  disconnected the phone from Internet (but with bluetooth activated).

4. I sent the victim's phone (my own phone) "back to the past" by setting the phone's date/time to that date/time. B

5. After 10 minutes I did the same as in step 1-2 for the subsequent RPI (in temporal order) to be sure that the victim's phone receive at least two valid RPIs for more than 15 minutes.  That is, if the first RPI were for 1 Sep 2020 1:00AM, I generate the next RPI for 1 Sep 1:10AM.

6. After about 20 minutes, I stopped broadcast and I stopped the bluetooth on the phone.

7. I sent the phone "back to the future" by restoring the correct time/date and I rebooted the phone and then I reactivate Internet.

8. After some minutes the phone received a risk notification as you can see here: https://www.youtube.com/watch?v=ew_r09OTYT8&feature=youtu.be

Beyond being a  simulation of replay attack, this is an attack in itself. For instance, if somebody can have your phone for few seconds can change your time/data and then start broadcast and later when possibly the date/time will be restored by yourself or by the attacker you will receive risk notification. There are many real life situations where people hand their phones to other people.
Some people could be even interested in performing the attack against themselves: in fact, they could need to have the risk notification to not work and stay at home, etc.

The ease of mounting this attack should urge authorities to study countermeasures or reconsider the meaning of risk notification.

I remark again that nobody should use the software and the explanation I gave here for malicious and illegal purposes and maybe should not be used at all.
Moreover, mounting the attack alterates the counter of the Ministry of Health, so this shows that this counter may be unreliable and should not be used for official statistics. Furthermore, I recall that it is  currently practically impossible for authorities to  know whether a notification of risk notification is real or fake since the the risk notification are anonymous by design.

I also take the opportunity to spur Ministry of Innovation to study alternative solutions that withstand this and other known attacks. Research is fundamental for the progress. Several researchers in Italy and abroad proposed alternative solutions that should be considered in view of current and potential future attacks  against GAEN.

Kind regards

**Comment by vincenzoiovino** [comment]
Just a comment.
Martin Vuagnoux suggested me that the attack can work even without physical access to the victim's phone to change the time/date. If you use a fake base station you can send a wrong date/time.

**Comment by vuagnoux** [comment]
Congratulations Vincenzo! Your replay attack has been successfully tested on SwissCovid app.

However the Swiss export.bin format is different. There is no header of 17 lines such as described [here.](https://developers.google.com/android/exposure-notifications/external-export-files-verification)

To download the Swiss export.bin the request is the following:

```
date -d '2020-09-22 02:00:00 CEST'  +"%s"
1600732800
wget https://www.pt.bfs.admin.ch/v1/gaen/exposed/1601078400000
unzip 1601078400000
```

As you said, I propose to improve your attack to avoid physical access to the smartphone by changing the date with a fake base station (usually smartphones are synchronized with time and date of the mobile network) This can be done locally with a SDR (Software Defined Radio) and available open source tools. Disclaimer: this is illegal in almost all countries.

Probably easier if you share the same network (Wi-Fi) of the victim, you may also modify the date and time using a rogue NTP server.

 I guess it's time to reconsider [Attack E of this document](https://raw.githubusercontent.com/DP-3T/documents/master/Security%20analysis/Response%20to%20'Analysis%20of%20DP3T'.pdf) which was discussed in [this paper, page 22.](https://eprint.iacr.org/2020/531.pdf)

**Comment by immuniopensource** [comment]
Dear @vincenzoiovino,
thank you for reporting this replay attack. Unfortunately we believe that this is an attack against GAEN rather than Immuni and so it should be resolved by a protocol implementation update. 
Should you have suggestions for our own code base to prevent or mitigate the attack, please let us know and we will evaluate them.

**Comment by enrichman** [comment]
I've not digged deeply into the code, but to avoid the date/time tampering it could be useful to add a server side check of the time every X minutes. If the system clock is too much disaligned it could be worth to send a notification, or an alert to the user.

Could this help mitigating the issue?

**Comment by LAlbertalli** [comment]
@immuniopensource a possible mitigation should be to mark the captured RPI using the System Monotonic Clock and to correlate the monotonic clock with a trusted external time source (e.g: CloudFlare's secure time service https://developers.cloudflare.com/time-services/nts). Since the monotonic clock is guaranteed to be always increasing even if the user change the phone time (or an untrusted NTP server change the phone time), the relative sequence of RPIs will always be correct. Then synchronizing the clock with a trusted and authenticated time source will provide the absolute time keeping.

To explain better the algorithm. 
- Each RPI get marked with the system monotonic clock ([SystemClock.elapsedRealTime](https://developer.android.com/reference/android/os/SystemClock#elapsedRealtime()) on Android) 
- At regular interval, ImmuniApp sync with a secure NTP server (e.g: the one I discuss above) and create a mapping between NTP time and monotonic clock. With this information it update the past datapoint with a real world time
- After a reboot, the app check the database for time not properly converted and perform a forward conversion using the last converted datapoint

**Potential vulnerabilities**
- Attacks to the trusted secure clock could produce a skew in the time. This will require an attack against an internet infrastructure that will probably get noticed and could be mitigated
- Vulnerabilities to the implementation of the monotonic clocks could allow the attacker to still successfully change the time. This is possible but it is a much more complicated attack vector. The Immuni App could proactively mitigate this attack by checking that recorded RPIs are always monotonically increasing (phone restart will reset the time).
- A quick phone reboot before a successful time sync could cause data loss. This is potentially problematic because an attacker could block the access to the time service for a long time and destroy the notification. This is an error condition that should be surfaced to the user, but the results should be the lost of RPIs (and consequent contact tracing issues), not an erroneous notification. It is even possible to keep the data but mark it as suspicious.

Any comment @vincenzoiovino @vuagnoux ?

**Comment by vincenzoiovino** [comment]
> Dear @vincenzoiovino,
> thank you for reporting this replay attack. Unfortunately we believe that this is an attack against GAEN rather than Immuni and so it should be resolved by a protocol implementation update.
> Should you have suggestions for our own code base to prevent or mitigate the attack, please let us know and we will evaluate them.

Dear Team of Immuni,
thanks for you reply. 
I apologize in advance if you can find my spirit too critical but I hope you understand that it is because I am worried for a so important project that affects the citizens' privacy and the National Security. I would really like to contribute to the success of "Immuni", and I think your main mistake was to give up to the pressure of the proponents of the so called straightforward decentralized model. Having you chosen a different and BETTER model, the app would now be a) more secure, 2) more flexible in case of need of fixing bugs and c) would have had more support from the scientific community. Only to the death there is no solution.

I summarize my questions, thoughts and suggestions in some points.

1.  Is the Team of the Ministry and Technology responsible only for the graphical interface and backend of Immuni or is it also responsible of providing to the citizens an overall reliable app/service? Is the app/service immutable or can be changed in the future to withstand critical attacks? 
To my knowledge, you did not subscribe any contract with Google&Apple  that forces you to use GAEN. 
In France and other countries there are equally valid apps that work without GAEN. 
Just as an example, if due to an unresolvable bug of company X, all the citizens' data present on a the server of company X would be exposed what one should do? Look immediately at alternative non-bugged servers or just keep saying that it is a problem of company X and doing nothing?
And in the case of GAEN, the problem is even more evident: with company X usually institutions subscribe legal contracts, with Google&Apple there is no such contract. In fact, an important researcher from Google told me privately that any issue/problem in the use of GAEN is not responsibility of Google, the legal authorities in each country that implement the GAEN-based apps are the only responsible; in our case this is the Ministry of Innovation and Technology responsible for Immuni. In theory, Google & Apple could even discard and ignore any  bug and suggestion of your team, they have no responsibility: they offer an API that suffers this problem, it is your "fault" if you use their APIs in a way that would allow malicious people to perform operations that cause social and political consequences in Italy.

2. If you admit, as you do, this serious problem, and you admit you cannot solve it, you should start to look at alternative solutions as France and other countries did.
 In Italy several reserachers proposed several solutions that are resistant to replay attacks.
My team for instance proposed Pronto-C2 and very recently Pronto-B2 (the name is dedicated to Berlusconi-Briatore) that have good resistance to replay attack: https://eprint.iacr.org/2020/493.pdf
and Buccafurri et al.  also provide a solution with good security properties: https://arxiv.org/abs/2005.10309

3. Even if you cannot or do not want to do anything to solve the problem, the transparency is fundamental. Did you inform the Ministry of Health that the number of risk notifications the Ministry receives is EASILY FAKEABLE?

4.   Were not you really aware of this attack? As Martin pointed out, these attacks were known theoretically and having you (unlike ours) possibility of debugging, you could have tested these attacks more carefully and informed us. To my knowledge there is no security analysis of Immuni and you never collaborated with people like Serge Vaudenay who discovered this and more attacks and could have helped you.

4. Beyond proposing to look at alternative solutions, I actually do have a likely solution to withstand replay attacks that works with GAEN and would just require a change at the app level. Unfortunately, the Immuni's ecosystem is not (contrarily to what you write in your FAQ) open source and is not even testable, so I cannot perform tests to confirm whether my solution may really work. If I had the possibility of debugging, this would help. 
Being your process IMHO completely non-transparent until now, having you based the app on a system that is not publicly debuggable,  and for other reasons,  I prefer to not disclose my solution here. But I am open and you may contact me privately. 

5. Immuni is only a drop in the bucket. In November there are the elections in USA and the main reason on why I am studying these attacks is because I am really worried that malicious hackers could sabotage  the elections, for instance through massive but undetected replay attacks. My mission is to defend The Great Trump and I will fight to make these apps disabled during the elections and to prevent Trump's adversaries and foreign Nations to attack him.


To conclude, I remark again that the research is the core of the Innovation. I hope you will pursue more collaborations with researchers in Italy and abroad and look and study alternative solutions.

Thank you for your work

Kind regards

**Comment by vincenzoiovino** [comment]
> @immuniopensource a possible mitigation should be to mark the captured RPI using the System Monotonic Clock and to correlate the monotonic clock with a trusted external time source (e.g: CloudFlare's secure time service https://developers.cloudflare.com/time-services/nts). Since the monotonic clock is guaranteed to be always increasing even if the user change the phone time (or an untrusted NTP server change the phone time), the relative sequence of RPIs will always be correct. Then synchronizing the clock with a trusted and authenticated time source will provide the absolute time keeping.
> 
> To explain better the algorithm.
> 
> * Each RPI get marked with the system monotonic clock ([SystemClock.elapsedRealTime](https://developer.android.com/reference/android/os/SystemClock#elapsedRealtime()) on Android)
> * At regular interval, ImmuniApp sync with a secure NTP server (e.g: the one I discuss above) and create a mapping between NTP time and monotonic clock. With this information it update the past datapoint with a real world time
> * After a reboot, the app check the database for time not properly converted and perform a forward conversion using the last converted datapoint
> 
> **Potential vulnerabilities**
> 
> * Attacks to the trusted secure clock could produce a skew in the time. This will require an attack against an internet infrastructure that will probably get noticed and could be mitigated
> * Vulnerabilities to the implementation of the monotonic clocks could allow the attacker to still successfully change the time. This is possible but it is a much more complicated attack vector. The Immuni App could proactively mitigate this attack by checking that recorded RPIs are always monotonically increasing (phone restart will reset the time).
> * A quick phone reboot before a successful time sync could cause data loss. This is potentially problematic because an attacker could block the access to the time service for a long time and destroy the notification. This is an error condition that should be surfaced to the user, but the results should be the lost of RPIs (and consequent contact tracing issues), not an erroneous notification. It is even possible to keep the data but mark it as suspicious.
> 
> Any comment @vincenzoiovino @vuagnoux ?

The app should work most of the time even without Internet access, with no wifi and no data, actually without sim card at all, etc.
The adversary could just (actually should) disconnect the phone from Internet. Any solution like the one you suggest seems to me to give an improvement only for the periods of times in which the phone is connected, the adversary would just disconnect the phone. Moreover, being the system anonymous by design, the adversary can ever redirect the traffic to its servers via standard techniques, etc.
Last but not least, the attack can (should) be mounted when Immuni is installed first time or after having deleted all prior data etc.
Moreover, recall 1) that it is an attack in itself send notfication to yourself and 2) the attack with the time machine was done just to simulate a real replay attacks and any suggestion like yours would not help to withstand real-time replay attacks.

Kind regards

**Comment by enrichman** [comment]
> > @immuniopensource a possible mitigation should be to mark the captured RPI using the System Monotonic Clock and to correlate the monotonic clock with a trusted external time source (e.g: CloudFlare's secure time service https://developers.cloudflare.com/time-services/nts). Since the monotonic clock is guaranteed to be always increasing even if the user change the phone time (or an untrusted NTP server change the phone time), the relative sequence of RPIs will always be correct. Then synchronizing the clock with a trusted and authenticated time source will provide the absolute time keeping.
> > To explain better the algorithm.
> > 
> > * Each RPI get marked with the system monotonic clock ([SystemClock.elapsedRealTime](https://developer.android.com/reference/android/os/SystemClock#elapsedRealtime()) on Android)
> > * At regular interval, ImmuniApp sync with a secure NTP server (e.g: the one I discuss above) and create a mapping between NTP time and monotonic clock. With this information it update the past datapoint with a real world time
> > * After a reboot, the app check the database for time not properly converted and perform a forward conversion using the last converted datapoint
> > 
> > **Potential vulnerabilities**
> > 
> > * Attacks to the trusted secure clock could produce a skew in the time. This will require an attack against an internet infrastructure that will probably get noticed and could be mitigated
> > * Vulnerabilities to the implementation of the monotonic clocks could allow the attacker to still successfully change the time. This is possible but it is a much more complicated attack vector. The Immuni App could proactively mitigate this attack by checking that recorded RPIs are always monotonically increasing (phone restart will reset the time).
> > * A quick phone reboot before a successful time sync could cause data loss. This is potentially problematic because an attacker could block the access to the time service for a long time and destroy the notification. This is an error condition that should be surfaced to the user, but the results should be the lost of RPIs (and consequent contact tracing issues), not an erroneous notification. It is even possible to keep the data but mark it as suspicious.
> > 
> > Any comment @vincenzoiovino @vuagnoux ?
> 
> The app should work most of the time even without Internet access, with no wifi and no data, actually without sim card at all, etc.
> The adversary could just (actually should) disconnect the phone from Internet. Any solution like the one you suggest seems to me to give an improvement only for the periods of times in which the phone is connected, the adversary would just disconnect the phone. Moreover, being the system anonymous by design, the adversary can ever redirect the traffic to its servers via standard techniques, etc.
> Last but not least, the attack can (should) be mounted when Immuni is installed first time or after having deleted all prior data etc. so the increasing conter would not stop the attacker (and would create additional problems since even honest users sometimes happen to change time by mistake or for some good reasons; in this case you could stop the app from working just by changing time once?)
> 
> Finally recall 1) that sending notfication to yourself is an attack in itself and 2) the attack with the time machine was done just to simulate a real replay attacks and any suggestion like yours would not help to withstand real-time replay attacks.
> 
> Kind regards

If I got it right the solution proposed by @LAlbertalli was to use the system monotonic clock, not a real time clock.
With this you should be able to correlate any counterfeiting of the clock, and (probably) solve the issue.

The use of the GAEN framework was due to some limitation of the Apple system, or even Android, that could kill the app or limit the usage of the bluetooth.

**Comment by vincenzoiovino** [comment]
> If I got it right the solution proposed by @LAlbertalli was to use the system monotonic clock, not a real time clock.
> With this you should be able to correlate any counterfeiting of the clock, and (probably) solve the issue.
> 
> The use of the GAEN framework was due to some limitation of the Apple system, or even Android, that could kill the app or limit the usage of the bluetooth.

I see but his solution also needs, I think, to periodically syncs with a real time server, so the attacker could anyway play with fake time.
However, any solution to the time machine is not a solution to real-time replay attacks that is the main concern for Immuni.
Recall that I did this to _simulate_ a real replay attack.

**Comment by LAlbertalli** [comment]
@vincenzoiovino yes, it needs to synchronize from time to time to an external clock. But there are secure solutions for time synchronization like the one I have shown from Cloudflare that uses TLS to verify the server. So an attacker should or compromise TLS or the time keeping infrastructure. This is always possible, but it increases the attack complexity and make the detection easier.

For the problem of a Real Time replay attack, you are correct but those are indeed different attacks. In a Real Time scenario there is no certainty about having a person infected to cause widespread panic but only a probabilistic one. While the attack you describe uses keys shared by infected and is a more targeted attack. It is indeed possible to make it a widespread attack but there are limitations such us how often the phone resynch the time and how long you could run the attack before being spotted.

On a side note: I read your paper on Pronto-B2 and Pronto-C2. They are interesting protocols with lot of potential but I feel your analysis of Replay attack it is limited to a mono-directional real-time attack. If your proposal (or one using a similar approach) where to be implemented, an attacker would just create a bi-directional link between locations. This is a technique used by car theft to unlock cars with proximity keys, so it is not unrealistic for an attacker to use such an attack. Obviously, this reduces the probability of a successful attack to the time when both an infected is in place A and the target are in place B, but it is still possible with some clever tricks to make the attack works.

**Comment by vincenzoiovino** [comment]
> @vincenzoiovino yes, it needs to synchronize from time to time to an external clock. But there are secure solutions for time synchronization like the one I have shown from Cloudflare that uses TLS to verify the server. So an attacker should or compromise TLS or the time keeping infrastructure. This is always possible, but it increases the attack complexity and make the detection easier.
> 
Hello,

If I got right, for your solution to work I think you need this sync "from time to time" to occur at least in the two circumstances: first installation and reboot.

This could affect negatively the functionality of the app. The app should possibly work without internet. On the other hand, if you are not strict in the sync after first installation, reboot, etc. the adversary will still have chance of success, especially attacking his/her open phone (that, as we said, is an attack in itself beyond alterating the counter of the Ministry of Health).

Cheers
> For the problem of a Real Time replay attack, you are correct but those are indeed different attacks. In a Real Time scenario there is no certainty about having a person infected to cause widespread panic but only a probabilistic one. While the attack you describe uses keys shared by infected and is a more targeted attack. It is indeed possible to make it a widespread attack but there are limitations such us how often the phone resynch the time and how long you could run the attack before being spotted.
> 
> On a side note: I read your paper on Pronto-B2 and Pronto-C2. They are interesting protocols with lot of potential but I feel your analysis of Replay attack it is limited to a mono-directional real-time attack. If your proposal (or one using a similar approach) where to be implemented, an attacker would just create a bi-directional link between locations. 

True. Mono-directional as It is. With very few modifications you can "encrypt" the GPS position and be safe against bidirectional attacks as well (I will check).
In GAEN of the GPS position were used trivially, It would be instead a disaster for privacy. In pronto-B2/C2 It can be simply "encrypted"  with no consequences for privacy. 



This is a technique used by car theft to unlock cars with proximity keys, so it is not unrealistic for an attacker to use such an attack. Obviously, this reduces the probability of a successful attack to the time when both an infected is in place A and the target are in place B, but it is still possible with some clever tricks to make the attack works.

**Comment by vincenzoiovino** [comment]
> @vincenzoiovino yes, it needs to synchronize from time to time to an external clock. But there are secure solutions for time synchronization like the one I have shown from Cloudflare that uses TLS to verify the server. So an attacker should or compromise TLS or the time keeping infrastructure. This is always possible, but it increases the attack complexity and make the detection easier.
> 
> For the problem of a Real Time replay attack, you are correct but those are indeed different attacks. In a Real Time scenario there is no certainty about having a person infected to cause widespread panic but only a probabilistic one. While the attack you describe uses keys shared by infected and is a more targeted attack. It is indeed possible to make it a widespread attack but there are limitations such us how often the phone resynch the time and how long you could run the attack before being spotted.
> 
> On a side note: I read your paper on Pronto-B2 and Pronto-C2. They are interesting protocols with lot of potential but I feel your analysis of Replay attack it is limited to a mono-directional real-time attack. If your proposal (or one using a similar approach) where to be implemented, an attacker would just create a bi-directional link between locations. This is a technique used by car theft to unlock cars with proximity keys, so it is not unrealistic for an attacker to use such an attack. Obviously, this reduces the probability of a successful attack to the time when both an infected is in place A and the target are in place B, but it is still possible with some clever tricks to make the attack works.


I also would like to add a comment about the "probabilistic" attack. You mean that you capture data hoping that they belong to users who later upload data. You implicitly consider that this procedure can fail in probability.
In my opinion the only "obstacle" for the attacker is the fact that Immuni is still not very widespread. So, let us assume Immuni someday will be very widespread (not just downloaded, but used by a large fractions of people who move around).
As an example, the attacker can go to the Capodichino airport.
 I bet that in each day from August until now there has been >= 1 person who tested positive at the airport. I did the test there one month ago, and I observed that all people had to transit through the same queue passing through a public space where other people can freely seat, there are tables of bars, and many objects where an attacker  can put sniffers (or even in his/her pocket), etc.
So, assuming that each day at that airport there is at least one people who does the test and will be diagnosed positive (a very mild assumption supported by the past evidence until now) the attacker can just put a sniffer in a position where all the tested people have to pass through. The attacker will succeed with probability almost 1.

The adversary can fail only if few people passing through the sniffer used Immuni.
So there is a tradeoff. Either few people use Immuni (and in this case Immuni is non useful) or many people use Immuni and so is trivial to mount massive (real-time) replay attacks just going to Capodichino airport or any place where any day there are people tested positive.

The scaring side of the replay attack is that there is almost no way to detect them, the sniffers are completely passive and can stay in the pocket of the attackers.

**Comment by blaispe** [comment]
> Congratulations Vincenzo! Your replay attack has been successfully tested on SwissCovid app.
> 
> However the Swiss export.bin format is different. There is no header of 17 lines such as described [here.](https://developers.google.com/android/exposure-notifications/external-export-files-verification)
> 
> To download the Swiss export.bin the request is the following:
> 
> ```
> date -d '2020-09-22 02:00:00 CEST'  +"%s"
> 1600732800
> wget https://www.pt.bfs.admin.ch/v1/gaen/exposed/1601078400000
> unzip 1601078400000
> ```
> 
> As you said, I propose to improve your attack to avoid physical access to the smartphone by changing the date with a fake base station (usually smartphones are synchronized with time and date of the mobile network) This can be done locally with a SDR (Software Defined Radio) and available open source tools. Disclaimer: this is illegal in almost all countries.
> 
> Probably easier if you share the same network (Wi-Fi) of the victim, you may also modify the date and time using a rogue NTP server.
> 
> I guess it's time to reconsider [Attack E of this document](https://raw.githubusercontent.com/DP-3T/documents/master/Security%20analysis/Response%20to%20'Analysis%20of%20DP3T'.pdf) which was discussed in [this paper, page 22.](https://eprint.iacr.org/2020/531.pdf)

Sure, SDR will work , (ex. tools like Great Scott Gadgets HackRF One )
