### ISSUE TITLE
[GENERAL] Segnalazione di positività - Propongo di inserire dettagli sugli operatori sanitari abilitati all'inserimento del codice monouso

### ISSUE THREAD

**Issue by giuragu** [immuni-app/immuni-app-android#282]
Salve,
Sono un utente Android. Per segnalare la positività viene generato dall'app il codice da indicare all'operatore sanitario che ha comunicato la positività, affinché quest'ultimo sblocchi la possibilità per l'utente di concludere la segnalazione della positività sull'app. Ma l'operatore sanitario che ha comunicato la positività non conosce la procedura e non sa aiutare il soggetto "positivo". Non sa nemmeno chi sia l'operatore a ciò predisposto. Sto parlando di un caso reale.

Penso che sia necessario inserire nella app delle istruzioni più dettagliate che consentano di superare questo fastidioso stallo.
Ad esempio rinviando ad un elenco degli operatori sanitari (con dettagli su recapiti e contatti) che hanno accesso al "sistema" che gli consente di inserire il codice fornito dall'utente, permettendogli di sbloccare l'app e concludere quindi il processo di segnalazione della positività.

Spero qualcuno possa verificare la fattibilità e magari implementare questa mia proposta.

**Comment by giuragu** [comment]
Aggiungo. Quando si installa e si attiva l'app viene richiesto di inserire la regione di riferimento. Avere sull'app l'elenco degli operatori censiti sul vostro sistema? Potrebbe essere un'idea?
Attendo fiducioso

**Comment by lucanomax** [comment]
Non ho mai avuto la sfortuna (o fortuna) di dover segnalare la positività, ma suppongo che solo l'ASL ha accesso al sistema.

**Comment by giuragu** [comment]
Penso di si @lucanomax. Ma Immuni dovrebbe avere elenco di chi ha accesso al sistema...giusto?

**Comment by lucanomax** [comment]
@giuragu Come ho detto non ho mai ricevuto notifiche, ma credo che già ci siano istruzioni su chi contattare, basato sulla provincia che hai messo. Se sbaglio, credo sarebbe buono mettere i recapiti delle varie asl basate sulla provincia scelta.

**Comment by giuragu** [comment]
Esatto. Sarebbe utile avere l'elenco degli operatori sanitari della propria "provincia" (come Immuni definisce le Regioni). Il problema è comunque lato "positivo" che deve segnalare la positività.

**Comment by lucanomax** [comment]
@giuragu Non sai il numero della tua ASL?

**Comment by giuragu** [comment]
> @giuragu Non sai il numero della tua ASL?

@lucanomax certamente. Ho chiamato i vari numeri ASL e nessuno prende in carico la cosa, perché non la sanno prendere in carico e non sanno a chi altro indirizzarmi per risolvere il problema.

**Comment by quaqo** [comment]
Confermo. Ho **due** amici sintomatici che sono a casa malati (non si conoscono tra loro e sono di ASL diverse), utenti della prima ora di Immuni per dovere civico, come me del resto, e che non sono riusciti nemmeno insistendo a dare il codice. Nessuno sa nulla. Ad uno dei due è stato detto che il codice lo genera il MMG. Questo è IMHO pericolosissimo perché oltre a vanificare l'efficacia dell'app, potrebbe infine disincentivarne l'utilizzo se si iniziasse a vederla come inutile.

**Comment by giuragu** [comment]
@quaqo che poi il problema non è generare il codice ma inserirlo da qualche parte per sbloccare l'app all'utente positivo nella fase di segnalazione. Questo aggiunge ulteriore tassello a prova della non conoscenza dell'app da parte degli operatori sanitari

**Comment by quaqo** [comment]
> @quaqo che poi il problema non è generare il codice ma inserirlo da qualche parte per sbloccare l'app all'utente positivo nella fase di segnalazione. Questo aggiunge ulteriore tassello a prova della non conoscenza dell'app da parte degli operatori sanitari
> 

Esatto. Non sanno di cosa si parli purtroppo (non che sia colpa dell'operatore, sia chiaro: dovevano essere formati!). Questo rende vano il fatto di aver scaricato con Immuni.

**Comment by giuragu** [comment]
Proprio così @quaqo. Se Immuni riuscisse a implementare questa feature sarebbe un bel passo avanti. Avrei davanti un operatore che certamente saprebbe come fare perché certamente ha accesso al sistema. Se ciò non fosse possibile, rimarrebbe la necessaria e urgente formazione e informazione di tutti gli operatori coinvolti. Spero e confido nella prima soluzione

**Comment by quaqo** [comment]
Oppure che lavorino con le ASL per includere un codice nel referto così che anche il cittadino possa fare l'upload.

**Comment by giuragu** [comment]
> Oppure che lavorino con le ASL per includere un codice nel referto così che anche il cittadino possa fare l'upload.

Potrebbe essere altra opzione. In questo caso però ci sarebbe un legame stretto tra codice app e codice fiscale tale da minare alla privacy una volta indicato codice sull'app in fase di upload? (riflessione a voce alta)

**Comment by quaqo** [comment]
Giusto.

**Comment by TommasoAzz** [comment]
Ripropongo, a maggior ragione dopo gli ultimi fatti di cronaca.

**Comment by giuragu** [comment]
> Il riferimento è a questo servizio vero? https://www.iene.mediaset.it/video/test-pungidito-app-immuni-giulio-golia_892916.shtml

Quello riportata è la situazione che hanno vissuto e stanno vivendo diversi positivi e in varie Regioni. Con ricerche che durano anche giorni e non sempre si concludono con la segnalazione. A questo punto ci sono evidenze almeno da Sicilia, Lombardia, Veneto, Liguria e Lazio.

**Comment by lucanomax** [comment]
Spero che con una movimentazione mediatica su questo argomento le ASL si adeguino con immuni. C'è anche da dire che abbiamo avuto il picco di download da pochi giorni, se le persone iniziano a usare immuni in massa probabilmente anche le ASL "_impareranno cosa fare_" con le notifiche.
In genere con la sanità italiana non c'è da riporre tanta fiducia, ma non possiamo fare altro lol

**Comment by giovannidoni** [comment]
Mi inserisco nel thread perchè credo che la notifica di positività sia da trasmettere attraverso l'app e per tutelare la privacy, l'esito dell'esame in seno alle asl dovrebbe essre indicizzato con solo l'hash usato da immuni e generato in corrispondenza del tampone. Di fatto mi sembrerebbe logico attendersi che questo diventi uno standard.
