### ISSUE TITLE
[BUG] Controlli esposizione poco chiari...

### ISSUE THREAD

**Issue by garethjax** [immuni-app/immuni-app-android#286]
**Describe the bug**

Vengono segnalate delle notifiche di esposizione poco comprensibili, come si vede dagli screenshot
- ieri sono state segnalate 4 notifiche alle 22:27 e una alla 1:18 del mattino
- abito al quarto piano di un condominio, a quell'ora ero in camera a programmare. Con me abita mia madre, che non ha installato immuni.
- all'1.18 sicuramente dormivo.

**To Reproduce**

entra nel sistema di contact tracing di android e guarda le ultime segnalazioni

**Expected behaviour**

Orari e segnali più realistici. O comprensibili ? 

**Screenshots**

![Screenshot_20201009-103549](https://user-images.githubusercontent.com/3459602/95562051-e823ff00-0a1b-11eb-9aa1-bf33d44b4a4c.png)
![Screenshot_20201009-103516](https://user-images.githubusercontent.com/3459602/95562055-e9edc280-0a1b-11eb-98d4-b36820a98c74.png)

**Smartphone (please complete the following information):**

- Device: Motorola One Vision
- OS: Android 10
- Version QSAS30.62-33-4

**Additional context**

**Comment by lucanomax** [comment]
Quelli sono i controlli che fa l'app per confrontare i tuoi codici con i codici di persone risultate positive.
Non penso ci sia modo per controllare in tempo reale quando effettivamente scambia i codici, sarebbe un problema per la privacy.

Quindi quelli sono solo i controlli che fa sul server centrale, dove vengono caricati i positivi.
