### ISSUE TITLE
[GENERAL] adblocker blocks connections to api.myendpoint.io 

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [immuni-app/immuni-app-android#288]
# Issue content
Long time user of [Blokada](https://github.com/blokadaorg/blokada), I noticed that it defaults to blocking connections to api.myendpoint.io 

Since I could not find any attempts prior to installation of Immuni, I think this is the source.
If my guess is correct, a few questions:
1. what is Immuni trying to do?
2. is it required for normal operation?

For the time being, I've added an exception for the app, yet I am curious.

**Comment by enricocid** [comment]
I'm not sure, but it could be related to rest api and the connection request/response to gather data for the different fields (faq content, for example).

**Comment by corbindavenport** [comment]
Found this issue while looking for something else, this might explain things: https://www.vice.com/en/article/jgqm5x/us-military-location-data-xmode-locate-x

**Comment by Miriam-cpu** [comment]
Hi AndreaBorgia-Abo, could you post the id of the App you identified as source? Was is this one? it.ministerodellasalute.immuni
