### ISSUE TITLE
[BUG] Scambio chiavi interrotto

### ISSUE THREAD

**Issue by micheledellaguardia** [immuni-app/immuni-app-android#291]
Di tanto in tanto il controllo esposizioni con lo scambio di chiavi si interrompe, nonostante il mio device sia quasi perennemente connesso durante il giorno.
Anche dopo un lungo periodo di disconnessione (per esempio la notte) alla riconnessione mi aspetterei un tentativo di verifica delle chiavi e invece se vado a controllare non trovo nulla.
E' dunque necessario che io chiuda forzatamente l'app e dopo un riavvio posso vedere che nei "Controlli esposizione" ci sono nuovi check con numerose nuove chiavi verificate.

- Device: Xiaomi Mi A1
- OS: Android 9
- Version 2.0.0

**Comment by andreapede** [comment]
Probabilmente è un duplicato di questa
Duplicate of #233
