### ISSUE TITLE
[BUG] No push notification

### ISSUE THREAD

**Issue by marcofio25** [immuni-app/immuni-app-android#294]
**Describe the bug**

Oggi ho aperto l’app per caso e ho trovato una notifica di esposizione a rischio per caso. Le notifiche push non hanno funzionato anche se attive. Stessa cosa è capitata ad alti 3 utenti di mia conoscenza

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 3a]
- OS: [e.g. Android 9]
- Version [e.g. 1.0.0]

**Additional context**

**Comment by enrichman** [comment]
Potrebbe essere dovuto ad alcune limitazioni di alcune tipologie di smartphone, come specificato nella pagina principale dell'app.

Se clicchi "Scopri di più" troverai [questo messaggio](https://github.com/immuni-app/immuni-app-android/blob/master/app/src/main/res/values-it/strings.xml#L339):

> Per motivi tecnici, <b>alcuni modelli di smartphone Android possono interrompere il funzionamento di Immuni se l’app rimane chiusa per qualche giorno</b>. Quando questo accade, lo scambio di codici casuali con altri dispositivi rimane attivo, ma Immuni non è in grado di verificare se sei stato esposto a utenti potenzialmente contagiosi, avvertendoti in caso di rischio. Per evitare che ciò accada, apri l’app una volta al giorno. Google sta collaborando con i produttori di questi modelli per risolvere il problema.

**Comment by marcofio25** [comment]
Buongiorno,
Io e gli altri utenti abbiamo un iPhone quindi no android.

**Comment by MichaelSiddi** [comment]
Ciao @marcofio25, 
se il problema che segnali è su iOS, questo non è il posto giusto in quanto siamo sul repository dell'app Android.

Trovi una segnalazione già aperta su iOS a questo indirizzo: https://github.com/immuni-app/immuni-app-ios/issues/322#issue-726371671

Michael
