### ISSUE TITLE
[FEAT] Do not send push notifications at nighttime

### ISSUE THREAD

**Issue by Valeri0p** [immuni-app/immuni-app-android#297]
**Is your feature request related to a problem? Please describe it.**
Hello. I've noticed notifications to re-enable the service if it gets shut down are more common now, but it would be better to send them only during the day, since it's unlikely to have made any potential contact if you are sleeping, and also to avoid notifications to be delivered in the middle of the night. (yes, it happened just moments ago, with all connectivity features disabled except mobile phone service)
**Describe the solution you'd like**
One way we could solve this is to never send non-urgent notifications (so this would exclude the "notifiche di possibile contatto") between 00:00 and 8:00 am for example; a series best practices on how other apps handle this issue probably already exist.
**Describe alternatives you've considered**
Unless there's an option in the OS to do this manually for each app, I don't know how one would try to solve this.

Thanks for your time and for developing this app.

**Comment by ilovelinux** [comment]
Hi, as far as I know the notification is sent by Google Services, not by Immuni. You can use "Do not disturb" mode to silence that notification. Anyway there are no reasons to shutdown it on night.

**Comment by Valeri0p** [comment]
Thanks for your reply.
![20201120_204330](https://user-images.githubusercontent.com/24795760/99842991-1b0bf780-2b71-11eb-9b71-f2784e329716.jpg)
![Screenshot_20201120-161412_Settings](https://user-images.githubusercontent.com/24795760/99843024-265f2300-2b71-11eb-9b7e-f453aebbf4cb.jpg)
That notification seems to be generated by Immuni as far as I can see.
I can turn on the "do not disturb" mode on my phone and maybe disable the audio for this app's notifications, but it would still be nice to be able to differentiate between service messages and important messages, so that people won't get frustrated by receiving it when they aren't using the app.
