### ISSUE TITLE
[BUG] Huawei P8 Lite non supportato

### ISSUE THREAD

**Issue by polarene** [immuni-app/immuni-app-android#298]
**Describe the bug**

Ho provato ad installare Immuni tempo fa ma il Play store dice che il mio Huawei P8 non è supportato (modello ALE-L21). Come mai, dato che la versione minima supportata del sistema è la 6, che il mio telefono ha? Mi dispiace molto perché avrei voluto installare Immuni per il tracciamento.

**Smartphone (please complete the following information):**

- Device: Huawei P8 Lite
- OS: Android 6

**Comment by enricocid** [comment]
Strano. 
Potrebbe dipendere dalla versione di Google Play Services installata? Ce lo hai aggiornato?
https://play.google.com/store/apps/details?id=com.google.android.gms

Oppure dallo stato della certificazione play protect? Si vede dalla impostazioni del PlayStore.

So che se il telefono non lo è alcuni servizi Google non sono accessibili ...

**Comment by polarene** [comment]
Grazie delle info, provo a controllare play services e le altre impostazioni e ti faccio sapere!

**Comment by polarene** [comment]
Ecco i dati:
- Google play services 20.39.15, sembra aggiornato
- Certificazione Play Protect: Dispositivo certificato

L'unica particolarità che noto è che molto tempo fa ho disabilitato Google Play Edicola/Film/Giochi/Libri/Musica per risparmiare spazio. Può dipendere da questo?

**Comment by enricocid** [comment]
> Ecco i dati:
> 
> * Google play services 20.39.15, sembra aggiornato
> * Certificazione Play Protect: Dispositivo certificato
> 
> L'unica particolarità che noto è che molto tempo fa ho disabilitato Google Play Edicola/Film/Giochi/Libri/Musica per risparmiare spazio. Può dipendere da questo?

No, io anche l'ho disattivata quella app e a me immuni si scarica.
Non saprei, devi aspettare gli sviluppatori a questo punto. 👍🏻

Per curiosità, il paese che hai impostato sul PlayStore (in account, dalla tendina laterale) è Italia?
Prova anche a controllare che il PlayStore sia aggiornato.

Comunque i telefoni Huawei e Honor hanno avuto diversi problemi ...

**Comment by polarene** [comment]
Grazie ancora dei consigli, proverò queste ultime strade. Speriamo che qualcuno degli sviluppatori legga qui.

**Comment by balanza** [comment]
Confermo stesso problema sul mio Huawei P8 Lite. 

Io ho immuni installato da sempre, periodicamente lo apro per vedere se è tutto ok.
Questo per dire che il problema è sorto negli ultimi 7-10 giorni.

**Comment by polarene** [comment]
Alla fine, dopo aver letto un articolo su questo problema, ho aggiornato Huawei Mobile Services ma purtroppo non ha funzionato: Play Store non mi visualizza proprio l'app e sul web mi dice che il mio modello non è supportato.

**Comment by enricocid** [comment]
Mi chiedo che fine hanno fatto i dev ...

**Comment by tiziodcaio** [comment]
Salve avete risolto?

**Comment by sebaker88** [comment]
@polarene what operating system is installed on your device? Immuni works with Android 7+

**Comment by polarene** [comment]
È scritto nella descrizione in cima: Android 6. Però sullo store o altrove avevo letto che era supportata, altrimenti non mi sarei disturbato ad aprire questo issue.

**Comment by polarene** [comment]
Haha adesso non compare nemmeno più nella ricerca su Play Store... ma quando ho scritto l'anno scorso compariva però non me la faceva installare. Diceva che il *modello* non era supportato, non il SO. Vabbè nel mentre avrete alzato la versione minima, pazienza... non ho mai potuto utilizzare Immuni.
