### ISSUE TITLE
[BUG] Crash on start

### ISSUE THREAD

**Issue by mirh** [immuni-app/immuni-app-android#303]
**Describe the bug**

The app continues to crash, there's no way to open it. 

**To Reproduce**

1. Simply open the app. 

Sometimes the error message it has crashed even pops up while I'm doing something else. 

**Smartphone (please complete the following information):**

- Device: Sony Xperia XZ2 Compact
- OS: Android 9
- Version: 52.0.A.3.27

**Additional context**
Logcat [here](https://github.com/immuni-app/immuni-app-android/files/5632163/logimmuni.txt). You should even see my crash report in the google play console.

**Comment by scambusters** [comment]
Crash on Oneplus 6 
O.s. Android 10

**Comment by mirh** [comment]
If you don't provide a log you aren't helpful.

**Comment by ilovelinux** [comment]
Probably useless but, did you tried to clean app data? Maybe something got corrupted

**Comment by mirh** [comment]
Yes, I know that should be able to fix it (like in #280 perhaps)
Still, my reasoning is.. your grandma isn't going to care about such tip. The app should work even with malformed inputs, and I'm trying to help figuring out what's going on.

**Comment by ilovelinux** [comment]
I agree with you. I was just trying to understand if the crash is device-related. It probably isn't since it happens getting the app's preferences..

**Comment by berga** [comment]
Hi, I have the same problem on LG G7 ThinQ Android 10.
I've already reset the app data and uninstalled many times, after some period of time It began crashing. I've sent the Android report too, so please keep an eye on Google play console.

**Comment by mirh** [comment]
Still a thing with 2.2.1.

**Comment by mirh** [comment]
Well, last week for some reason the app reset by itself, and asked me again to insert my info and all. 

... Today it somehow closes on start, but it technically isn't outright crashing, so even though the original bug is still probably there I cannot really reproduce anything anymore. Sad.
