### ISSUE TITLE
Servis isn't ready yet - Error code:39507

### ISSUE THREAD

**Issue by tburakozdemir** [immuni-app/immuni-app-android#310]
# Google Play Services

I keep getting this error on both my physical phone and the emulator, is there any method to fix it?

![error](https://user-images.githubusercontent.com/54362580/103304507-de59d880-4a19-11eb-9ea6-48fde3a1517d.png)
![error2](https://user-images.githubusercontent.com/54362580/103304519-e285f600-4a19-11eb-9624-d759d17e4d76.jpeg)

**Comment by kolzar** [comment]
I have the same error. Any Workaround?

**Comment by filioro** [comment]
find the following lines of code using Ctrl + Shift + F:

private fun canProceed(): Boolean {
return viewModel.isBroadcastingActive.value ?: false
}

then change "return viewModel.isBroadcastingActive.value ?: false" to "return true".
