### ISSUE TITLE
Profilo di lavoro non supportato.

### ISSUE THREAD

**Issue by albertuan** [immuni-app/immuni-app-android#314]
**Errore 39501 su TUTTI I DEVICE con TUTTI GLI ANDROID se attivato il profilo di lavoro.**

Il profilo di lavoro è quella funzionalità che permette di avere le "doppie app" sul telefono, quelle private e quelle lavorative. Se il telefono viene attivato come "solo lavorativo" il problema non sussiste, in quanto il bug non sembra essere presente su Android For Work, ma solo su Android con il Work Profile . Maggiori informazioni sul profilo di lavoro :
https://support.google.com/work/android/answer/6191949?hl=it

**Riprodurre l'errore**

Passaggi necessari per riprodurre l'errore:
1. Aggiungere un account lavorativo di un Google Worspace con la gestione dei dispositivi mobili avanzata attivata.
https://support.google.com/a/answer/7396025?hl=it
2. Confermare l'installazione di googole policy (fa tutto lui in atuomatico) se il passaggio precedente è corretto.
https://play.google.com/store/apps/details?id=com.google.android.apps.enterprise.dmagent&hl=it&gl=US
3. Installare l'app immuni e provare ad attivarla
4. Alla fine, dopo il pulsante attiva, appare l'errore

**Non si attiva ed appare l'errore**
Google Play Service non è ancora pronto, Google Play Service è aggiornato ma no può ancora abilitare le notifiche di esposizione. Riprova più tardi

**Screenshots**
![20210224-ERROR-APP-IMMUNI](https://user-images.githubusercontent.com/59246021/108964815-445e8700-767c-11eb-9c5b-c5c77578a7c5.jpg)

**Ci ho provato con 3 smartphone, con 3 versioni diverse di Android. Eccone uno:**
- Device: [Motorola Edge]
- OS: [Android 10]
- Version [Livello Patch primo ottobre 2020]

**Comment by astagi** [comment]
Ciao @albertuan grazie per la segnalazione! Come da documentazione solo il profilo principale può accedere alle Exposure Notification API. Per maggiori informazioni https://developers.google.com/android/exposure-notifications/implementation-guide#prereqs
