### ISSUE TITLE
[GENERAL] The app should not require a Google account

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-app-android#32]
As discussed in 
https://github.com/immuni-app/immuni-documentation/issues/65 the app cannot be installed, used or kept up-to-date unless the user connects its phone to a Google account.

This is both a privacy risk (the same executable providing the Exposure Notification service is aware of user's identity), as well as a fair competition issue (the government should not oblige a citizen to subscribe a certain private service, even if free of charge, in order use a public service).

**Comment by powext** [comment]
I'm sorry but this is the umpteenth issue that has no purpose other than being useless.

The app is "made" by Ministero della salute so **It can't technically be a public service, and it isn't even a service.**

There are no other solutions other than using Google and Apple APIs that guarantee fast implementation, good user experience, and this level of anonymity.

Also, what you wrote is kinda conspiracy, if you don't trust Apple and Google just don't use the app, you are not obliged.

**Comment by lmasellis** [comment]
> I'm sorry but this is the umpteenth issue that has no purpose other than being useless.

You are not obliged to agree on other people's views, but the fact you don't share them does not mean they are useless. Maybe you think you own absolute truth; I don't (neither I think I own it myself).

> The app is "made" by Ministero della salute so **It can't technically be a public service, and it isn't even a service.**

So the app is provided and sponsored by the government, but it's not a public service? LOL.

> There are no other solutions other than using Google and Apple APIs that guarantee fast implementation, good user experience, and this level of anonymity (and you wrote about privacy lol).

Who says that? You?
And, think of it, the only reason why Google's way is the only way is because Google restricted the use of BLE just at the same time they announced their Exposure Notification service with Apple.

> Also, what you wrote is kinda conspiracy, if you don't trust Apple and Google just don't use the app, you are not obliged.

No conspiracy theories here. Just don't understand why I should trust private entities operating under a foreign jurisdiction more than a legitimate government of a democratic country. Everybody has been shouting at government in order to see Immuni's source code (and this is perfectly right), but only a few are questioning whether Google and Apple will behave as they promised. This just does not make any sense.

> EDIT: Google said that they will profile full documentation of how to reproduce Exposure Notifications APIs in systems that are Google Services lacking, so there is no competition.

So, question: if the Exposure Notification service is reimplemented in open source for use on AOSP based devices or other platforms, will Immuni support it? I would ask nothing more than that.

At the moment what I see is that in order to use Immuni you have to use Google approved device, you have to connect it to a Google account and you have to just hope that Google behaves in good faith, because you have no means to verify. And this is a fact.

You may think this is right, I don't.

**Comment by rriemann** [comment]
This is indeed a privacy problem. If the app cannot be used without a Google account, than the entity determining the purpose and means of the personal data processing of this app (called *controller* in GDPR) risks to nudge people in accepting Google's terms of service and become responsible (*co-controllership*) for the processing of Google.

Google uses personal data amongst others for profiling and advertising purposes. However, the public service has in most if not all circumstances no mandate to become involved in these purposes. To lower the risk of nudging and offer privacy-friendly alternatives, offering other deployment means is an important element. This can be done for instance with F-Droid (see #143).

**Comment by gabrielelucci** [comment]
It is absolutely shameful to be forced to use Google services to use a public service.

**Comment by ferdi2005** [comment]
>I'm sorry but this is the umpteenth issue that has no purpose other than being useless. [...] Also, what you wrote is kinda conspiracy, if you don't trust Apple and Google just don't use the app, you are not obliged.

Questa è una risposta terribile che non mi aspetto e non accetto quando si discute di una questione così importante, come il non voler concedere a Google i propri dati personali ed il controllo sul proprio dispositivo. Specialmente, da una persona che in qualche modo rappresenta un servizio erogato dal Ministero della salute (e nel momento in cui il servizio denominato Immuni è erogato dall'ente pubblico Ministero della salute e sponsorizzato tramite campagne di pubblica pubblicità, forse potrebbe anche essere definito servizio pubblico).

E spero di non ricevere risposte del tipo "I'm sorry but this is the umpteenth issue that has no purpose other than being useless".

**Comment by tallero** [comment]
>There are no other solutions other than using Google and Apple APIs that guarantee fast implementation, good user experience, and this level of anonymity (and you wrote about privacy lol).

[citation needed]

**Comment by tallero** [comment]
Che risate.
