### ISSUE TITLE
Google Play Services isn't ready yet 39501

### ISSUE THREAD

**Issue by S1077117** [immuni-app/immuni-app-android#325]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Redmi K40
- OS: Android
- Version MIUI 12.5.3 Stable

**Additional context**

**Comment by cunidev** [comment]
Can confirm the same issue on my Vivo X50 Pro+, Origin OS (Android 10) v1.0.

**Comment by cunidev** [comment]
Duplicate of #232 / #157?
