### ISSUE TITLE
[FEAT] Skip activation for vaccine certificate

### ISSUE THREAD

**Issue by cunidev** [immuni-app/immuni-app-android#335]
Firstly, a big "thank you" to the Immuni developers for their excellent work. As a developer myself, I really appreciate the effort and active development of this tool.

After switching to a new phone, I am experiencing the common "39501" issue affecting many Chinese devices with Google Play Services. This did not, unfortunately, let me activate the "exposure notifications" (?) through BLE beacons.

However, having received my vaccine certificate some days ago, I would love to be able to activate the app also for the purpose of showing it upon need, even though my hardware does not currently allow the app to function correctly for some reason. 

Granted, this would have the side effect of people downloading the app without the main, useful feature of contact tracking in it, so while I would like to have a solution to this, maybe what I am proposing may not be the best choice. 

Mutually exclusive "vaccine certificate or contact tracking" does not probably make much sense either, since even for fully vaccinated people can apparently be carriers of the virus to some extent (https://www.nebraskamed.com/COVID/can-i-still-spread-covid-19-after-vaccination).

Thanks in advance.

**Comment by WAPEETY** [comment]
I support this idea

**Comment by cunidev** [comment]
Uh. Certificate already landed in the IO app apparently, so this may not be necessary in general.
