### ISSUE TITLE
[FEAT] Allow adding EU digital covid certificate from QR rather than only by retrieving it from DGC

### ISSUE THREAD

**Issue by lciti** [immuni-app/immuni-app-android#343]
**Is your feature request related to a problem? Please describe it.**
As far as I can see, the only way to add a covid vaccination certificate is to retrieve it from DGC using an AUTHCODE. I could not find a way to add a certificate to Immuni (v2.5.1) by scanning the QR of a previously generated certificate.

**Describe the solution you'd like**
I would like to be able to add a certificate by scanning the QR of the digital certificate. This would be useful, for example, to add certificates of vaccinations received in other EU countries.

**Describe alternatives you've considered**
This feature is currently available and working as expected in the [Swiss](https://github.com/admin-ch/CovidCertificate-App-Android) and [German](https://github.com/Digitaler-Impfnachweis/covpass-android) apps.

**Comment by dariotrombello** [comment]
Reopen this
