### ISSUE TITLE
[GENERAL]  Round corners of EU - Vaccination pass cannot be read by VerificaC19

### ISSUE THREAD

**Issue by Oviing** [immuni-app/immuni-app-android#345]
# Round corners of EU - Vaccination pass cannot be read by VerificaC19

The android version of immuni renders the corner of the QR code round. Therefore the three position squares are incomplete and the VerificaC19 or any other app cannot understand that this is an QR code. The same QR code could be read on the iOS version of the immuni app, so I can guarantee that the QR was correct. The iOS version of immuni renders the corner sharp, so that the full QR is displayed.

Devide: Samsung S10e
Android: 11 (latest Updates)
Immuni: Latest version

**Comment by matpag** [comment]
I don't have this problem with a Pixel 3a and version 2.5.2.
Did you tested with latest version of Immuni?
