### ISSUE TITLE
[BUG] province change removes certificate

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [immuni-app/immuni-app-android#348]
If you already have the EU certificate on your phone, it will be lost when moving to another province.

1. Ensure you have a certificate, perhaps using the [recovery procedure](https://www.dgc.gov.it/spa/public/reqauth)
2. In the settings, change to another province
3. Verify that the certificate is now gone

**Expected behaviour**
The certificate remains available in the app.

**Smartphone**

- Device: Moto G5S plus
- OS: Android 8.1
- Version: latest

**Additional context**
First observed with Bologna to Modena, tested with Modena to Bologna

**Comment by astagi** [comment]
@AndreaBorgia-Abo thank you for reporting this issue! The problem has been fixed in #350 and the relative patch will be released in the next version.
