### ISSUE TITLE
[BUG] Samsung Galaxy J3 (2016) not supported

### ISSUE THREAD

**Issue by SxtBox** [immuni-app/immuni-app-android#359]
**![Screenshot_2021-09-29-01-06-06](https://user-images.githubusercontent.com/60861585/135177857-89c18e50-43f0-4973-85a5-35b85c38ff43.png)**

![Screenshot_2021-09-29-01-15-15](https://user-images.githubusercontent.com/60861585/135178091-d823f739-96a2-4065-b914-cff1cef62405.png)

![Screenshot_2021-09-29-01-16-30](https://user-images.githubusercontent.com/60861585/135178190-9b4605f0-7042-40a7-b4c4-f29b0ddff4c5.png)

it seems to me that you will force people to change phones too now
App link https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni

**Comment by tiziodcaio** [comment]
This is a good phone, I suggest to unlock it to install an updated custom rom to solve the problem

**Comment by sebaker88** [comment]
Unfortunately, your smartphone's operating system is not supported. The app is available for Android 7+.

**Comment by SxtBox** [comment]
> Unfortunately, your smartphone's operating system is not supported. The app is available for Android 7+.

YOU ARE VERY FASTER DUDE
