### ISSUE TITLE
[BUG] Incorrect Warning is triggered when user becomes positive

### ISSUE THREAD

**Issue by serenadg** [immuni-app/immuni-app-android#39]
**Describe the bug**
Incorrect Warning is triggered when users become positive. Text refers to having been in contact with a positive user when the users are actually positive themselves.

**Smartphone (please complete the following information):**

- Device: Huawei P30
- OS: Android 10
- Version (42)

[Untitled.mp4.zip](https://github.com/immuni-app/immuni-app-android/files/4679068/Untitled.mp4.zip)

**Comment by VaiTon** [comment]
Should've been closed with 695f08f I guess.

**Comment by titaniabanfi** [comment]
fix verified
