### ISSUE TITLE
incorretto ambito di visibilità

### ISSUE THREAD

**Issue by ghost** [immuni-app/immuni-app-android#42]
nel file HomeListAdapter.kt vi è la classe HomeListAdapter che presenta il clickListener, sarebbe meglio che questa fosse dichiarata privata

**Comment by immuniopensource** [comment]
Buonasera @oppo99 e grazie per il contributo. Sarebbe possibile avere maggiori informazioni in merito a questa richiesta per facilitare il triage? Grazie molte!

**Comment by oppo99** [comment]
https://github.com/immuni-app/immuni-app-android/blob/fbe92126af503cd2c3cc1510eb6621a93d2f1b1a/app/src/main/java/it/ministerodellasalute/immuni/ui/home/HomeListAdapter.kt#L37

dovrebbe diventare     private val clickListener: HomeClickListener
