### ISSUE TITLE
[BUG] Missing or placeholder content to change

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#45]
**Describe the bug**
There are missing/placeholder/not working parts that will need to be changed before releasing:

- [x] TOS are missing (placeholder)
- [x] Privacy Policy is missing (placeholder)
- [x] FAQ cannot be opened (connection error message)

**Comment by powext** [comment]
See #20

**Comment by LauraB-QA** [comment]
Fix verified on v1.0.1
