### ISSUE TITLE
[BUG] Connection to Google Play is done over HTTP

### ISSUE THREAD

**Issue by plaguna** [immuni-app/immuni-app-android#46]
The file PlayStoreActions.kt has a hardcoded HTTP connection to the Google Play Store. This can lead to MiTM attacks.

**Comment by cortinico** [comment]
Already fixed by #34

**Comment by ilovelinux** [comment]
It is still an issue since #34 hasn't been merged yet

**Comment by ilovelinux** [comment]
It's still an issue since #34 hasn't been merged yet
