### ISSUE TITLE
[GENERAL] What will happen switching phones?

### ISSUE THREAD

**Issue by romeop555** [immuni-app/immuni-app-android#48]
I need to send my phone to assistence, and i will use a temporary phone for at least one month, using a temporary phone.

What will happen when i will use again main main phone?

Can be the data tracked by my temporary phone "added" to my main phone?

What if i will notify Covid by my main phone? Will contacts with my temporary phone alerted?

Many thanks

**Comment by marcouberti** [comment]
Hi, this is not possible. The Immuni app has been designed to preserve the privacy at the maximum level so there is no way to map your different phones to your user. Moreover the Apple/Google SDKs don't offer this feature.
