### ISSUE TITLE
[FEAT] Alternate constructor to provide a default layout for Fragments

### ISSUE THREAD

**Issue by nicopasso** [immuni-app/immuni-app-android#49]
**Code conciseness**
Using `androidx.Fragment`, it's possible to clean up a bit each `Fragment` class by removing the `onCreateView` method with the layout inflation in favor of the alternate `Fragment` constructor that allows providing the default layout.

[Androidx Fragment releases page](https://developer.android.com/jetpack/androidx/releases/fragment)
<img width="805" alt="Screenshot 2020-05-26 11 24 35" src="https://user-images.githubusercontent.com/1663205/82884030-7c953580-9f43-11ea-9abd-d721d9d755f5.png">

**Example**
Instead of writing
```kotlin
class MyFragment: Fragment() {

// ...

override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.my_fragment, container, false)
    }
}
```
it's now possible to simplify it with:
```kotlin
class MyFragment: Fragment(R.layout.my_fragment) {
    // onCreateView no longer needed
}
```

**Comment by spectrumIG** [comment]
@nicopasso Are you sure they are not using it already? I thought I saw that in a Fragment base class of some sort...

**Comment by nicopasso** [comment]
@spectrumIG I've checked most of the Fragments in the app and all have `onCreateView`. The layout in the constructor is used only for `DialogFragment`s that extend `BaseStateDialogFragment`

**Comment by spectrumIG** [comment]
Ah ok...yes, correct. I get what you mean , now.

Il mar 26 mag 2020, 12:54 Niccolò Passolunghi <notifications@github.com> ha
scritto:
