### ISSUE TITLE
[GENERAL] Question: will AOSP device (or "derivative" like LineageOS) be supported? 

### ISSUE THREAD

**Issue by vixrt** [immuni-app/immuni-app-android#50]
I'm referring to this comment 
https://github.com/immuni-app/immuni-app-android/issues/32#issuecomment-633687782

`Google said that they will profile full documentation of how to reproduce Exposure Notifications APIs in systems that are Google Services lacking, so there is no competition.`

Apparently, there is a way to develop the app even for AOSP users. I'm talking about users that, by choice, do not have google play service installed (so, for example, LineageOS without gapps)

Is it true?
Do you have any plans on doing it? 

Thanks

**Comment by spectrumIG** [comment]
@vixrt  That comment is referring to a library not the entire app. Those are two different things.
It means that Google will release the specifications for that library and if you want you can implement another library with them. So what action should the developer do?Develop that library? i think that is way behind their responsabilies. 
Also AOSP users is a terms that doesn't mean anything in this context. AOSP is the Google repository for SOME part of Android not another OS or something like that. Kindle Fire, LineageOS, OxygenOS, FlyMe OS, ecc...are derivative FROM that repository. Some of them choose to be Google partners and have inside their system PlayService and GAPP and other don't. But this is again behind the scope of this app.
For the record , this is NOT A FORUM, it's an issue tracker for which there's an ISSUE TEMPLATE to fill. It's common practice in open source project of ANY kind to follow the rule of owner of the repository.

**Comment by Talebian12** [comment]
Immuni only works if you have GApps installed.  It works perfectly on Galaxy Note 8 with Lineageos 17.1.

**Comment by Arcilollo** [comment]
I installed it on LineageOS 16.0 using MicroG and it won't work because I need to update the google play services. It would be perfect if I can run it without the need of gps (google play services)

**Comment by vixrt** [comment]
> 
> 
> Immuni only works if you have GApps installed. It works perfectly on Galaxy Note 8 with Lineageos 17.1.

I have updated my answer. What I'm asking is precisely the case when the user does not have google play service installed

**Comment by Talebian12** [comment]
> > Immuni only works if you have GApps installed. It works perfectly on Galaxy Note 8 with Lineageos 17.1.
> 
> I have updated my question. What I'm asking is precisely the case when the user does not have google play service installed

Google Play Services are required.

**Comment by vixrt** [comment]
> 
> 
> > > Immuni only works if you have GApps installed. It works perfectly on Galaxy Note 8 with Lineageos 17.1.
> > 
> > 
> > I have updated my question. What I'm asking is precisely the case when the user does not have google play service installed
> 
> Google Play Services are required.

I know that, read again my question. I asked if they have plans to bring a version of the app without them

**Comment by ziozoomer** [comment]
I installed Android AOSP version on my phone. It was the first thing I did just bought the phone because i don't want gapps. Why this app needs the google services? They were made various statements regarding privacy. I would like to install it, but if the gapps are required, I can not install it.

**Comment by andrew-ld** [comment]
you can use opensource reimplementation of play services, it have implemented the exposure api

https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-675739396
