### ISSUE TITLE
[BUG] Visual Glitch on Android 10

### ISSUE THREAD

**Issue by eliseomartelli** [immuni-app/immuni-app-android#52]
**Describe the bug**

There's a visual glitch on Android 10 on the "Scopri di più" section. 
There's a grey bar at the top of the navigation bar.

**To Reproduce**

1. Open the app
2. Click on "Scopri di più" 
3. Look at the gray bar

**Expected behaviour**

No gray bar.

**Screenshots**
<a href="https://ibb.co/j5vVJrk"><img src="https://i.ibb.co/BPV4nC2/photo-2020-05-26-14-49-52.jpg" alt="photo-2020-05-26-14-49-52" border="0"></a>

**Smartphone (please complete the following information):**

- Device: Xiaomi Mi A3
- OS: Android 10
- Version 1.0.0

**Additional context**

**Comment by marcouberti** [comment]
Cannot reproduce on my devices. Can you try changing the navigation bar type? (classic 3 dots buttons)

**Comment by eliseomartelli** [comment]
Already tried with the other types of navigation, the visual glitch is still there. 
I can provide a layout inspector dump if it's needed. 
 
https://ibb.co/5r8CLjr
https://ibb.co/zXHvP0g

**Comment by eliseomartelli** [comment]
**Follow up**

After some further testing on other devices (Xiaomi Mi A3 Lite, Xiaomi Mi A3, OnePlus 7), the visual glitch is present only on the Xiaomi Mi A3 (strange since it's an Android One device). 

The solution proposed by me in #53 _partially_ solves the problem of the inconsistency but the final result doesn't not resemble correctly the proposed design.
