### ISSUE TITLE
Comunica questo codice all'operatore sanitario in caricamento dati.

### ISSUE THREAD

**Issue by vastianazzo** [immuni-app/immuni-app-android#57]
# Issue content
Se i dati sono identificati da un codice alfanumerico che dovrebbe garantire l'anonimato, se, nel momento in cui "carico i dati" sul server centrale (dove?) e "devo" comunicare il mio codice all'operatore sanitario (che ovviamente mi sta identificando), come fa l'applicazione a garantire l'anonimato?
Chi è questo "operatore sanitario" a cui sto comunicando i dati? Cosa fa l'"operatore sanitario" quando "conferma il codice" che ho comunicato?

**Comment by vi-enne** [comment]
C'è un issue simile nella repo documentation [qui](github.com/immuni-app/immuni-documentation/issues/27)

**Comment by immuniopensource** [comment]
Buonasera @vastianazzo, siccome questa issue non è legata a questo repository rimando la discussione al repository di [documentation](https://github.com/immuni-app/immuni-documentation) e, in particolar modo, alla issue già segnalata da @vi-enne. Grazie ad entrambi!
