### ISSUE TITLE
[BUG] The shadows around the tiles are not by design

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#61]
**Describe the bug**

- [ ] In the Onboarding/Privacy screen the shadows around the checkbox tiles are not by design.
- [ ] In the Home screen the shadows around the Info tiles are not by design.

**To Reproduce**

1. Go to the Onboarding/Privacy screen
2. Scroll down
--> Observe the shadows around the checkbox tiles.
3. Go to the Home screen
--> Observe the shadows around the Info tiles.

**Screenshots**

![Screenshot_20200527-101256_Immuni](https://user-images.githubusercontent.com/57350395/82994915-2c7da800-a003-11ea-8155-14be552fa545.jpg)

![Screenshot_20200527-111617_Immuni](https://user-images.githubusercontent.com/57350395/83001206-b5004680-a00b-11ea-9b67-20910109c208.jpg)

**Comment by titaniabanfi** [comment]
fix verified
