### ISSUE TITLE
[BUG] In the Onboarding/Privacy screen by tapping on `Avanti` the two checkbox tiles are marked in red even though they were never visualized by the user

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#62]
**Describe the bug**

In the Onboarding/Privacy screen, by tapping on `Avanti`, users are brought to the end of the screen where the two checkbox tiles are already marked in red, even though they were never visualized by the user. 

**To Reproduce**

1. Go to the Onboarding/Privacy screen
2. Do not scroll down and tap on `Avanti`
--> Users are directed to the end of the screen and the two checkbox tiles are already marked in red.

**Expected behaviour**

The two checkbox tiles should turn red after being visualized and then pressing `Avanti`.

**Screenshots**

![Screenshot_20200527-103045_Immuni](https://user-images.githubusercontent.com/57350395/82996417-37d1d300-a005-11ea-8358-bb2880f12079.jpg)

**Comment by titaniabanfi** [comment]
closing - discussed offline
