### ISSUE TITLE
rimuvovere questa libreria poichè permetterebbe un accesso alla posizione anche se con una bassa granularità

### ISSUE THREAD

**Issue by ghost** [immuni-app/immuni-app-android#73]
https://github.com/immuni-app/immuni-app-android/blob/79911ea8f6b02f57354ccdb9811fa51163aa0dc1/extensions/src/main/java/it/ministerodellasalute/immuni/extensions/location/LocationStateFlow.kt#L22

come affermato del dalle specifiche della libreria, importando questa libreria lo sviluppatore potrebbe accedere alla posizione con una bassa granularità

"Unless noted, all Location API methods require the Manifest.permission.ACCESS_COARSE_LOCATION or Manifest.permission.ACCESS_FINE_LOCATION permissions. If your application only has the coarse permission then it will not have access to fine location providers. Other providers will still return location results, but the exact location will be obfuscated to a coarse level of accuracy.
Requires the PackageManager#FEATURE_LOCATION feature which can be detected using PackageManager.hasSystemFeature(String)."

https://developer.android.com/reference/android/location/LocationManager

**Comment by powext** [comment]
`android.location.LocationManager ` must be used by Immuni because BLE (and so Exposure Notifications) is enabled only if the localization services are checked, and you should notify the user if these are not.

As you can see there is only a feature function: `fun isLocationEnabled()` just to check if localization services are enabled.
You can also see that in the whole code there aren't any location providers permissions declarations so Immuni can't access Location API methods.

**Comment by vi-enne** [comment]
The issue is also discussed [here](https://github.com/immuni-app/immuni-documentation/issues/19), and it is still an open matter.

**Comment by oppo99** [comment]
A mio avviso utilizzare questa libreria potrebbe comportare, a seguito di un attacco con esecuzione del codice malevolo all'interno dell'app (come XSS https://github.com/immuni-app/immuni-app-android/issues/40#issue-624515033), la mappatura delle posizioni oltre al tracciamento dei contatti

**Comment by powext** [comment]
@oppo99 sry but the XSS attack consists of injecting **only JS scripts** into the browser and it could only get Intent or cookies data, so it can't inject some Kotlin code in some strange way.

As I said above Immuni can't access GPS data if it doesn't declare `Manifest.permission.ACCESS_COARSE_LOCATION` or `Manifest.permission.ACCESS_FINE_LOCATION`, so I don't see any problem here.

**Comment by FredBonux** [comment]
> A mio avviso utilizzare questa libreria potrebbe comportare, a seguito di un attacco con esecuzione del codice malevolo all'interno dell'app (come XSS [#40 (comment)](https://github.com/immuni-app/immuni-app-android/issues/40#issue-624515033)), la mappatura delle posizioni oltre al tracciamento dei contatti

Actually, I think #40 is closing as the related PR (#41) has been approved and it is now ready to merge.

>Given that the endpoints are down at the moment, I'm not able to verify if the TOS/FAQ/PP pages require JS to render properly. If that is the case, you probably want to hold-on on this PR till you find an alternative solution.

They are probably waiting for some checks on the TOS/FAQ/PP page side

**Comment by oppo99** [comment]
> @oppo99 sry but the XSS attack consists of injecting **only JS scripts** into the browser and it could only get Intent or cookies data, so it can't inject some Kotlin code in some strange way.
> 
> As I said above Immuni can't access GPS data if it doesn't declare `Manifest.permission.ACCESS_COARSE_LOCATION` or `Manifest.permission.ACCESS_FINE_LOCATION`, so I don't see any problem here.

ho sbagliato il rifermimento al XSS
