### ISSUE TITLE
[BUG] Two notifications are sent simultaneously when a contact at risk is detected

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#81]
**Describe the bug**

Two notifications are sent simultaneously when a contact at risk is detected (both OS and app notifications).

**To Reproduce**

1. Expose device A to another (B) that has turned positive
2. Wait until A detects the contagion risk and gets alerted
--> Device A receives two notifications simultaneously to alert the user of the risk.

Note that Immuni notification is sticky and the user need to tap on it to dismiss it, while the OS notification is dismissable without opening the app.

![Image from iOS](https://user-images.githubusercontent.com/57350395/83132431-ae440300-a0e1-11ea-9635-6d03b67f7cc2.jpg)

**Comment by marcouberti** [comment]
One is the app specific one, the other is the Google Exposure API one.

**Comment by serenadg** [comment]
FV
