### ISSUE TITLE
class OtpGenerator - Hardening nextOtpCode()

### ISSUE THREAD

**Issue by mchirivi** [immuni-app/immuni-app-android#82]
# Issue content
Sarebbe opportuno rinforzare la funzione aumentando il numero di caratteri, inserendo ad esempio le lettere minuscole e qualche carattere speciale, inoltre sarebbe opportuno inserire un algoritmo di Salt a protezione dell'hash.

**Comment by bfabio** [comment]
We're looking at a 25^9 key space here and ephemeral codes lasting [at most 150 seconds](https://github.com/immuni-app/immuni-backend-otp/blob/d718ab9153de7c364715d1c9eaab58103593f4e5/immuni_otp/core/config.py#L23) and I'm guessing half as long on the average case, where [the user completes the upload procedure](https://github.com/immuni-app/immuni-backend-exposure-ingestion/blob/4e34c712cf6289d40d0f822fadae2ce8e0654814/immuni_exposure_ingestion/apis/ingestion.py#L135). On top of that, I bet there's network level attack mitigation, so I think we're fine.

Reducing the alphabet and using a CRC are great UX choices, I wish software was built with this attention to detail more often. :1st_place_medal:

**Comment by oppo99** [comment]
dato lo spazio delle chiavi 25^9 un semplice script py riesce a generare 10^6 diverse combinazioni con anche il 10 bit di controllo in 6.6621527671813965 secondi quindi si possono generare tutte le chiavi in 25^9/10^6 *6.6621527671813965 /60 /60 /24 = 294.1446289831354220708211263020833333333333333333333333333... giorni con un solo dispositivo (poco potente), con 10 dispositivi le chiavi verrebbero generate in meno di un mese.
presumo che una mitigazione lato server sia fondamentale ma estendere le chiavi di un paio di caratteri al non sarebbe una cattiva idea.

**Comment by bfabio** [comment]
@oppo99 You're misunderstanding how OTPs are used in the app: they are only valid for a brief period of time once you give it to a health worker (who inserts it into the system) after being tested positive.

**Comment by oppo99** [comment]
@bfabio ho capito il funzionamento dell'otp, non ritengo che questo sia un problema se preso da solo ma in relazione a https://github.com/immuni-app/immuni-app-android/issues/121 potrebbe esserlo. la possibilità che due dispositivi vengano forzati ad avere lo stesso codice è correlato alla dimensione dello spazio delle chiavi
