### ISSUE TITLE
[BUG] Capitalization issues in FAQ copy

### ISSUE THREAD

**Issue by LauraB-QA** [immuni-app/immuni-app-android#84]
**Describe the bug**

Two capitalization issues in the FAQ for consistency with the rest of the copy:
immuni >> Immuni
bluetooth >> Bluetooth

**To Reproduce**

1. Go to FAQ
--> In one instance "immuni" and "bluetooth" are lowercase.

**Comment by mlocati** [comment]
IMHO bluetooth shouldn't be capitalized: it's a common name (would you say "motore a Benzina" or "motore a benzina"?).
Enciclopedia Treccani too writes it lowercase: see http://www.treccani.it/enciclopedia/bluetooth/

**Comment by madbat** [comment]
Fixed by the new FAQs added in #84

**Comment by LauraB-QA** [comment]
Fixed verified in build 58.
