### ISSUE TITLE
[BUG] I cannot complete the onboarding

### ISSUE THREAD

**Issue by mattiaferigutti** [immuni-app/immuni-app-android#89]
**Describe the bug**

When I arrive in the "Attiva le notifiche di esposizione COVID-19" section and I try to press the "Consenti" button I get this message "Notifiche di esposizione non attivate". 
The bug seems to be here where the `optInAndStartExposureTracing` gets an exception :
```
//OnboardingViewModel.kt
fun startExposureNotification(activity: Activity) {
        viewModelScope.launch {
            try {
                exposureManager.optInAndStartExposureTracing(activity)
            } catch (e: Exception) {
                toast(
                    activity.applicationContext,
                    activity.getString(R.string.onboarding_exposure_api_not_activated)
                )
                e.printStackTrace()
            }
        }
    }
```

**To Reproduce**

1. Delete your app data or just uninstall your app
2. Reinstall the app

**Expected behaviour**
I aspect I should be able to finish the onboarding without incurring in an error. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Pixel 4
- OS: Android 10

**Additional context**

**Comment by marcouberti** [comment]
Hi, as stated in the README only government apps can use the Apple/Google SDK. So this behaviour is expected.
