### ISSUE TITLE
[enhancement] App locked in portrait?

### ISSUE THREAD

**Issue by ndorigatti** [immuni-app/immuni-app-android#9]
https://github.com/immuni-app/immuni-app-android/blob/8c4739b471754977ea42b5cc2090cd28804a141f/app/src/main/AndroidManifest.xml#L34

It is really ugly to see app locked in portrait in 2020... with livedata, viewmodels and SavedStateViewModel!

**Comment by powext** [comment]
How would be this a priority, the app must be ready to be shipped in a few days and basically no one uses the smartphone in landscape mode except for watching media.

**Comment by ndorigatti** [comment]
not a priority, obviously, but an enhancement to consider.

**Comment by rscano** [comment]
> How would be this a priority, the app must be ready to be shipped in a few days and basically no one uses the smartphone in landscape mode except for watching media.

This is an accessibility requirement. Mandatory. Not an optional.

**Comment by medomatto** [comment]
There’s no need for pleasure and entertainment enhancements. This app has just to simply work.

**Comment by rscano** [comment]
> There’s no need for pleasure and entertainment enhancements. This app has just to simply work.

This is an accessibility requirement. Required by law. Mandatory. Here we are not play or develop a game but one mobile app that must confirm to en 301549 standard.

**Comment by powext** [comment]
> > There’s no need for pleasure and entertainment enhancements. This app has just to simply work.
> 
> This is an accessibility requirement. Required by law. Mandatory. Here we are not play or develop a game but one mobile app that must confirm to en 301549 standard that relay on wcag 2.1
> 
> Success Criterion 1.3.4 Orientation (Level AA)
> Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.

Please, provide a source with all the info.

**Comment by rscano** [comment]
> > > There’s no need for pleasure and entertainment enhancements. This app has just to simply work.
> > 
> > 
> > This is an accessibility requirement. Required by law. Mandatory. Here we are not play or develop a game but one mobile app that must confirm to en 301549 standard that relay on wcag 2.1
> > Success Criterion 1.3.4 Orientation (Level AA)
> > Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.
> 
> Please, provide a source with all the info.

Never hear about wcag? International standards? En 301549? Italian accessibility law? A baseline for developers. Use Google.

**Comment by powext** [comment]
@rscano I'm sorry for your embarrassment, seeing the [Linee guida 2019](https://trasparenza.agid.gov.it/moduli/downloadFile.php?file=oggetto_allegati/19356907350O__OLinee+Guida+Accessibilit%E0+versione+IR.pdf):

> 1. comma 1. Le disposizioni del presente decreto relative ai siti web e alle applicazioni mobili, ad eccezione di
> quanto disposto dall’articolo 11, comma 1, lettera a), della legge n. 4 del 2004, come sostituito dall'articolo 1,
> comma 10, del presente decreto, limitatamente ai siti web e alle applicazioni mobili, si applicano come segue:
> a. ai siti web non pubblicati prima del 23 settembre 2018: a decorrere dal 23 settembre 2019;
> b. ai siti web non contemplati dalla lettera a): a decorrere dal 23 settembre 2020;
> **c. alle applicazioni mobili: a decorrere dal 23 giugno 2021**

Again, I'm so sorry for your embarrassment, these are the baselines for developers, next time use Google.

**Comment by rscano** [comment]
I know them due i have develop them. But you don't know about law 67/2006. And in this case people that are discriminated receive money for discrimination. A lot of money. And this can be the case. And you are saying that actually they are no able to make this stupid interface accessible. Need to wait 2021. Great. So I will call you and them developer in 2021. For now for me you and them are a bad developer. Cheers.

**Comment by powext** [comment]
I agree with you that this standard is very important and it should be respected by Immuni shortly even if the team is not obliged. 
I also admit that I never thought about Accessibility in my short career, it has never been mentioned in my entire educational process (ITIS + Computer Science Bachelor) and this is a bad thing. 
So I thank you for this, I'm sorry for the friction between us, have a good evening.

**Comment by gvdr** [comment]
@immuniopensource this is a bug, as it limits accessibility, and it is potentially discriminatory. Please relabel the issue.

**Comment by Igaryu** [comment]
> How would be this a priority, the app must be ready to be shipped in a few days and basically _**no one uses the smartphone in landscape mode except for watching media.**_

This is no correct: Add example, if possible, I'd like to read FAQ in landscape mode on a mobile phone device!

J.C.

**Comment by ndorigatti** [comment]
@all I didn't want to start this "fight", i just wanted to note that nowadays it's not too difficult as before, given also the quality of libraries and architecture used in this app (and there also designers).
After that, the developers of this app have made choices and decide how and what to implement. 
Thank you for at least considering the feedback, and I'm really sorry for those 27 (at the moment) that downvoted my issue, laws or not, i find that allowing rotation is something we should give to users.
Just my 2cents.
