### ISSUE TITLE
[BUG] Cannot Enable Exposure Notifications

### ISSUE THREAD

**Issue by Dement0** [immuni-app/immuni-app-android#94]
**Describe the bug**

During the on-boarding, the app asks a permission to enable the COVID-19 exposure notifications. Even though the locations services have already been activated, when the "Allow" button is clicked, the app shows "Exposure notifications not enabled".

**To Reproduce**

1. Go to 'Enable COVID-19 exposure notifications'
2. Click on 'Allow'
3. See error as a Toast

**Expected behavior**

Although the instructions about the location services activation are not clear enough from the `Toast` message, I was expected to be redirected to the next page after allowing the exposure notifications.

**Screenshots**

![Screenshot_1590736690](https://user-images.githubusercontent.com/33685811/83232973-4e576600-a18e-11ea-9a3c-4c9a63e9038b.png)

![Screenshot_1590736644](https://user-images.githubusercontent.com/33685811/83232974-4f889300-a18e-11ea-8256-5e00d8481e24.png)

![Screenshot_1590736566](https://user-images.githubusercontent.com/33685811/83232978-50b9c000-a18e-11ea-825f-dc6db04b9bb3.png)

**Smartphone (please complete the following information):**

- Device: [Pixel 2]
- OS: [Android 10]
- Build Number: [QSR1.190920.001]

**Additional context**

The `Toast` message also should be more clear in order to prompt the user to check the location services.

**Comment by grausof** [comment]
Already widely discussed here: #21

`Please note that Google restricts the usage of the Exposure Notification API to government entities or developers approved by a government entity to develop an application on behalf of a government for COVID-19 response efforts. Full details are in the Additional Terms document. Otherwise, you may build and use the application, but you will not be able to use the underlying Exposure Notification system.`

**Comment by Dement0** [comment]
> Already widely discussed here: #21
> 
> `Please note that Google restricts the usage of the Exposure Notification API to government entities or developers approved by a government entity to develop an application on behalf of a government for COVID-19 response efforts. Full details are in the Additional Terms document. Otherwise, you may build and use the application, but you will not be able to use the underlying Exposure Notification system.`

Thanks for the pointer @grausof, I didn't understand that we were referencing the same issue.
